import { createSovietThreatModel } from "./model-helpers";
import type { ThreatDefinition } from "./types";

export const KH22 = {
  id: "Kh-22",
  profile: {
    cruiseAltitude: 360,
    terminalAltitude: 2.2,
    terminalAt: 450,
    cruiseSpeed: 13.2,
    terminalSpeed: 15.2,
    turnRate: 4.5,
    damage: 46,
    defaultRange: 1000,
    burnThroughRange: 26,
    radarCrossSection: 1.1,
    modelScale: 0.92,
    selectionRadius: 4.2,
    pathColor: 0xffb05a,
    threatPriority: 45,
    trajectory: "high-altitude",
    ciwsPenalty: 0.3,
    ciwsPkCap: 0.14,
    weave: {
      lateral: 0,
      longitudinal: 0,
      lateralRate: 0,
      longitudinalRate: 0,
    },
  },
  preset: {
    label: "HIGH SPEED",
    count: 8,
    interval: 2,
    altitude: 360,
    spread: 190,
    range: 1000,
  },
  createModel: () =>
    createSovietThreatModel({
      length: 11,
      radius: 0.72,
      skinColor: 0xb7b9ad,
      bandColor: 0xd8d9cf,
      noseLength: 2.8,
      wingSpan: 4.8,
      wingChord: 3.4,
      finThickness: 0.13,
      finHeight: 2.2,
      dorsalDetails: true,
      exhaustLength: 6,
      exhaustColor: 0xffd37a,
      mistRadius: 1.45,
      mistLength: 9,
      seekerRadius: 8,
      seekerLength: 30,
      shockCone: true,
    }),
} as const satisfies ThreatDefinition;
