import { createA6Model, createF14Model, createTu16Model } from "./models";
import type { AirPlatformDefinition, AirPlatformId, AirWeaponDefinition, AirWeaponId } from "./types";

export const AIR_WEAPONS: Readonly<Record<AirWeaponId, AirWeaponDefinition>> = {
  "AIM-54A": { id:"AIM-54A", name:"AIM-54A Phoenix", targets:["aircraft"], guidance:"active-radar", minRange:12, maxRange:470, speed:19, boostSeconds:6, maxTurnRateDeg:17, seekerRange:90, seekerFovDeg:55, datalinkInterval:0.8, damage:72, proximityRadius:5, countermeasureResistance:0.72 },
  "AIM-7F": { id:"AIM-7F", name:"AIM-7F Sparrow", targets:["aircraft"], guidance:"semi-active-radar", minRange:5, maxRange:190, speed:15, boostSeconds:4, maxTurnRateDeg:24, seekerRange:36, seekerFovDeg:42, datalinkInterval:0.4, damage:64, proximityRadius:4, countermeasureResistance:0.58 },
  "AIM-9L": { id:"AIM-9L", name:"AIM-9L Sidewinder", targets:["aircraft"], guidance:"infrared", minRange:2, maxRange:70, speed:12, boostSeconds:3, maxTurnRateDeg:42, seekerRange:52, seekerFovDeg:48, datalinkInterval:0.2, damage:58, proximityRadius:3.5, countermeasureResistance:0.52 },
  "KSR-5": { id:"KSR-5", name:"KSR-5 Kingfish", targets:["ship"], guidance:"anti-ship-radar", minRange:80, maxRange:900, speed:14, boostSeconds:8, maxTurnRateDeg:7, seekerRange:125, seekerFovDeg:50, datalinkInterval:1.2, damage:48, proximityRadius:8, countermeasureResistance:0.66 },
  "AGM-84A": { id:"AGM-84A", name:"AGM-84A Harpoon", targets:["ship"], guidance:"anti-ship-radar", minRange:25, maxRange:430, speed:6.2, boostSeconds:3, maxTurnRateDeg:12, seekerRange:115, seekerFovDeg:50, datalinkInterval:1, damage:22, proximityRadius:6, countermeasureResistance:0.64 },
};

const emptyLoadout = (): Record<AirWeaponId, number> => ({"AIM-54A":0,"AIM-7F":0,"AIM-9L":0,"KSR-5":0,"AGM-84A":0});
export const AIR_PLATFORM_DEFINITIONS: readonly AirPlatformDefinition[] = [
  { id:"F-14A", name:"F-14A Tomcat", nation:"United States", role:"Fleet air defense", mission:"cap", radarCrossSection:8, infraredSignature:1.1, flight:{cruiseSpeed:5.1,maxSpeed:11.5,stallSpeed:2.1,acceleration:1.1,drag:0.018,maxLoadFactor:7.5,maxRollRateDeg:120,maxPitchRateDeg:28,fuelSeconds:900}, sensor:{name:"AN/AWG-9",range:520,updateInterval:0.8,fieldOfViewDeg:120,precision:0.88}, ecm:{strength:0.56,burnThroughRange:35}, countermeasures:{chaff:30,flares:30,program:{chaffBurst:2,flareBurst:2,interval:0.18,cooldown:5,triggerTti:20}}, loadout:{...emptyLoadout(),"AIM-54A":4,"AIM-7F":2,"AIM-9L":2}, buildModel:createF14Model },
  { id:"TU-16K", name:"Tu-16K Badger-G", nation:"Soviet Union", role:"Maritime strike", mission:"anti-ship", radarCrossSection:28, infraredSignature:1.35, flight:{cruiseSpeed:4.2,maxSpeed:5.4,stallSpeed:1.8,acceleration:0.45,drag:0.022,maxLoadFactor:2.5,maxRollRateDeg:38,maxPitchRateDeg:10,fuelSeconds:1300}, sensor:{name:"Rubin-1K",range:600,updateInterval:1.5,fieldOfViewDeg:100,precision:0.7}, ecm:{strength:0.68,burnThroughRange:48}, countermeasures:{chaff:42,flares:18,program:{chaffBurst:4,flareBurst:2,interval:0.14,cooldown:4.5,triggerTti:26}}, loadout:{...emptyLoadout(),"KSR-5":1}, buildModel:createTu16Model },
  { id:"A-6E", name:"A-6E Intruder", nation:"United States", role:"All-weather strike", mission:"anti-ship", radarCrossSection:7, infraredSignature:1, flight:{cruiseSpeed:3.8,maxSpeed:5.5,stallSpeed:1.7,acceleration:0.62,drag:0.021,maxLoadFactor:6.5,maxRollRateDeg:95,maxPitchRateDeg:23,fuelSeconds:950}, sensor:{name:"AN/APQ-148",range:340,updateInterval:1.2,fieldOfViewDeg:100,precision:0.78}, ecm:{strength:0.52,burnThroughRange:28}, countermeasures:{chaff:24,flares:24,program:{chaffBurst:2,flareBurst:2,interval:0.2,cooldown:5,triggerTti:18}}, loadout:{...emptyLoadout(),"AGM-84A":2}, buildModel:createA6Model },
];
export const AIR_PLATFORM_BY_ID = Object.fromEntries(AIR_PLATFORM_DEFINITIONS.map(d=>[d.id,d])) as Record<AirPlatformId,AirPlatformDefinition>;
