import { createA6Model, createF14Model, createMig29Model, createTu16Model } from "./models";
import type { AirPlatformDefinition, AirPlatformId, AirWeaponDefinition, AirWeaponId } from "./types";

export const AIR_WEAPONS: Readonly<Record<AirWeaponId, AirWeaponDefinition>> = {
  "AIM-54A": { id:"AIM-54A", name:"AIM-54A Phoenix", targets:["aircraft"], guidance:"active-radar", minRange:12, maxRange:470, speed:19, boostSeconds:6, maxTurnRateDeg:17, seekerRange:90, seekerFovDeg:55, datalinkInterval:0.8, damage:72, proximityRadius:5, countermeasureResistance:0.72, shipDefenseTemplate:"Kh-22" },
  "AIM-7F": { id:"AIM-7F", name:"AIM-7F Sparrow", targets:["aircraft"], guidance:"semi-active-radar", minRange:5, maxRange:190, speed:15, boostSeconds:4, maxTurnRateDeg:24, seekerRange:36, seekerFovDeg:42, datalinkInterval:0.4, damage:64, proximityRadius:4, countermeasureResistance:0.58, shipDefenseTemplate:"Kh-22" },
  "AIM-9L": { id:"AIM-9L", name:"AIM-9L Sidewinder", targets:["aircraft"], guidance:"infrared", minRange:2, maxRange:70, speed:12, boostSeconds:3, maxTurnRateDeg:42, seekerRange:52, seekerFovDeg:48, datalinkInterval:0.2, damage:58, proximityRadius:3.5, countermeasureResistance:0.52, shipDefenseTemplate:"Kh-22" },
  "R-27R": { id:"R-27R", name:"R-27R Alamo-A", targets:["aircraft"], guidance:"semi-active-radar", minRange:6, maxRange:240, speed:14.5, boostSeconds:5, maxTurnRateDeg:25, seekerRange:42, seekerFovDeg:44, datalinkInterval:0.45, damage:66, proximityRadius:4.2, countermeasureResistance:0.6, shipDefenseTemplate:"Kh-22" },
  "R-73": { id:"R-73", name:"R-73 Archer", targets:["aircraft"], guidance:"infrared", minRange:1.5, maxRange:78, speed:11.5, boostSeconds:3.2, maxTurnRateDeg:48, seekerRange:58, seekerFovDeg:62, datalinkInterval:0.2, damage:56, proximityRadius:3.5, countermeasureResistance:0.56, shipDefenseTemplate:"Kh-22" },
  "KSR-5": { id:"KSR-5", name:"KSR-5 Kingfish", targets:["ship"], guidance:"anti-ship-radar", minRange:80, maxRange:900, speed:10.4, boostSeconds:8, maxTurnRateDeg:7, seekerRange:125, seekerFovDeg:50, datalinkInterval:1.2, damage:48, proximityRadius:8, countermeasureResistance:0.66, shipDefenseTemplate:"Kh-22", antiShipFlight:{boostAltitude:92,cruiseAltitude:6,terminalAltitude:.8,boostSpeedFactor:.72,cruiseSpeedFactor:.94,terminalTurnFactor:1.8} },
  "AGM-84A": { id:"AGM-84A", name:"AGM-84A Harpoon", targets:["ship"], guidance:"anti-ship-radar", minRange:25, maxRange:430, speed:6.2, boostSeconds:3, maxTurnRateDeg:12, seekerRange:115, seekerFovDeg:50, datalinkInterval:1, damage:22, proximityRadius:6, countermeasureResistance:0.64, shipDefenseTemplate:"RGM-84 Harpoon", antiShipFlight:{boostAltitude:4.5,cruiseAltitude:.9,terminalAltitude:.12,boostSpeedFactor:.72,cruiseSpeedFactor:.94,terminalTurnFactor:1.8} },
};

const emptyLoadout = (): Record<AirWeaponId, number> => ({"AIM-54A":0,"AIM-7F":0,"AIM-9L":0,"R-27R":0,"R-73":0,"KSR-5":0,"AGM-84A":0});
const fighterHardpoints = [
  ...[-1, 1].flatMap((side) => [
    { id:`wing-${side<0?"port":"starboard"}-outer`, position:[side*2.7,-.42,.15] as const, compatibleWeapons:["AIM-9L"] as const, releaseDelay:.18, ignitionDelay:.12 },
    { id:`wing-${side<0?"port":"starboard"}-inner`, position:[side*1.8,-.48,.45] as const, compatibleWeapons:["AIM-54A","AIM-7F"] as const, releaseDelay:.22, ignitionDelay:.16 },
  ]),
  ...[-1,1].flatMap((side)=>[0,1].map(index=>({id:`tunnel-${side<0?"port":"starboard"}-${index+1}`,position:[side*.62,-.64,-.5+index*1.35] as const,compatibleWeapons:["AIM-54A","AIM-7F"] as const,releaseDelay:.2,ignitionDelay:.14}))),
];
const badgerHardpoints = [
  { id:"centerline-ksr", position:[0,-1.15,.4] as const, compatibleWeapons:["KSR-5"] as const, releaseDelay:.65, ignitionDelay:.8 },
];
const intruderHardpoints = [-1,1].map(side=>({id:`wing-${side<0?"port":"starboard"}-strike`,position:[side*2.15,-.52,.25] as const,compatibleWeapons:["AGM-84A"] as const,releaseDelay:.35,ignitionDelay:.3}));
const fulcrumHardpoints = [-1, 1].flatMap((side) => [
  { id:`wing-${side<0?"port":"starboard"}-outer`, position:[side*2.65,-.38,.45] as const, compatibleWeapons:["R-73"] as const, releaseDelay:.16, ignitionDelay:.1 },
  { id:`wing-${side<0?"port":"starboard"}-middle`, position:[side*1.85,-.42,.25] as const, compatibleWeapons:["R-27R","R-73"] as const, releaseDelay:.2, ignitionDelay:.14 },
  { id:`wing-${side<0?"port":"starboard"}-inner`, position:[side*1.15,-.44,.05] as const, compatibleWeapons:["R-27R"] as const, releaseDelay:.22, ignitionDelay:.15 },
]);
export const AIR_PLATFORM_DEFINITIONS: readonly AirPlatformDefinition[] = [
  { id:"F-14A", name:"F-14A Tomcat", nation:"United States", role:"Fleet air defense", mission:"cap", radarCrossSection:8, infraredSignature:1.1, flight:{cruiseSpeed:5.1,maxSpeed:11.5,stallSpeed:2.1,acceleration:1.1,drag:0.018,maxLoadFactor:7.5,maxRollRateDeg:120,maxPitchRateDeg:28,fuelSeconds:900}, sensor:{name:"AN/AWG-9",range:520,updateInterval:0.8,fieldOfViewDeg:120,precision:0.88}, ecm:{strength:0.56,burnThroughRange:35}, countermeasures:{chaff:30,flares:30,program:{chaffBurst:2,flareBurst:2,interval:0.18,cooldown:5,triggerTti:20}}, loadout:{...emptyLoadout(),"AIM-54A":4,"AIM-7F":2,"AIM-9L":2}, fireControlChannels:{datalink:6,illumination:1}, hardpoints:fighterHardpoints, buildModel:createF14Model, shipDefenseTemplate:"Kh-22" },
  { id:"TU-16K", name:"Tu-16K Badger-G", nation:"Soviet Union", role:"Maritime strike", mission:"anti-ship", radarCrossSection:28, infraredSignature:1.35, flight:{cruiseSpeed:4.2,maxSpeed:5.4,stallSpeed:1.8,acceleration:0.45,drag:0.022,maxLoadFactor:2.5,maxRollRateDeg:38,maxPitchRateDeg:10,fuelSeconds:1300}, sensor:{name:"Rubin-1K",range:600,updateInterval:1.5,fieldOfViewDeg:100,precision:0.7}, ecm:{strength:0.68,burnThroughRange:48}, countermeasures:{chaff:42,flares:18,program:{chaffBurst:4,flareBurst:2,interval:0.14,cooldown:4.5,triggerTti:26}}, loadout:{...emptyLoadout(),"KSR-5":1}, fireControlChannels:{datalink:1,illumination:0}, hardpoints:badgerHardpoints, buildModel:createTu16Model, shipDefenseTemplate:"Kh-22" },
  { id:"A-6E", name:"A-6E Intruder", nation:"United States", role:"All-weather strike", mission:"anti-ship", radarCrossSection:7, infraredSignature:1, flight:{cruiseSpeed:3.8,maxSpeed:5.5,stallSpeed:1.7,acceleration:0.62,drag:0.021,maxLoadFactor:6.5,maxRollRateDeg:95,maxPitchRateDeg:23,fuelSeconds:950}, sensor:{name:"AN/APQ-148",range:340,updateInterval:1.2,fieldOfViewDeg:100,precision:0.78}, ecm:{strength:0.52,burnThroughRange:28}, countermeasures:{chaff:24,flares:24,program:{chaffBurst:2,flareBurst:2,interval:0.2,cooldown:5,triggerTti:18}}, loadout:{...emptyLoadout(),"AGM-84A":2}, fireControlChannels:{datalink:2,illumination:0}, hardpoints:intruderHardpoints, buildModel:createA6Model, shipDefenseTemplate:"Kh-22" },
  { id:"MIG-29A", name:"MiG-29A Fulcrum-A", nation:"Soviet Union", role:"Front-line fighter", mission:"intercept", radarCrossSection:5.2, infraredSignature:1.2, flight:{cruiseSpeed:5.3,maxSpeed:11.2,stallSpeed:2,acceleration:1.18,drag:0.018,maxLoadFactor:9,maxRollRateDeg:150,maxPitchRateDeg:34,fuelSeconds:720}, sensor:{name:"N019 Rubin",range:285,updateInterval:0.9,fieldOfViewDeg:110,precision:0.8}, ecm:{strength:0.46,burnThroughRange:30}, countermeasures:{chaff:30,flares:30,program:{chaffBurst:2,flareBurst:3,interval:0.16,cooldown:4.5,triggerTti:18}}, loadout:{...emptyLoadout(),"R-27R":4,"R-73":2}, fireControlChannels:{datalink:0,illumination:1}, hardpoints:fulcrumHardpoints, buildModel:createMig29Model, shipDefenseTemplate:"Kh-22" },
];
export const AIR_PLATFORM_BY_ID = Object.fromEntries(AIR_PLATFORM_DEFINITIONS.map(d=>[d.id,d])) as Record<AirPlatformId,AirPlatformDefinition>;
