import * as THREE from "three";
import type { CombatEntity, TargetableEntity } from "../combat-entity";
import { AIR_PLATFORM_BY_ID, AIR_WEAPONS } from "./catalog";
import type { AirCombatEvent, AirDecoyInstance, AirMissileInstance, AirPlatformInstance, AirShipDefenseContact, AirSpawn, AirSubsystem, AirTrack, AirWeaponId } from "./types";

const UP = new THREE.Vector3(0, 1, 0);
const clamp = THREE.MathUtils.clamp;
const angle = (a: THREE.Vector3, b: THREE.Vector3) => THREE.MathUtils.radToDeg(a.angleTo(b));
function roll(seed: number) { const x = Math.sin(seed * 12.9898 + 78.233) * 43758.5453; return x - Math.floor(x); }
function rotateToward(current: THREE.Vector3, desired: THREE.Vector3, radians: number) {
  const delta = current.angleTo(desired); if (delta < 1e-5) return desired.clone();
  const axis = current.clone().cross(desired); if (axis.lengthSq() < 1e-6) axis.copy(UP); else axis.normalize();
  return current.clone().applyAxisAngle(axis, Math.min(delta, radians)).normalize();
}

function instantiate(spawn: AirSpawn, serial: number): AirPlatformInstance {
  const model = spawn.definition.buildModel(); model.position.copy(spawn.position);
  const id = `${spawn.side}-${spawn.definition.id}-${serial}`;
  return { id, side:spawn.side, kind:"aircraft", position:model.position, velocity:spawn.heading.clone().normalize().multiplyScalar(spawn.definition.flight.cruiseSpeed), radarCrossSection:spawn.definition.radarCrossSection, infraredSignature:spawn.definition.infraredSignature, alive:true, definition:spawn.definition, model, formationId:spawn.formationId, formationIndex:spawn.formationIndex, leaderId:spawn.leaderId ?? null, mission:spawn.definition.mission, fuel:spawn.definition.flight.fuelSeconds, heading:spawn.heading.clone().normalize(), desiredDirection:spawn.heading.clone().normalize(), bank:0, tracks:new Map(), ammo:new Map(Object.entries(spawn.definition.loadout) as [AirWeaponId,number][]), subsystemHealth:new Map<AirSubsystem,number>([["structure",100],["left-engine",100],["right-engine",100],["radar",100],["flight-control",100],["weapons",100]]), nextOoda:0, nextScan:0, nextCountermeasure:0, chaff:spawn.definition.countermeasures.chaff, flares:spawn.definition.countermeasures.flares, state:"formation", targetId:null, shotAt:new Set() };
}

function missileModel(guidance: AirMissileInstance["definition"]["guidance"]) {
  const g=new THREE.Group(), radar=guidance!=="infrared", mat=new THREE.MeshStandardMaterial({color:radar?0xe6e3d6:0xd5d8d2,metalness:.55,roughness:.36});
  const body=new THREE.Mesh(new THREE.CylinderGeometry(.16,.2,2.2,10),mat);body.rotation.x=Math.PI/2;g.add(body);
  const nose=new THREE.Mesh(new THREE.ConeGeometry(.16,.65,10),new THREE.MeshStandardMaterial({color:radar?0x31383a:0x25201c,metalness:.4,roughness:.3}));nose.rotation.x=-Math.PI/2;nose.position.z=-1.42;g.add(nose);
  const flame=new THREE.Mesh(new THREE.ConeGeometry(.13,1.25,8,1,true),new THREE.MeshBasicMaterial({color:0xffa34f,transparent:true,opacity:.72,blending:THREE.AdditiveBlending,depthWrite:false}));flame.rotation.x=Math.PI/2;flame.position.z=1.7;g.add(flame);g.userData.flame=flame;return g;
}

export class AirCombatSystem {
  readonly group=new THREE.Group(); readonly aircraft:AirPlatformInstance[]=[]; readonly missiles:AirMissileInstance[]=[]; readonly decoys:AirDecoyInstance[]=[]; readonly events:AirCombatEvent[]=[];
  enabled=true; private serial=0; private lastEventIndex=0;
  constructor(private scene:THREE.Scene){this.group.name="air-combat";scene.add(this.group);}
  reset(blueShip:CombatEntity, redShip:CombatEntity|null){ this.disposeObjects(); this.serial=0;
    const spawns:AirSpawn[]=[
      ...this.pair("F-14A","blue","CAP-1",new THREE.Vector3(-170,72,-220),new THREE.Vector3(1,0,-.12)),
      ...this.pair("TU-16K","red","RAID-1",new THREE.Vector3(80,92,-250),new THREE.Vector3(-.15,-.01,1)),
      ...this.pair("A-6E","blue","STRIKE-1",new THREE.Vector3(-60,18,-220),new THREE.Vector3(.15,0,-1)),
    ];
    for(const spawn of spawns){const p=instantiate(spawn,++this.serial);this.aircraft.push(p);this.group.add(p.model);}
    for(const p of this.aircraft){ if(p.formationIndex>0){const leader=this.aircraft.find(x=>x.formationId===p.formationId&&x.formationIndex===0);p.leaderId=leader?.id??null;} }
    this.group.userData.context={blueShip,redShip};
  }
  private pair(id:"F-14A"|"TU-16K"|"A-6E",side:"blue"|"red",formationId:string,position:THREE.Vector3,heading:THREE.Vector3):AirSpawn[]{const d=AIR_PLATFORM_BY_ID[id];return [0,1].map(i=>({definition:d,side,formationId,position:position.clone().add(new THREE.Vector3((i?1:-1)*12,i*2, i?9:-4)),heading,formationIndex:i}));}
  private disposeObjects(){for(const o of [...this.aircraft.map(x=>x.model),...this.missiles.map(x=>x.model),...this.decoys.map(x=>x.model)]){this.group.remove(o);o.traverse(c=>{if(c instanceof THREE.Mesh){c.geometry.dispose();const m=c.material;if(Array.isArray(m))m.forEach(x=>x.dispose());else m.dispose();}});}this.aircraft.length=this.missiles.length=this.decoys.length=this.events.length=0;this.lastEventIndex=0;}
  dispose(){this.disposeObjects();this.scene.remove(this.group);}
  private emit(time:number,kind:AirCombatEvent["kind"],text:string){this.events.push({time,kind,text});}
  drainEvents(){const out=this.events.slice(this.lastEventIndex);this.lastEventIndex=this.events.length;return out;}
  private entities(context:{blueShip:CombatEntity;redShip:CombatEntity|null}){return [...this.aircraft.filter(a=>a.alive),...this.missiles.filter(m=>m.alive),...this.decoys.filter(d=>d.alive),context.blueShip,...(context.redShip?.alive?[context.redShip]:[])];}
  update(time:number,dt:number,context:{blueShip:CombatEntity;redShip:CombatEntity|null}){if(!this.enabled)return;this.group.userData.context=context;this.updateDecoys(dt);for(const a of this.aircraft)this.updateAircraft(a,time,dt,context);for(const m of this.missiles)this.updateMissile(m,time,dt,context);}

  shipDefenseContacts(targetId:string):AirShipDefenseContact[]{return [
    ...this.aircraft.filter(a=>a.alive&&a.side==="red").map(a=>({id:a.id,name:a.definition.name,category:"aircraft" as const,model:a.model,velocity:a.velocity,radarCrossSection:a.radarCrossSection,template:a.definition.shipDefenseTemplate,phase:"inbound" as const})),
    ...this.missiles.filter(m=>m.alive&&m.phase!=="destroyed"&&m.side==="red"&&m.targetId===targetId&&m.definition.targets.includes("ship")).map(m=>({id:m.id,name:m.definition.name,category:"missile" as const,model:m.model,velocity:m.velocity,radarCrossSection:m.radarCrossSection,template:m.definition.shipDefenseTemplate,phase:m.phase as "boost"|"midcourse"|"terminal"})),
  ];}
  destroyMissile(id:string){const missile=this.missiles.find(m=>m.id===id);if(!missile||!missile.alive)return false;missile.alive=false;missile.phase="destroyed";missile.model.visible=false;return true;}
  applyShipSamDamage(id:string,damage:number,point:THREE.Vector3,time:number){const target=this.aircraft.find(a=>a.id===id&&a.alive);if(!target)return null;this.damageTarget(target,damage,point,time);return target.alive?"survived":"destroyed";}
  private updateTracks(a:AirPlatformInstance,time:number,context:{blueShip:CombatEntity;redShip:CombatEntity|null}){if(time<a.nextScan||!a.alive)return;a.nextScan=time+a.definition.sensor.updateInterval;const radarHealth=(a.subsystemHealth.get("radar")??0)/100;
    for(const target of this.entities(context)){if(target.side===a.side||target.id===a.id||!target.alive)continue;const offset=target.position.clone().sub(a.position),range=offset.length(),effective=a.definition.sensor.range*Math.pow(Math.max(.05,target.radarCrossSection/8),.25)*radarHealth,boresight=angle(a.heading,offset);const probability=clamp(.96-Math.pow(range/Math.max(1,effective),2)*.7,0, .96)*radarHealth;
      const key=(time/a.definition.sensor.updateInterval|0)+this.serial+target.id.length+a.id.length;if(range<=effective&&boresight<=a.definition.sensor.fieldOfViewDeg*.5&&roll(key) < probability){const quality=clamp((1-range/effective)*.7+.24,0.08,.96),uncertainty=(1-quality)*18;const first=!a.tracks.has(target.id),classification=target.kind==="decoy"||target.kind==="missile"||quality<=.45?"unknown":target.kind==="ship"?"ship":"aircraft";a.tracks.set(target.id,{targetId:target.id,position:target.position.clone().add(new THREE.Vector3((roll(key+2)-.5)*uncertainty,(roll(key+3)-.5)*uncertainty*.35,(roll(key+4)-.5)*uncertainty)),velocity:target.velocity.clone(),quality,uncertainty,lastUpdate:time,classification});if(first)this.emit(time,"detect",`${a.definition.name} DETECT / ${classification.toUpperCase()} / TQ ${Math.round(quality*100)}%`);}
    }for(const [id,t] of a.tracks){t.position.addScaledVector(t.velocity,a.definition.sensor.updateInterval);t.quality=Math.max(0,t.quality-.018*a.definition.sensor.updateInterval);t.uncertainty+=.6*a.definition.sensor.updateInterval;if(time-t.lastUpdate>8||t.quality<.04)a.tracks.delete(id);}}
  private chooseWeapon(a:AirPlatformInstance,target:CombatEntity,range:number){return ([...a.ammo] as [AirWeaponId,number][]).filter(([,n])=>n>0).map(([id])=>AIR_WEAPONS[id]).filter(w=>w.targets.includes(target.kind==="ship"?"ship":"aircraft")&&range>=w.minRange&&range<=w.maxRange).sort((x,y)=>y.maxRange-x.maxRange)[0];}
  private launch(a:AirPlatformInstance,target:CombatEntity,track:AirTrack,time:number){const range=a.position.distanceTo(track.position),w=this.chooseWeapon(a,target,range);if(!w||(a.subsystemHealth.get("weapons")??0)<=5)return false;const model=missileModel(w.guidance);model.position.copy(a.position).addScaledVector(a.heading,2);const velocity=a.heading.clone().multiplyScalar(Math.max(a.velocity.length(),w.speed*.32));const commandPoint=track.position.clone().addScaledVector(track.velocity,w.datalinkInterval);const m:AirMissileInstance={id:`air-weapon-${++this.serial}`,side:a.side,kind:"missile",position:model.position,velocity,radarCrossSection:.12,infraredSignature:2.2,alive:true,definition:w,model,shooterId:a.id,targetId:target.id,age:0,phase:"boost",commandPoint,nextDatalink:time,seekerAcquired:w.guidance==="infrared",illuminationLostAt:null};this.missiles.push(m);this.group.add(model);a.ammo.set(w.id,(a.ammo.get(w.id)??0)-1);a.shotAt.add(target.id);if(a.mission==="anti-ship"){a.mission="egress";a.state="egress";}this.emit(time,"launch",`${a.definition.name} LAUNCH ${w.name} / ${range.toFixed(0)} wu / TRACK TQ ${Math.round(track.quality*100)}%`);return true;}
  private incomingFor(a:AirPlatformInstance){return this.missiles.filter(m=>m.alive&&m.side!==a.side&&m.targetId===a.id).sort((x,y)=>x.position.distanceTo(a.position)-y.position.distanceTo(a.position))[0];}
  private deployCountermeasures(a:AirPlatformInstance,m:AirMissileInstance,time:number){if(time<a.nextCountermeasure)return;const program=a.definition.countermeasures.program,isIr=m.definition.guidance==="infrared",count=Math.min(isIr?program.flareBurst:program.chaffBurst,isIr?a.flares:a.chaff);if(count<=0)return;for(let i=0;i<count;i++){const type=isIr?"flare":"chaff",mesh=new THREE.Mesh(type==="flare"?new THREE.SphereGeometry(.28,8,6):new THREE.IcosahedronGeometry(.6,1),new THREE.MeshBasicMaterial({color:type==="flare"?0xffb05d:0xb8e8e4,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false}));mesh.position.copy(a.position).add(new THREE.Vector3((i-.5)*1.4,-.4,1));const d:AirDecoyInstance={id:`${type}-${++this.serial}`,side:a.side,kind:"decoy",position:mesh.position,velocity:a.velocity.clone().multiplyScalar(.65).add(new THREE.Vector3((roll(this.serial)-.5)*1.5,-.3,(roll(this.serial+1)-.5)*1.5)),radarCrossSection:type==="chaff"?18:.02,infraredSignature:type==="flare"?4:.02,alive:true,decoyType:type,model:mesh,age:0,life:type==="chaff"?14:5};this.decoys.push(d);this.group.add(mesh);}if(isIr)a.flares-=count;else a.chaff-=count;a.nextCountermeasure=time+program.cooldown;this.emit(time,"countermeasure",`${a.definition.name} ${isIr?"FLARE":"CHAFF"} / ${count} ROUNDS`);}
  private updateAircraft(a:AirPlatformInstance,time:number,dt:number,context:{blueShip:CombatEntity;redShip:CombatEntity|null}){if(!a.alive){if(a.state==="disabled"){a.velocity.y-=.18*dt;a.model.rotation.z+=dt*.7;a.position.addScaledVector(a.velocity,dt);if(a.position.y<=.2){a.position.y=.2;a.state="crashed";a.model.visible=false;this.emit(time,"kill",`${a.definition.name} IMPACTED SEA`);}}return;}this.updateTracks(a,time,context);a.fuel=Math.max(0,a.fuel-dt);if(a.fuel<=0)a.mission="return";if(a.mission==="cap"&&!this.aircraft.some(other=>other.alive&&other.side!==a.side)&&!this.missiles.some(m=>m.alive&&m.side!==a.side)){a.mission="return";a.state="egress";}if(a.mission==="egress"||a.mission==="return"){a.state="egress";a.desiredDirection.set(a.side==="blue"?-1:1,.04,1).normalize();}
    const incoming=this.incomingFor(a);if(incoming){const range=incoming.position.distanceTo(a.position),tti=range/Math.max(1,incoming.velocity.length());a.state="defending";a.desiredDirection.copy(incoming.velocity).normalize().cross(UP).normalize().multiplyScalar(a.formationIndex?1:-1);if(tti<a.definition.countermeasures.program.triggerTti)this.deployCountermeasures(a,incoming,time);if(a.mission==="anti-ship"&&time>=a.nextOoda){a.nextOoda=time+1;const ship=this.entities(context).find(entity=>entity.side!==a.side&&entity.kind==="ship"&&entity.alive&&a.tracks.has(entity.id)),track=ship?a.tracks.get(ship.id):undefined;if(ship&&track&&!a.shotAt.has(ship.id))this.launch(a,ship,track,time);}}
    else if(a.mission!=="egress"&&a.mission!=="return"&&time>=a.nextOoda){a.nextOoda=time+1.0;const candidates=this.entities(context).filter(e=>e.side!==a.side&&e.alive&&a.tracks.has(e.id));let target:CombatEntity|undefined;if(a.mission==="anti-ship")target=candidates.find(e=>e.kind==="ship");else target=candidates.filter(e=>e.kind==="aircraft").sort((x,y)=>x.position.distanceTo(a.position)-y.position.distanceTo(a.position))[0];a.targetId=target?.id??null;
      if(target){const track=a.tracks.get(target.id)!;a.state="engaging";a.desiredDirection.copy(track.position).sub(a.position).normalize();if(track.quality>=.22&&!a.shotAt.has(target.id))this.launch(a,target,track,time);}
      else {const leader=this.aircraft.find(x=>x.id===a.leaderId&&x.alive);if(leader){const offset=new THREE.Vector3(a.formationIndex%2?12:-12,2,10).applyQuaternion(leader.model.quaternion);a.desiredDirection.copy(leader.position).add(offset).sub(a.position).normalize();}else if(a.mission==="anti-ship"){const ship=a.side==="red"?context.blueShip:context.redShip;if(ship?.alive)a.desiredDirection.copy(ship.position).sub(a.position).normalize();}else a.desiredDirection.set(a.side==="blue"?.25:-.25,0,a.side==="blue"?-1:1).normalize();}}
    const fc=(a.subsystemHealth.get("flight-control")??0)/100,eng=((a.subsystemHealth.get("left-engine")??0)+(a.subsystemHealth.get("right-engine")??0))/200,flight=a.definition.flight,speed=a.velocity.length(),availableG=1+(flight.maxLoadFactor-1)*clamp((speed-flight.stallSpeed)/(flight.cruiseSpeed-flight.stallSpeed),0,1)*fc,maxTurn=THREE.MathUtils.degToRad(flight.maxPitchRateDeg)*availableG/flight.maxLoadFactor;const next=rotateToward(a.heading,a.desiredDirection,maxTurn*dt);const yawDelta=Math.atan2(a.heading.clone().cross(next).y,a.heading.dot(next));a.bank=clamp(a.bank+yawDelta*3,-1.15,1.15);a.heading.copy(next);const targetSpeed=(a.state==="defending"?flight.maxSpeed:flight.cruiseSpeed)*eng,accel=clamp(targetSpeed-speed,-flight.drag*speed*speed,flight.acceleration*eng)*dt;const climbCost=Math.max(0,a.heading.y)*.45;const newSpeed=clamp(speed+accel-climbCost*dt,flight.stallSpeed*.72,flight.maxSpeed);if(newSpeed<flight.stallSpeed){a.heading.y=Math.max(-.18,a.heading.y-.25*dt);a.state="defending";}a.velocity.copy(a.heading).multiplyScalar(newSpeed);a.position.addScaledVector(a.velocity,dt);a.position.y=Math.max(.25,a.position.y);a.model.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),a.heading);a.model.rotateZ(-a.bank);
    const wings=a.model.userData.variableWings as THREE.Object3D[]|undefined;if(wings){const sweep=THREE.MathUtils.lerp(.28,.9,clamp((newSpeed-flight.cruiseSpeed)/(flight.maxSpeed-flight.cruiseSpeed),0,1));wings.forEach((w,i)=>w.rotation.y=(i?.0:0)+(i%2?1:-1)*sweep);}
  }
  private targetById(id:string,context:{blueShip:CombatEntity;redShip:CombatEntity|null}){return this.entities(context).find(e=>e.id===id);}
  private updateMissile(m:AirMissileInstance,time:number,dt:number,context:{blueShip:CombatEntity;redShip:CombatEntity|null}){if(!m.alive)return;m.age+=dt;const target=this.targetById(m.targetId,context);if(!target){m.alive=false;m.phase="destroyed";m.model.visible=false;return;}const shooter=this.aircraft.find(a=>a.id===m.shooterId),range=m.position.distanceTo(target.position),toTarget=target.position.clone().sub(m.position).normalize();if(m.age>=m.definition.boostSeconds)m.phase=range<=m.definition.seekerRange?"terminal":"midcourse";
    if(m.phase==="midcourse"&&time>=m.nextDatalink){m.nextDatalink=time+m.definition.datalinkInterval;const track=shooter?.tracks.get(target.id);if(track)m.commandPoint.copy(track.position).addScaledVector(track.velocity,m.definition.datalinkInterval);}
    if(m.phase==="terminal"&&!m.seekerAcquired&&range<=m.definition.seekerRange&&angle(m.velocity,toTarget)<=m.definition.seekerFovDeg*.5){m.seekerAcquired=true;}
    if(m.definition.guidance==="semi-active-radar"){const illuminating=!!shooter?.alive&&!!shooter.tracks.get(target.id);if(!illuminating)m.illuminationLostAt??=time;else m.illuminationLostAt=null;if(m.illuminationLostAt!==null&&time-m.illuminationLostAt>1.5){m.alive=false;m.phase="destroyed";m.model.visible=false;this.emit(time,"maneuver",`${m.definition.name} LOST ILLUMINATION`);return;}}
    let aim=m.seekerAcquired?target.position.clone():m.commandPoint.clone();const matching=this.decoys.filter(d=>d.alive&&d.side===target.side&&d.position.distanceTo(target.position)<30&&angle(m.velocity,d.position.clone().sub(m.position))<=m.definition.seekerFovDeg*.5&&((m.definition.guidance==="infrared"&&d.decoyType==="flare")||(m.definition.guidance!=="infrared"&&d.decoyType==="chaff"))).sort((a,b)=>a.position.distanceTo(m.position)-b.position.distanceTo(m.position))[0];if(m.seekerAcquired&&matching&&matching.position.distanceTo(m.position)<range){const signal=m.definition.guidance==="infrared"?matching.infraredSignature:matching.radarCrossSection;const targetSignal=m.definition.guidance==="infrared"?target.infraredSignature:target.radarCrossSection,ecm=target.kind==="aircraft"?(target as AirPlatformInstance).definition.ecm:undefined,burned=range<=(ecm?.burnThroughRange??0),capture=(signal/(signal+targetSignal))*(1-m.definition.countermeasureResistance)+(burned?0:(ecm?.strength??0)*.2);if(roll(this.serial+m.age*7)<capture*dt*2.2){aim=matching.position.clone();m.targetId=matching.id;this.emit(time,"countermeasure",`${m.definition.name} DECOY CAPTURE / ${matching.decoyType.toUpperCase()}`);}}
    const desired=aim.sub(m.position).normalize(),turn=THREE.MathUtils.degToRad(m.definition.maxTurnRateDeg)*dt;m.velocity.copy(rotateToward(m.velocity.clone().normalize(),desired,turn).multiplyScalar(THREE.MathUtils.lerp(m.velocity.length(),m.definition.speed,Math.min(1,dt*1.8))));m.position.addScaledVector(m.velocity,dt);m.model.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),m.velocity.clone().normalize());const flame=m.model.userData.flame as THREE.Mesh|undefined;if(flame)flame.visible=m.age<m.definition.boostSeconds;
    if(range<=m.definition.proximityRadius){if(target.kind==="decoy"){m.alive=false;m.phase="destroyed";m.model.visible=false;return;}if(target.kind==="missile"){const intercepted=target as AirMissileInstance;intercepted.alive=false;intercepted.phase="destroyed";intercepted.model.visible=false;this.emit(time,"kill",`${m.definition.name} INTERCEPT / ${intercepted.definition.name}`);}else this.damageTarget(target,m.definition.damage,m.position,time);m.alive=false;m.phase="destroyed";m.model.visible=false;this.emit(time,"hit",`${m.definition.name} HIT / ${target.id}`);}else if(m.age>180||m.position.y<0){m.alive=false;m.phase="destroyed";m.model.visible=false;}
  }
  private damageTarget(target:CombatEntity,damage:number,point:THREE.Vector3,time:number){if(target.kind==="aircraft"){const a=target as AirPlatformInstance,systems:AirSubsystem[]=["structure","left-engine","right-engine","radar","flight-control","weapons"],system=systems[Math.floor(roll(this.serial+time)*systems.length)],before=a.subsystemHealth.get(system)??100;a.subsystemHealth.set(system,Math.max(0,before-damage*(system==="structure"?1:.75)));const structure=a.subsystemHealth.get("structure")??0;this.emit(time,"damage",`${a.definition.name} ${system.toUpperCase()} DAMAGE / ${Math.round(a.subsystemHealth.get(system)??0)}%`);if(structure<=20||((a.subsystemHealth.get("left-engine")??0)<=5&&(a.subsystemHealth.get("right-engine")??0)<=5)){a.alive=false;a.state="disabled";this.emit(time,"kill",`${a.definition.name} MISSION KILL`);}}else if("applyDamage" in target)(target as TargetableEntity).applyDamage(damage,point);
  }
  private updateDecoys(dt:number){for(const d of this.decoys){if(!d.alive)continue;d.age+=dt;d.position.addScaledVector(d.velocity,dt);d.velocity.multiplyScalar(Math.max(0,1-dt*.12));d.velocity.y-=dt*.05;const mesh=d.model as THREE.Mesh,mat=mesh.material as THREE.MeshBasicMaterial;mat.opacity=Math.max(0,.85*(1-d.age/d.life));d.model.scale.setScalar(1+d.age*(d.decoyType==="chaff"?.32:.06));if(d.age>=d.life){d.alive=false;d.model.visible=false;}}}
  diagnostics(){const live=this.aircraft.filter(a=>a.alive),ksr=this.missiles.filter(m=>m.definition.id==="KSR-5");return {aircraft:this.aircraft.length,live:live.length,blueLive:live.filter(a=>a.side==="blue").length,redLive:live.filter(a=>a.side==="red").length,missiles:this.missiles.length,activeMissiles:this.missiles.filter(m=>m.alive).length,chaff:this.decoys.filter(d=>d.alive&&d.decoyType==="chaff").length,flares:this.decoys.filter(d=>d.alive&&d.decoyType==="flare").length,launches:this.events.filter(e=>e.kind==="launch").length,hits:this.events.filter(e=>e.kind==="hit").length,kills:this.events.filter(e=>e.kind==="kill").length,ksrMaximumSpeed:Math.max(0,...ksr.map(m=>m.velocity.length()))};}
  hasActiveCombat(){return this.missiles.some(m=>m.alive)||this.aircraft.some(a=>a.alive&&a.state!=="egress"&&a.mission!=="return");}
  focusTarget(){return this.missiles.find(m=>m.alive)?.model??this.aircraft.find(a=>a.alive)?.model??null;}
}
