import * as THREE from 'three';
import './style.css';
import { CombatPicture } from './sim';

type EnemyType='P-500'|'P-700'|'Kh-22';
type Missile={mesh:THREE.Group; velocity:THREE.Vector3; phase:'inbound'|'boost'|'midcourse'|'terminal'|'destroyed'; age:number; history:THREE.Vector3[]; path:THREE.Line; kind:EnemyType; speedFactor:number; rcs:number; launchAt:number; aimOffset:THREE.Vector3;};
type Interceptor={mesh:THREE.Group; target:Missile; age:number; weapon:'RIM-67'|'SM-2MR'; velocity:THREE.Vector3; distanceTraveled:number; history:THREE.Vector3[]; guidancePath:THREE.Line; commandPoint:THREE.Vector3; commandVelocity:THREE.Vector3; nextDatalink:number; datalinkValid:boolean; illuminated:boolean; illuminationBeam:THREE.Line;};
type Explosion={core:THREE.Mesh; ring:THREE.Mesh; light:THREE.PointLight; age:number;};
const canvas=document.querySelector('#scene') as HTMLCanvasElement;
const scene=new THREE.Scene(); scene.fog=new THREE.Fog(0x06111b,180,900); scene.background=new THREE.Color(0x06111b);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,2000); camera.position.set(120,95,150); camera.lookAt(0,0,0);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
scene.add(new THREE.HemisphereLight(0x9cc7dd,0x10212b,1.55)); const sun=new THREE.DirectionalLight(0xffe3ad,2.5); sun.position.set(-120,200,100);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-250;sun.shadow.camera.right=250;sun.shadow.camera.top=250;sun.shadow.camera.bottom=-250;scene.add(sun);
const seaGeometry=new THREE.PlaneGeometry(1800,1800,64,64);const sea=new THREE.Mesh(seaGeometry,new THREE.MeshStandardMaterial({color:0x0a3340,roughness:.68,metalness:.18,flatShading:false})); sea.rotation.x=-Math.PI/2; scene.add(sea);const seaPositions=seaGeometry.attributes.position as THREE.BufferAttribute;const seaBase=Float32Array.from(seaPositions.array as ArrayLike<number>);
const grid=new THREE.GridHelper(1200,48,0x1d6570,0x123f4b); grid.position.y=.15; (grid.material as THREE.Material).opacity=.25; (grid.material as THREE.Material).transparent=true; scene.add(grid);
function createHullGeometry(){
 const sections=[[-26,.7],[-20,3.4],[-12,4.4],[10,4.6],[18,3.8],[29,.25]] as const;
 const vertices:number[]=[],indices:number[]=[];
 for(const [x,w] of sections)vertices.push(x,6,-w,x,6,w,x,.4,-w*.58,x,.4,w*.58);
 for(let i=0;i<sections.length-1;i++){const a=i*4,b=(i+1)*4;indices.push(a,a+1,b+1,a,b+1,b,a+2,b+2,b+3,a+2,b+3,a+3,a,a+2,b+2,a,b+2,b,a+1,b+1,b+3,a+1,b+3,a+3);}
 indices.push(0,4,5,0,5,1,(sections.length-1)*4,(sections.length-1)*4+1,(sections.length-1)*4+3,(sections.length-1)*4,(sections.length-1)*4+3,(sections.length-1)*4+2);
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;
}
function createHullNumberTexture(){const c=document.createElement('canvas');c.width=128;c.height=64;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,128,64);ctx.fillStyle='#e8ece5';ctx.font='bold 46px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('9',64,34);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
function ship(color:number,scale=1){
 const g=new THREE.Group(); g.scale.setScalar(scale);
 const hullMat=new THREE.MeshStandardMaterial({color,metalness:.72,roughness:.32});
 const deckMat=new THREE.MeshStandardMaterial({color:0x707d7c,metalness:.35,roughness:.6});
 const darkMat=new THREE.MeshStandardMaterial({color:0x263538,metalness:.5,roughness:.45});
 const hull=new THREE.Mesh(createHullGeometry(),hullMat);g.add(hull);
 const deckShape=new THREE.Shape(); deckShape.moveTo(-25,0);deckShape.lineTo(-18,-4.2);deckShape.lineTo(16,-4.2);deckShape.lineTo(29,0);deckShape.lineTo(16,4.2);deckShape.lineTo(-18,4.2);deckShape.closePath(); const mainDeck=new THREE.Mesh(new THREE.ShapeGeometry(deckShape),deckMat); mainDeck.rotation.x=-Math.PI/2;mainDeck.position.y=6.05;g.add(mainDeck);
 const waterline=new THREE.Mesh(createHullGeometry(),new THREE.MeshStandardMaterial({color:0x151d20,roughness:.75}));waterline.scale.set(1.002,.28,1.002);waterline.position.y=-.1;g.add(waterline);
 const keel=new THREE.Mesh(new THREE.BoxGeometry(24,.7,2.8),darkMat); keel.position.set(-1,.15,0); g.add(keel);
 const aftDeck=new THREE.Mesh(new THREE.BoxGeometry(13,.7,8),deckMat); aftDeck.position.set(-10,6,0); g.add(aftDeck);
 const bridge=new THREE.Mesh(new THREE.BoxGeometry(11,5.5,6.5),deckMat); bridge.position.set(5,8,0); g.add(bridge);
 const bridgeRoof=new THREE.Mesh(new THREE.BoxGeometry(13,.8,7.2),darkMat); bridgeRoof.position.set(5,11,0); g.add(bridgeRoof);
 const mast=new THREE.Mesh(new THREE.CylinderGeometry(.45,.7,20,8),darkMat); mast.position.set(1,20,0); g.add(mast);
 const yard=new THREE.Mesh(new THREE.BoxGeometry(11,.35,.35),darkMat); yard.position.set(1,24,0); g.add(yard);
 const radar=new THREE.Group(); radar.position.set(1,24,0); const dish=new THREE.Mesh(new THREE.BoxGeometry(5.8,4.3,.45),new THREE.MeshStandardMaterial({color:0x9caaa6,metalness:.35,roughness:.52})); dish.rotation.z=.08; radar.add(dish); const backing=new THREE.Mesh(new THREE.BoxGeometry(3.8,3.1,1.1),darkMat);backing.position.z=-.65;radar.add(backing);for(let x=-2;x<=2;x++)for(let y=-1;y<=1;y++){const cell=new THREE.Mesh(new THREE.BoxGeometry(.65,.65,.12),new THREE.MeshStandardMaterial({color:0xc1cbc5,metalness:.3,roughness:.5}));cell.position.set(x,y*1.05,.3);radar.add(cell);} const feed=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,2.8,8),darkMat);feed.rotation.x=Math.PI/2;feed.position.z=1.6;radar.add(feed);g.add(radar);
 const fireControl=new THREE.Group(); fireControl.position.set(8,12,0); fireControl.add(new THREE.Mesh(new THREE.SphereGeometry(1.6,12,8),new THREE.MeshStandardMaterial({color:0x9ba9a6,metalness:.5,roughness:.45}))); g.add(fireControl);
 const launcher=new THREE.Group(); launcher.position.set(-10,7,0); launcher.userData.arms=[];launcher.add(new THREE.Mesh(new THREE.BoxGeometry(8,1.2,5.5),darkMat)); for(const z of [-2.1,2.1]){const rail=new THREE.Mesh(new THREE.BoxGeometry(7,.4,.28),deckMat); rail.position.set(0,1,z); launcher.add(rail);} g.add(launcher);
 const pivot=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.5,1.3,12),darkMat);pivot.position.y=1.1;launcher.add(pivot);for(const z of [-1.8,1.8]){const arm=new THREE.Group();launcher.userData.arms.push(arm);const beam=new THREE.Mesh(new THREE.BoxGeometry(8,.35,.45),deckMat);beam.position.set(2.5,2,z);arm.add(beam);const readyRound=new THREE.Mesh(new THREE.CylinderGeometry(.22,.28,5.5,8),new THREE.MeshStandardMaterial({color:0xd0d4ca,metalness:.45,roughness:.35}));readyRound.rotation.z=Math.PI/2;readyRound.position.set(3,2.35,z);arm.add(readyRound);launcher.add(arm);}
 const windowMat=new THREE.MeshStandardMaterial({color:0x75d8d4,emissive:0x164b4a,emissiveIntensity:1.8}); const windows=new THREE.Group();for(let z=-2.3;z<=2.3;z+=1.15){const pane=new THREE.Mesh(new THREE.BoxGeometry(.18,.5,.72),windowMat);pane.position.set(10.58,9.6,z);windows.add(pane);}for(const side of [-1,1])for(let x=1.5;x<=8.5;x+=1.4){const pane=new THREE.Mesh(new THREE.BoxGeometry(.72,.5,.18),windowMat);pane.position.set(x,9.6,side*3.33);windows.add(pane);}g.add(windows);
 const upperBridge=new THREE.Mesh(new THREE.BoxGeometry(7,2.4,5.2),deckMat); upperBridge.position.set(4,13,0); g.add(upperBridge);
 const aftHouse=new THREE.Mesh(new THREE.BoxGeometry(8,3.2,6),deckMat); aftHouse.position.set(-7,8.2,0); g.add(aftHouse);
 const stack=new THREE.Mesh(new THREE.CylinderGeometry(1.1,1.35,5,10),darkMat); stack.position.set(-4,12.3,0); g.add(stack);
 const gunMount=new THREE.Group(); gunMount.position.set(15,7,0); const turret=new THREE.Mesh(new THREE.CylinderGeometry(2,2.4,1.5,10),deckMat); gunMount.add(turret); const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.22,.3,7,8),darkMat); barrel.rotation.z=Math.PI/2; barrel.position.set(3.5,1,0); gunMount.add(barrel); g.add(gunMount);
 const aftDirector=new THREE.Group(); aftDirector.position.set(-7,12,0); aftDirector.add(new THREE.Mesh(new THREE.SphereGeometry(1.3,12,8),new THREE.MeshStandardMaterial({color:0x9ba9a6,metalness:.5,roughness:.45}))); g.add(aftDirector);
 const arrayFrame=new THREE.Mesh(new THREE.BoxGeometry(5.5,4,.25),darkMat);arrayFrame.position.set(1,21.5,0);arrayFrame.rotation.z=.08;g.add(arrayFrame);for(let x=-2;x<=2;x++)for(let y=-1;y<=1;y++){const element=new THREE.Mesh(new THREE.BoxGeometry(.55,.55,.18),new THREE.MeshStandardMaterial({color:0x8fa29f,metalness:.4,roughness:.5}));element.position.set(1+x*.9,21.5+y*.9,.22);g.add(element);}
 for(const side of [-1,1]){const rail=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,42,6),new THREE.MeshStandardMaterial({color:0xa5afaa,metalness:.5,roughness:.5}));rail.rotation.z=Math.PI/2;rail.position.set(-1,7,side*4.15);g.add(rail);for(let x=-19;x<=18;x+=4){const post=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,1.2,6),darkMat);post.position.set(x,6.5,side*4.15);g.add(post);}}
 for(const side of [-1,1])for(const x of [-5,-1]){const raft=new THREE.Mesh(new THREE.CylinderGeometry(.45,.45,2.2,10),new THREE.MeshStandardMaterial({color:0xe6ded0,roughness:.65}));raft.rotation.x=Math.PI/2;raft.position.set(x,8.1,side*3.8);g.add(raft);}
 for(const x of [-5,5]){const antenna=new THREE.Mesh(new THREE.CylinderGeometry(.04,.04,7,6),darkMat);antenna.position.set(x,17,0);antenna.rotation.z=x<0?-.18:.18;g.add(antenna);}
 const numberMat=new THREE.MeshBasicMaterial({map:createHullNumberTexture(),transparent:true,side:THREE.DoubleSide,depthWrite:false});for(const side of [-1,1]){const number=new THREE.Mesh(new THREE.PlaneGeometry(3.2,1.6),numberMat);number.position.set(17.5,3.7,side*4.02);number.rotation.y=side>0?0:Math.PI;g.add(number);const nav=new THREE.PointLight(side>0?0x36ff78:0xff3a32,3,18);nav.position.set(6,14,side*3.7);g.add(nav);}
 for(const side of [-1,1]){const anchor=new THREE.Mesh(new THREE.TorusGeometry(.45,.12,8,16),darkMat);anchor.position.set(21,3.2,side*3.1);anchor.rotation.x=Math.PI/2;g.add(anchor);}
 for(const x of [-15,-10,10]){const hatch=new THREE.Mesh(new THREE.BoxGeometry(2.2,.16,1.4),darkMat);hatch.position.set(x,6.3,0);g.add(hatch);}
 for(const x of [-14,-8,0,8,14]){const bollard=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,.8,8),darkMat); bollard.position.set(x,6.5,4); g.add(bollard);}
 g.userData={radar,fireControl,launcher,detail:[radar,fireControl,launcher,windows]};
 return g;
}
const defender=ship(0x4b5a59); defender.position.set(0,0,40);defender.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(defender);
const wakeMat=new THREE.MeshBasicMaterial({color:0xc5eff0,transparent:true,opacity:.16,depthWrite:false,side:THREE.DoubleSide});const wake=new THREE.Mesh(new THREE.ConeGeometry(10,48,3),wakeMat);wake.rotation.z=Math.PI/2;wake.rotation.x=Math.PI/2;wake.position.set(-42,.22,40);scene.add(wake);
const missiles:Missile[]=[]; const interceptors:Interceptor[]=[]; const combatPicture=new CombatPicture(); const radarCanvas=document.querySelector('#radar') as HTMLCanvasElement; const radarCtx=radarCanvas?.getContext('2d');
const lastTrackClasses=new Map<number,string>();
const explosions:Explosion[]=[];
const explodedTargets=new Set<Missile>();
const weaponProfiles={
 'RIM-67':{minRange:18,maxRange:245,maxSpeed:54,boost:2.4,acceleration:25,turnRate:THREE.MathUtils.degToRad(24),terminalRange:68},
 'SM-2MR':{minRange:12,maxRange:165,maxSpeed:68,boost:1.8,acceleration:36,turnRate:THREE.MathUtils.degToRad(32),terminalRange:62}
} as const;
const incomingProfiles={
 'P-500':{cruiseAltitude:13,terminalAltitude:4.5,terminalAt:72,cruiseSpeed:21,terminalSpeed:27,turnRate:18,damage:28},
 'P-700':{cruiseAltitude:17,terminalAltitude:6,terminalAt:92,cruiseSpeed:24,terminalSpeed:31,turnRate:14,damage:38},
 'Kh-22':{cruiseAltitude:58,terminalAltitude:8,terminalAt:145,cruiseSpeed:30,terminalSpeed:38,turnRate:9,damage:46}
} as const;
function defensiveShotRequirement(missile:Missile,quality:number){return missile.kind==='Kh-22'||missile.phase==='terminal'||quality<.42?2:1;}
function missileThreatScore(missile:Missile,quality:number){const range=missile.mesh.position.distanceTo(defender.position),tti=range/Math.max(1,missile.velocity.length());return Math.max(0,120-tti)*2+(missile.phase==='terminal'?90:missile.phase==='midcourse'?35:0)+(missile.kind==='Kh-22'?45:missile.kind==='P-700'?18:0)+quality*12;}
function createEnemyMissile(kind:EnemyType){
 const g=new THREE.Group(),isGranite=kind==='P-700',isKh22=kind==='Kh-22',length=isKh22?11:isGranite?9.6:8.8,radius=isGranite?1.05:isKh22?.72:.86;
 const skin=new THREE.MeshStandardMaterial({color:isKh22?0xb7b9ad:isGranite?0xa9553d:0xb96245,metalness:.58,roughness:.4});
 const dark=new THREE.MeshStandardMaterial({color:0x242b2c,metalness:.55,roughness:.5});
 const body=new THREE.Mesh(new THREE.CylinderGeometry(radius*.9,radius,length,14),skin);body.rotation.x=Math.PI/2;g.add(body);
 const nose=new THREE.Mesh(new THREE.ConeGeometry(radius*.9,isKh22?2.8:2.1,14),skin);nose.rotation.x=-Math.PI/2;nose.position.z=-length*.5-1;g.add(nose);
 const tail=new THREE.Mesh(new THREE.CylinderGeometry(radius*.72,radius,1.6,14),dark);tail.rotation.x=Math.PI/2;tail.position.z=length*.5+.6;g.add(tail);
 const wingSpan=isKh22?4.8:isGranite?5.6:5.1,wingChord=isKh22?3.4:2.8;
 const wingShape=new THREE.Shape();wingShape.moveTo(0,0);wingShape.lineTo(wingSpan,wingChord*.7);wingShape.lineTo(wingSpan*.78,-wingChord*.45);wingShape.lineTo(0,-wingChord*.7);wingShape.closePath();
 for(const side of [-1,1]){const wing=new THREE.Mesh(new THREE.ShapeGeometry(wingShape),skin);wing.rotation.x=Math.PI/2;wing.rotation.z=side<0?Math.PI:0;wing.position.set(side*radius*.45,0,isKh22?.5:1);g.add(wing);}
 for(const side of [-1,1]){const fin=new THREE.Mesh(new THREE.BoxGeometry(isKh22?.13:.18,isKh22?2.2:1.7,2.5),dark);fin.position.set(side*(radius+.35),0,length*.35);fin.rotation.z=side*.18;g.add(fin);}
 if(isGranite){const intake=new THREE.Mesh(new THREE.CylinderGeometry(.42,.58,3,10),dark);intake.rotation.x=Math.PI/2;intake.position.set(0,-radius*.85,1);g.add(intake);}
 const exhaust=new THREE.Mesh(new THREE.ConeGeometry(radius*.5,isKh22?6:5,12,1,true),new THREE.MeshBasicMaterial({color:isKh22?0xffd37a:0xff7138,transparent:true,opacity:.72,blending:THREE.AdditiveBlending,depthWrite:false}));exhaust.rotation.x=-Math.PI/2;exhaust.position.z=length*.5+3.4;g.add(exhaust);
 const hotCore=new THREE.Mesh(new THREE.ConeGeometry(radius*.18,3.2,10,1,true),new THREE.MeshBasicMaterial({color:0xfff2c0,transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false}));hotCore.rotation.x=-Math.PI/2;hotCore.position.z=length*.5+2.4;g.add(hotCore);
 const glow=new THREE.PointLight(0xff642d,isKh22?7:5,isKh22?35:28);glow.position.z=length*.5+2;g.add(glow);g.userData.exhaust=exhaust;g.userData.hotCore=hotCore;return g;
}
function addMissile(pos:THREE.Vector3,kind:EnemyType='P-500',launchAt=0){const profile=kind==='P-700'?{speed:1.12,rcs:2300,scale:1.05}:{speed:kind==='Kh-22'?1.35:1,rcs:kind==='Kh-22'?3100:1800,scale:kind==='Kh-22'?.92:.96},ordinal=missiles.length,aimOffset=new THREE.Vector3(Math.sin((ordinal+1)*2.399)*13,0,Math.cos((ordinal+1)*1.73)*3.5);const g=createEnemyMissile(kind);g.position.copy(pos);g.scale.setScalar(profile.scale);g.visible=launchAt<=0;const selection=new THREE.Mesh(new THREE.TorusGeometry(kind==='P-700'?4.8:4.2,.12,8,32),new THREE.MeshBasicMaterial({color:0xffd45a,transparent:true,opacity:.9}));selection.rotation.x=Math.PI/2;selection.visible=false;g.add(selection);g.userData.selection=selection;const history=[pos.clone()];const path=new THREE.Line(new THREE.BufferGeometry().setFromPoints(history),new THREE.LineBasicMaterial({color:kind==='Kh-22'?0xffb05a:0xe25a43,transparent:true,opacity:.34,blending:THREE.AdditiveBlending}));path.visible=g.visible;scene.add(g,path);missiles.push({mesh:g,velocity:new THREE.Vector3(0,0,20*profile.speed),phase:'inbound',age:0,history,path,kind,speedFactor:profile.speed,rcs:profile.rcs,launchAt,aimOffset});}
function launchInterceptor(target:Missile){const g=new THREE.Group();const sm2=selectedWeapon==='SM-2MR';const body=new THREE.Mesh(new THREE.CylinderGeometry(sm2?.42:.55,sm2?.6:.8,sm2?5.6:7,10),new THREE.MeshStandardMaterial({color:sm2?0xf0eee4:0xd9d7c7,metalness:.7,roughness:.3}));body.rotation.x=Math.PI/2;g.add(body);const flame=new THREE.PointLight(sm2?0x8fdfff:0x6cdcff,7,28);flame.position.z=4;g.add(flame);const trail=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-14)]),new THREE.LineBasicMaterial({color:0x8fe9ff,transparent:true,opacity:.8}));g.add(trail);const seeker=new THREE.Mesh(new THREE.ConeGeometry(sm2?5:7,sm2?22:30,20,1,true),new THREE.MeshBasicMaterial({color:0x65e4ff,transparent:true,opacity:.08,depthWrite:false,side:THREE.DoubleSide}));seeker.rotation.x=-Math.PI/2;seeker.position.z=-15;seeker.visible=false;g.add(seeker);g.userData.seeker=seeker;g.position.copy(defender.position).add(new THREE.Vector3(-10,10,0));const illuminationBeam=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineBasicMaterial({color:0xffd66b,transparent:true,opacity:.42,blending:THREE.AdditiveBlending,depthWrite:false}));illuminationBeam.visible=false;const history=[g.position.clone()],guidancePath=new THREE.Line(new THREE.BufferGeometry().setFromPoints(history),new THREE.LineBasicMaterial({color:sm2?0x9deaff:0x71d6ff,transparent:true,opacity:.5,blending:THREE.AdditiveBlending})),track=combatPicture.tracks.get(missiles.indexOf(target)+1),salvoLeader=interceptors.find(i=>i.mesh.visible&&i.target===target),commandPoint=(salvoLeader?.commandPoint??track?.position??target.mesh.position).clone(),commandVelocity=(salvoLeader?.commandVelocity??track?.velocity??target.velocity).clone(),nextDatalink=salvoLeader?.nextDatalink??elapsed+.35;scene.add(g,illuminationBeam,guidancePath);const initialDirection=commandPoint.clone().sub(g.position).setY(34).normalize();interceptors.push({mesh:g,target,age:0,weapon:selectedWeapon,velocity:initialDirection.multiplyScalar(9),distanceTraveled:0,history,guidancePath,commandPoint,commandVelocity,nextDatalink,datalinkValid:salvoLeader?.datalinkValid??!!track,illuminated:false,illuminationBeam});log(`${selectedWeapon} LAUNCH / BOOST CLIMB`);}
function createExplosion(position:THREE.Vector3){const core=new THREE.Mesh(new THREE.IcosahedronGeometry(2.2,2),new THREE.MeshBasicMaterial({color:0xffc45e,transparent:true,opacity:.92,depthWrite:false,blending:THREE.AdditiveBlending}));core.position.copy(position);const ring=new THREE.Mesh(new THREE.TorusGeometry(3.2,.22,10,48),new THREE.MeshBasicMaterial({color:0xff7138,transparent:true,opacity:.78,depthWrite:false,blending:THREE.AdditiveBlending}));ring.position.copy(position);ring.quaternion.copy(camera.quaternion);const light=new THREE.PointLight(0xff6a22,18,95);light.position.copy(position);scene.add(core,ring,light);explosions.push({core,ring,light,age:0});}
function flashCombat(kind:'intercept'|'impact'){combatFlash.className='combat-flash';void combatFlash.offsetWidth;combatFlash.classList.add(kind);}
function destroyMissileVisual(missile:Missile,effect:'intercept'|'impact'){if(!explodedTargets.has(missile)){explodedTargets.add(missile);createExplosion(missile.mesh.position.clone());}flashCombat(effect);}
function ciwsTracer(target:THREE.Vector3){const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([defender.position.clone().add(new THREE.Vector3(15,9,0)),target.clone()]),new THREE.LineBasicMaterial({color:0xffef9a,transparent:true,opacity:.9}));scene.add(line);setTimeout(()=>{scene.remove(line);line.geometry.dispose();(line.material as THREE.Material).dispose();},110);}
addMissile(new THREE.Vector3(-85,18,-210)); addMissile(new THREE.Vector3(0,28,-240)); addMissile(new THREE.Vector3(80,14,-220));
let running=true,elapsed=0,simAccumulator=0,last=performance.now(),ammo=6,sm2Ammo=12,selectedWeapon:'RIM-67'|'SM-2MR'='RIM-67',autoFire=true,radarEnabled=true,timeScale=1,selectedTargetId=1,hullIntegrity=100,ciwsEnabled=true,ciwsRounds=1200,lastCiwsShot=-10,nextSamLaunch=0,leakers=0,missionEnded=false,maxSamChannels=3,maxIlluminators=2; let dragging=false,px=0,py=0,az=0.65,el=0.48,dist=210,cinematic=false,waveFrame=0;
const phaseEl=document.querySelector('#phase')!, clockEl=document.querySelector('#clock')!, targetState=document.querySelector('#targetState')!, feed=document.querySelector('#feed')!, ammoEl=document.querySelector('#ammo')!, weaponEnvelope=document.querySelector('#weaponEnvelope')!, threatName=document.querySelector('#threatName')!, threatRange=document.querySelector('#threatRange')!, threatAltitude=document.querySelector('#threatAltitude')!, trackQuality=document.querySelector('#trackQuality')!, threatTti=document.querySelector('#threatTti')!, qualityFill=document.querySelector('#qualityFill') as HTMLElement;
const targetMarker=document.querySelector('#targetMarker') as HTMLElement,targetMarkerLabel=document.querySelector('#targetMarkerLabel') as HTMLElement,combatFlash=document.querySelector('#combatFlash') as HTMLElement;
const controls=document.createElement('div');controls.className='combat-controls';controls.style.cssText='position:fixed;left:34px;bottom:150px;display:flex;gap:8px;z-index:8';document.body.appendChild(controls);
const resultPanel=document.createElement('div');resultPanel.className='result-panel';resultPanel.style.cssText='display:none;position:fixed;inset:0;margin:auto;width:360px;height:210px;background:#071923ee;border:1px solid #4ac0b8;color:#d5edf0;z-index:20;padding:28px;text-align:center;font:12px Arial;letter-spacing:1px';document.body.appendChild(resultPanel);
let placementMode:false|'enemy'|'ship'=false;
const sandbox=document.createElement('div');sandbox.style.cssText='position:fixed;inset:0;margin:auto;width:470px;height:430px;background:#071923f5;border:1px solid #4ac0b8;color:#d5edf0;z-index:30;padding:28px;font:12px Arial;letter-spacing:1px';sandbox.innerHTML=`<div style="font-size:20px;letter-spacing:3px;margin-bottom:22px">SANDBOX SCENARIO</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px"><label>MISSILE TYPE<select id="sbType"><option>P-500</option><option>P-700</option><option>Kh-22</option></select></label><label>MISSILE COUNT<input id="sbCount" type="number" min="1" max="24" value="6"></label><label>LAUNCH INTERVAL (s)<input id="sbInterval" type="number" min="0" max="20" step="0.5" value="1"></label><label>ALTITUDE<input id="sbAltitude" type="number" min="5" max="80" value="18"></label><label>CENTER X<input id="sbX" type="number" min="-400" max="400" value="0"></label><label>CENTER Z<input id="sbZ" type="number" min="-500" max="-80" value="-260"></label><label>FORMATION SPREAD<input id="sbSpread" type="number" min="0" max="300" value="150"></label><label>START WEAPON<select id="sbWeapon"><option>RIM-67</option><option>SM-2MR</option></select></label></div><button id="sbStart" style="margin-top:28px;width:100%;border:1px solid #4ac0b8;background:#0b2830;color:#bce7e5;padding:11px;cursor:pointer">START EXERCISE</button>`;sandbox.querySelectorAll('input,select').forEach((e:any)=>e.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px');document.body.appendChild(sandbox);running=false;missiles.forEach(m=>{m.mesh.visible=false;m.path.visible=false;});
sandbox.className='sandbox-panel';
function numberInput(id:string){return Number((sandbox.querySelector(id) as HTMLInputElement).value);}
const pickPlacement=document.createElement('button');pickPlacement.textContent='PICK FORMATION CENTER ON RADAR';pickPlacement.style.cssText='margin-top:12px;width:100%;border:1px solid #547d82;background:#0a2229;color:#9fd3d1;padding:8px;cursor:pointer';sandbox.insertBefore(pickPlacement,sandbox.querySelector('#sbStart'));pickPlacement.onclick=()=>{placementMode='enemy';pickPlacement.textContent='CLICK TACTICAL RADAR...';};
const pickShip=document.createElement('button');pickShip.textContent='PICK USS LONG BEACH ON RADAR';pickShip.style.cssText=pickPlacement.style.cssText;sandbox.insertBefore(pickShip,sandbox.querySelector('#sbStart'));pickShip.onclick=()=>{placementMode='ship';pickShip.textContent='CLICK TACTICAL RADAR...';};
const patternWrap=document.createElement('label');patternWrap.innerHTML='LAUNCH PATTERN<select id="sbPattern"><option value="RIPPLE">RIPPLE / ONE BY ONE</option><option value="SALVO">SALVO / SIMULTANEOUS</option><option value="WAVES">WAVES / GROUPS OF FOUR</option></select>';patternWrap.style.cssText='display:block;margin-top:12px';sandbox.insertBefore(patternWrap,pickPlacement);const patternSelect=patternWrap.querySelector('select') as HTMLSelectElement;patternSelect.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';
patternSelect.remove(2);patternSelect.onchange=()=>{if(patternSelect.value==='SALVO')(sandbox.querySelector('#sbInterval') as HTMLInputElement).value='0';};
sandbox.style.height='570px';
const sandboxGrid=sandbox.querySelector('div[style*="grid"]')!;for(const [label,id,value] of [['SHIP X','sbShipX','0'],['SHIP Z','sbShipZ','40']]){const field=document.createElement('label');field.textContent=label;const input=document.createElement('input');input.id=id;input.type='number';input.value=value;input.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';field.appendChild(input);sandboxGrid.appendChild(field);}sandbox.style.height='640px';
for(const [label,id,value,max] of [['RIM-67 MAGAZINE','sbRim','6','48'],['SM-2MR MAGAZINE','sbSm2','12','96'],['CIWS ROUNDS','sbCiws','1200','6000']]){const field=document.createElement('label');field.textContent=label;const input=document.createElement('input');input.id=id;input.type='number';input.min='0';input.max=max;input.value=value;input.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';field.appendChild(input);sandboxGrid.appendChild(field);}sandbox.style.height='760px';
const channelField=document.createElement('label');channelField.textContent='SAM FIRE CHANNELS';const channelInput=document.createElement('input');channelInput.id='sbChannels';channelInput.type='number';channelInput.min='1';channelInput.max='8';channelInput.value='3';channelInput.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';channelField.appendChild(channelInput);sandboxGrid.appendChild(channelField);
const illuminatorField=document.createElement('label');illuminatorField.textContent='TERMINAL ILLUMINATORS';const illuminatorInput=channelInput.cloneNode() as HTMLInputElement;illuminatorInput.id='sbIlluminators';illuminatorInput.max='4';illuminatorInput.value='2';illuminatorField.appendChild(illuminatorInput);sandboxGrid.appendChild(illuminatorField);
const wave2Type=document.createElement('label');wave2Type.innerHTML='SECOND WAVE TYPE<select id="sbType2"><option value="NONE">NONE</option><option>P-500</option><option>P-700</option><option>Kh-22</option></select>';const wave2Select=wave2Type.querySelector('select') as HTMLSelectElement;wave2Select.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';sandboxGrid.appendChild(wave2Type);for(const [label,id,value,max] of [['SECOND WAVE COUNT','sbCount2','4','12'],['SECOND WAVE DELAY','sbDelay2','10','60']]){const field=document.createElement('label');field.textContent=label;const input=document.createElement('input');input.id=id;input.type='number';input.min='0';input.max=max;input.value=value;input.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';field.appendChild(input);sandboxGrid.appendChild(field);}sandbox.style.height='850px';
const presets=document.createElement('div');presets.style.cssText='display:flex;gap:7px;margin-top:12px';sandbox.insertBefore(presets,patternWrap);function presetButton(text:string,kind:EnemyType,count:number,interval:number,altitude:number,spread:number){const b=document.createElement('button');b.textContent=text;b.style.cssText='flex:1;border:1px solid #3d6f73;background:#09232a;color:#9fd3d1;padding:7px;font-size:9px;cursor:pointer';b.onclick=()=>{(sandbox.querySelector('#sbType') as HTMLSelectElement).value=kind;(sandbox.querySelector('#sbCount') as HTMLInputElement).value=String(count);(sandbox.querySelector('#sbInterval') as HTMLInputElement).value=String(interval);(sandbox.querySelector('#sbAltitude') as HTMLInputElement).value=String(altitude);(sandbox.querySelector('#sbSpread') as HTMLInputElement).value=String(spread);};presets.appendChild(b);}presetButton('SEA SKIMMER','P-500',6,1.5,10,140);presetButton('SATURATION','P-700',16,0,16,260);presetButton('HIGH SPEED','Kh-22',8,2,55,190);
radarCanvas.addEventListener('pointerdown',e=>{if(!placementMode)return;e.stopPropagation();const rect=radarCanvas.getBoundingClientRect(),px=(e.clientX-rect.left)/rect.width*radarCanvas.width,py=(e.clientY-rect.top)/rect.height*radarCanvas.height,x=Math.round((px-radarCanvas.width/2)/.45),z=Math.round((py-radarCanvas.height/2)/.32);if(placementMode==='ship'){(sandbox.querySelector('#sbShipX') as HTMLInputElement).value=String(x);(sandbox.querySelector('#sbShipZ') as HTMLInputElement).value=String(z);pickShip.textContent=`SHIP SET / X ${x} / Z ${z}`;}else{(sandbox.querySelector('#sbX') as HTMLInputElement).value=String(x);(sandbox.querySelector('#sbZ') as HTMLInputElement).value=String(z);pickPlacement.textContent=`CENTER SET / X ${x} / Z ${z}`;}placementMode=false;});
(sandbox.querySelector('#sbStart') as HTMLButtonElement).onclick=()=>{missiles.forEach(m=>{scene.remove(m.mesh,m.path);m.path.geometry.dispose();});missiles.length=0;interceptors.forEach(i=>scene.remove(i.mesh));interceptors.length=0;combatPicture.tracks.clear();explodedTargets.clear();explosions.forEach(e=>scene.remove(e.core,e.ring,e.light));explosions.length=0;elapsed=0;last=performance.now();ammo=6;sm2Ammo=12;hullIntegrity=100;ciwsRounds=1200;missionEnded=false;selectedWeapon=(sandbox.querySelector('#sbWeapon') as HTMLSelectElement).value as 'RIM-67'|'SM-2MR';const kind=(sandbox.querySelector('#sbType') as HTMLSelectElement).value as EnemyType,count=Math.max(1,Math.min(24,numberInput('#sbCount'))),interval=Math.max(0,numberInput('#sbInterval')),altitude=numberInput('#sbAltitude'),cx=numberInput('#sbX'),cz=numberInput('#sbZ'),spread=numberInput('#sbSpread');for(let i=0;i<count;i++){const offset=count===1?0:(i/(count-1)-.5)*spread;addMissile(new THREE.Vector3(cx+offset,altitude+Math.sin(i)*5,cz-Math.abs(offset)*.12),kind,i*interval);}selectedTargetId=1;missiles[0].mesh.userData.selection.visible=true;weaponButton.textContent=`WEAPON: ${selectedWeapon}`;ammoEl.textContent=`RIM ${ammo} / SM2 ${sm2Ammo}`;sandbox.style.display='none';running=true;log(`SANDBOX START / ${count} x ${kind} / ${interval}s INTERVAL`);};
(sandbox.querySelector('#sbStart') as HTMLButtonElement).addEventListener('pointerdown',()=>{interceptors.forEach(i=>{i.illuminationBeam.visible=false;scene.remove(i.illuminationBeam,i.guidancePath);i.guidancePath.geometry.dispose();});explosions.forEach(e=>scene.remove(e.core,e.ring,e.light));simAccumulator=0;nextSamLaunch=0;leakers=0;const x=numberInput('#sbShipX'),z=numberInput('#sbShipZ');defender.position.set(x,0,z);wake.position.set(x-42,.22,z);},true);
(sandbox.querySelector('#sbStart') as HTMLButtonElement).addEventListener('click',()=>setTimeout(()=>{ammo=Math.max(0,Math.min(48,numberInput('#sbRim')));sm2Ammo=Math.max(0,Math.min(96,numberInput('#sbSm2')));ciwsRounds=Math.max(0,Math.min(6000,numberInput('#sbCiws')));maxSamChannels=Math.max(1,Math.min(8,numberInput('#sbChannels')));maxIlluminators=Math.max(1,Math.min(4,numberInput('#sbIlluminators')));ammoEl.textContent=`RIM ${ammo} / SM2 ${sm2Ammo}`;},0));
(sandbox.querySelector('#sbStart') as HTMLButtonElement).addEventListener('click',()=>setTimeout(()=>{const kind2=wave2Select.value as EnemyType|'NONE';if(kind2==='NONE')return;const count=Math.max(0,Math.min(12,numberInput('#sbCount2'))),delay=Math.max(0,numberInput('#sbDelay2')),cx=numberInput('#sbX'),cz=numberInput('#sbZ'),altitude=numberInput('#sbAltitude'),spread=numberInput('#sbSpread');for(let i=0;i<count;i++){const offset=count===1?0:(i/(count-1)-.5)*spread*.75;addMissile(new THREE.Vector3(cx+offset,kind2==='Kh-22'?Math.max(45,altitude):altitude,cz-50),kind2,delay+i*.6);}log(`SECOND WAVE / ${count} x ${kind2} / T+${delay}s`);},0));
function finishMission(victory:boolean){if(missionEnded)return;missionEnded=true;running=false;const score=Math.max(0,Math.round(hullIntegrity*10+ammo*150+sm2Ammo*100+ciwsRounds/10-Math.max(0,elapsed-20)*5)),outcome=victory?(leakers===0?'AIRSPACE SECURED':`RAID SURVIVED / ${leakers} LEAKER${leakers===1?'':'S'}`):'USS LONG BEACH DISABLED';resultPanel.innerHTML=`<div style="font-size:20px;letter-spacing:3px;margin-bottom:18px">${outcome}</div><div>MISSION SCORE ${score}</div><div style="margin-top:10px;color:#78c9c4">HULL ${hullIntegrity}% / RIM ${ammo} / SM2 ${sm2Ammo} / CIWS ${ciwsRounds}</div><button id="restartMission" style="margin-top:25px;border:1px solid #4ac0b8;background:#0b2830;color:#bce7e5;padding:9px 18px;cursor:pointer">RESTART EXERCISE</button>`;resultPanel.style.display='block';resultPanel.querySelector('button')!.addEventListener('click',()=>location.reload());}
function controlButton(label:string,action:()=>void){const b=document.createElement('button');b.textContent=label;b.style.cssText='border:1px solid #438e91;background:#071923dd;color:#a8dddd;padding:8px 11px;font:10px Arial;letter-spacing:1px;cursor:pointer';b.onclick=action;controls.appendChild(b);return b;}
const autoButton=controlButton('AUTO FIRE: ON',()=>{autoFire=!autoFire;autoButton.textContent=`AUTO FIRE: ${autoFire?'ON':'OFF'}`;});
const radarButton=controlButton('RADAR: ACTIVE',()=>{radarEnabled=!radarEnabled;radarButton.textContent=`RADAR: ${radarEnabled?'ACTIVE':'SILENT'}`;log(radarEnabled?'RADAR EMISSION RESTORED':'EMCON / RADAR SILENT');});
const ciwsButton=controlButton('CIWS: AUTO',()=>{ciwsEnabled=!ciwsEnabled;ciwsButton.textContent=`CIWS: ${ciwsEnabled?'AUTO':'HOLD'}`;});
const weaponButton=controlButton('WEAPON: RIM-67',()=>{selectedWeapon=selectedWeapon==='RIM-67'?'SM-2MR':'RIM-67';weaponButton.textContent=`WEAPON: ${selectedWeapon}`;ammoEl.textContent=`RIM ${ammo} / SM2 ${sm2Ammo}`;});
const targetButton=controlButton('TARGET: 1',()=>{const live=missiles.map((m,i)=>({m,id:i+1})).filter(x=>x.m.phase!=='destroyed');if(!live.length)return;const current=live.findIndex(x=>x.id===selectedTargetId);selectedTargetId=live[(current+1)%live.length].id;targetButton.textContent=`TARGET: ${selectedTargetId}`;missiles.forEach((m,i)=>m.mesh.userData.selection.visible=i+1===selectedTargetId&&m.phase!=='destroyed');});
const fireButton=controlButton('LAUNCH SAM',()=>{
 const active=interceptors.filter(i=>i.mesh.visible).length,track=combatPicture.tracks.get(selectedTargetId),target=missiles[selectedTargetId-1],available=selectedWeapon==='RIM-67'?ammo:sm2Ammo,profile=weaponProfiles[selectedWeapon];
 if(!running){log('LAUNCH INHIBIT / SIMULATION PAUSED');return;}if(elapsed<nextSamLaunch){log('LAUNCH INHIBIT / MK 10 LAUNCHER CYCLING');return;}if(active>=maxSamChannels){log(`LAUNCH INHIBIT / CHANNELS ${active}/${maxSamChannels}`);return;}if(available<=0){log('LAUNCH INHIBIT / MAGAZINE EMPTY');return;}if(!target||target.phase==='destroyed'){log('LAUNCH INHIBIT / TARGET INVALID');return;}if(!track){log(`LAUNCH INHIBIT / TRACK ${selectedTargetId} LOST`);return;}if(track.quality<.32||track.age>2.2){log(`LAUNCH INHIBIT / TRACK QUALITY ${Math.round(track.quality*100)}%`);return;}const assigned=interceptors.filter(i=>i.mesh.visible&&i.target===target).length,required=defensiveShotRequirement(target,track.quality);if(assigned>=required){log(`LAUNCH INHIBIT / SALVO COMPLETE ${assigned}/${required}`);return;}
 const range=target.mesh.position.distanceTo(defender.position);if(range<profile.minRange||range>profile.maxRange){log(`LAUNCH INHIBIT / ${selectedWeapon} ENVELOPE ${(profile.minRange/10).toFixed(1)}-${(profile.maxRange/10).toFixed(1)} km`);return;}
 launchInterceptor(target);nextSamLaunch=elapsed+.12;if(selectedWeapon==='RIM-67')ammo--;else sm2Ammo--;ammoEl.textContent=`RIM ${ammo} / SM2 ${sm2Ammo}`;
});
const speedButton=controlButton('TIME: 1X',()=>{timeScale=timeScale===1?2:timeScale===2?4:1;speedButton.textContent=`TIME: ${timeScale}X`;});
controlButton('SCENARIO SETUP',()=>{running=false;sandbox.style.display='block';});
missiles[0].mesh.userData.selection.visible=true;
function log(s:string){const d=document.createElement('div'); d.textContent=s; feed.prepend(d); while(feed.children.length>5)feed.lastChild?.remove();}
function updateShipStatus(){const active=interceptors.filter(i=>i.mesh.visible).length,illuminated=interceptors.filter(i=>i.mesh.visible&&i.illuminated).length;document.querySelector('#shipState')!.textContent=`HULL ${hullIntegrity}% / CH ${active}/${maxSamChannels} / ILL ${illuminated}/${maxIlluminators}`;}
log('16:42:08  NTU combat system initialized'); log('16:42:11  SURFACE SEARCH RADAR — CONTACTS ACQUIRED');
function updateCamera(){if(cinematic)az+=.0018;const focus=dist<140?defender.position.clone().add(new THREE.Vector3(0,9,0)):new THREE.Vector3(0,8,-40);const x=Math.cos(el)*Math.sin(az)*dist,z=Math.cos(el)*Math.cos(az)*dist;camera.position.set(focus.x+x,focus.y+Math.sin(el)*dist,focus.z+z);camera.lookAt(focus);}
setInterval(()=>{if(defender.userData.radar){const t=performance.now()*.001;defender.userData.radar.rotation.y+=.04;defender.userData.fireControl.rotation.y=Math.sin(t)*.3;defender.userData.launcher.rotation.y=Math.sin(t*.75)*.12;defender.userData.launcher.userData.arms?.forEach((arm:THREE.Group,index:number)=>arm.rotation.z=.12+Math.sin(t*.9+index*.4)*.08);}},50);
function updateCiws(){if(!ciwsEnabled||ciwsRounds<=0||elapsed-lastCiwsShot<.55)return;const candidates=missiles.filter(m=>m.phase!=='destroyed'&&m.mesh.position.distanceTo(defender.position)<34).sort((a,b)=>a.mesh.position.distanceTo(defender.position)-b.mesh.position.distanceTo(defender.position));const target=candidates[0];if(!target)return;lastCiwsShot=elapsed;ciwsRounds=Math.max(0,ciwsRounds-60);ciwsTracer(target.mesh.position);const saturation=Math.max(1,candidates.length),pk=Math.max(.16,.52/saturation),roll=Math.abs(Math.sin(elapsed*31.7+ciwsRounds*.013));if(roll<pk){target.phase='destroyed';target.mesh.visible=false;destroyMissileVisual(target,'intercept');log(`CIWS KILL / ${ciwsRounds} ROUNDS`);}else log(`CIWS BURST / ${ciwsRounds} ROUNDS`);}
setInterval(()=>interceptors.forEach(i=>{if(i.mesh.userData.seeker)i.mesh.userData.seeker.visible=i.weapon==='RIM-67'&&i.mesh.visible&&i.target.phase!=='destroyed'&&i.mesh.position.distanceTo(i.target.mesh.position)<weaponProfiles[i.weapon].terminalRange;}),50);
setInterval(()=>{const live=missiles.filter(m=>m.phase!=='destroyed').length,engagedTargets=new Set(interceptors.filter(i=>i.mesh.visible).map(i=>i.target)).size;targetState.textContent=live>0?`${live} THREATS / ${engagedTargets} ENGAGED`:'AIRSPACE CLEAR';},120);
setInterval(()=>{if(missiles[selectedTargetId-1]?.phase==='destroyed'){const next=missiles.findIndex(m=>m.phase!=='destroyed');if(next>=0){selectedTargetId=next+1;targetButton.textContent=`TARGET: ${selectedTargetId}`;}}missiles.forEach((m,i)=>m.mesh.userData.selection.visible=i+1===selectedTargetId&&m.phase!=='destroyed');},120);
setInterval(()=>{explosions.forEach(e=>{e.age+=.05;e.core.scale.setScalar(1+e.age*3.4);e.ring.scale.setScalar(1+e.age*5.8);e.ring.quaternion.copy(camera.quaternion);(e.core.material as THREE.MeshBasicMaterial).opacity=Math.max(0,.92-e.age/1.45);(e.ring.material as THREE.MeshBasicMaterial).opacity=Math.max(0,.78-e.age/1.15);e.light.intensity=Math.max(0,18-e.age*14);if(e.age>1.5){e.core.visible=false;e.ring.visible=false;e.light.visible=false;}});},50);
setInterval(()=>{if(!radarCtx)return; const cx=radarCanvas.width/2,cy=radarCanvas.height/2; missiles.forEach((m,i)=>{if(m.phase==='destroyed')return; const x=cx+(m.mesh.position.x-defender.position.x)*.45,y=cy+(m.mesh.position.z-defender.position.z)*.32,track=combatPicture.tracks.get(i+1); radarCtx.strokeStyle=track?(track.quality>.7?'#ff5148':track.quality>.25?'#ffb347':'#bd78ff'):'#526b70'; radarCtx.globalAlpha=.9; radarCtx.beginPath();radarCtx.arc(x,y,7,0,Math.PI*2);radarCtx.stroke(); if(track&&lastTrackClasses.get(i+1)!==track.classification){lastTrackClasses.set(i+1,track.classification);log(`TRACK ${i+1} ${track.classification.toUpperCase()} · UNCERTAINTY ${(track.uncertainty/1000).toFixed(1)} km`);}}); radarCtx.globalAlpha=1;},120);
setInterval(()=>{if(!radarCtx)return; const w=radarCanvas.width,h=radarCanvas.height,cx=w/2,cy=h/2; radarCtx.clearRect(0,0,w,h); radarCtx.fillStyle='#061923'; radarCtx.fillRect(0,0,w,h); radarCtx.strokeStyle='#2d7f83'; radarCtx.globalAlpha=.65; for(const r of [35,70,105]){radarCtx.beginPath();radarCtx.arc(cx,cy,r,0,Math.PI*2);radarCtx.stroke();} radarCtx.beginPath();radarCtx.moveTo(cx,cy);radarCtx.lineTo(cx+Math.cos(elapsed*.8)*110,cy+Math.sin(elapsed*.8)*110);radarCtx.strokeStyle='#78e1c8';radarCtx.stroke(); radarCtx.globalAlpha=1; radarCtx.fillStyle='#78e1c8';radarCtx.fillRect(cx-3,cy-3,6,6); missiles.forEach(m=>{if(m.phase==='destroyed')return; const x=cx+(m.mesh.position.x-defender.position.x)*.45,y=cy+(m.mesh.position.z-defender.position.z)*.32; radarCtx.fillStyle='#ff6548';radarCtx.beginPath();radarCtx.arc(x,y,4,0,Math.PI*2);radarCtx.fill();}); interceptors.forEach(i=>{if(!i.mesh.visible)return; const x=cx+(i.mesh.position.x-defender.position.x)*.45,y=cy+(i.mesh.position.z-defender.position.z)*.32; radarCtx.fillStyle='#a4ecff';radarCtx.beginPath();radarCtx.arc(x,y,3,0,Math.PI*2);radarCtx.fill();});},100);
function updateCombat(dt:number){
 updateCiws();
 combatPicture.update(elapsed,dt,radarEnabled?missiles.map((m,i)=>({m,i})).filter(x=>elapsed>=x.m.launchAt&&x.m.phase!=='destroyed').map(x=>({id:x.i+1,position:x.m.mesh.position,velocity:x.m.velocity,altitude:x.m.mesh.position.y,rcs:x.m.rcs})):[],1,defender.position);
 const activeInterceptors=interceptors.filter(i=>i.mesh.visible),active=activeInterceptors.length,assignments=new Map<Missile,number>();activeInterceptors.forEach(i=>assignments.set(i.target,(assignments.get(i.target)??0)+1));const best=[...combatPicture.tracks.values()].filter(t=>{const missile=missiles[t.id-1];return missile&&missile.phase!=='destroyed'&&t.quality>=.24&&t.age<2.2&&(assignments.get(missile)??0)<defensiveShotRequirement(missile,t.quality);}).sort((a,b)=>missileThreatScore(missiles[b.id-1],b.quality)-missileThreatScore(missiles[a.id-1],a.quality))[0];
 const terminalSm2=activeInterceptors.filter(i=>i.weapon==='SM-2MR'&&i.target.phase!=='destroyed'&&i.mesh.position.distanceTo(i.target.mesh.position)<weaponProfiles[i.weapon].terminalRange).sort((a,b)=>a.mesh.position.distanceTo(a.target.mesh.position)-b.mesh.position.distanceTo(b.target.mesh.position));
 const illuminated=new Set(terminalSm2.slice(0,maxIlluminators));
 activeInterceptors.forEach(i=>{i.illuminated=illuminated.has(i);i.illuminationBeam.visible=i.illuminated;if(i.illuminated){i.illuminationBeam.geometry.dispose();i.illuminationBeam.geometry=new THREE.BufferGeometry().setFromPoints([defender.position.clone().add(new THREE.Vector3(8,13,0)),i.target.mesh.position.clone()]);}});
 interceptors.filter(i=>!i.mesh.visible).forEach(i=>i.illuminationBeam.visible=false);
 updateShipStatus();
 const selected=missiles[selectedTargetId-1],selectedTrack=combatPicture.tracks.get(selectedTargetId);if(selected&&selected.phase!=='destroyed'){const range=selected.mesh.position.distanceTo(defender.position),profile=weaponProfiles[selectedWeapon],inRange=range>=profile.minRange&&range<=profile.maxRange;threatName.textContent=`TRACK ${String(selectedTargetId).padStart(2,'0')} / ${selectedTrack?.classification==='classified'?selected.kind:selectedTrack?.classification.toUpperCase()??'PENDING ID'}`;threatRange.textContent=`${(range/10).toFixed(1)} km`;threatAltitude.textContent=`${Math.round(selected.mesh.position.y*50)} m`;trackQuality.textContent=selectedTrack?`${Math.round(selectedTrack.quality*100)}% ${selectedTrack.classification.toUpperCase()}`:'NO DATA';threatTti.textContent=`${Math.max(0,Math.round(range/Math.max(1,selected.velocity.length())))} s`;qualityFill.style.width=`${Math.round((selectedTrack?.quality??0)*100)}%`;weaponEnvelope.textContent=`${selectedWeapon} / ${inRange?'IN RANGE':'OUT OF ENVELOPE'}`;weaponEnvelope.className=inRange?'in-range':'out-range';}
 if(running&&autoFire&&elapsed>2&&elapsed>=nextSamLaunch&&(ammo>0||sm2Ammo>0)&&active<maxSamChannels&&best){const target=missiles[best.id-1],range=target.mesh.position.distanceTo(defender.position),rim=weaponProfiles['RIM-67'],sm2=weaponProfiles['SM-2MR'],rimOk=ammo>0&&range>=rim.minRange&&range<=rim.maxRange,sm2Ok=sm2Ammo>0&&range>=sm2.minRange&&range<=sm2.maxRange;if(rimOk||sm2Ok){selectedWeapon=sm2Ok&&range<135?'SM-2MR':'RIM-67';launchInterceptor(target);nextSamLaunch=elapsed+.12;if(selectedWeapon==='RIM-67')ammo--;else sm2Ammo--;weaponButton.textContent=`WEAPON: ${selectedWeapon}`;ammoEl.textContent=`RIM ${ammo} / SM2 ${sm2Ammo}`;}}
 interceptors.forEach(i=>{
  if(!i.mesh.visible)return;if(i.target.phase==='destroyed'){i.mesh.visible=false;i.illuminationBeam.visible=false;return;}
  const profile=weaponProfiles[i.weapon];i.age+=dt;const range=i.mesh.position.distanceTo(i.target.mesh.position),speed=Math.max(1,i.velocity.length()),expectedInterceptorSpeed=Math.max(speed,profile.maxSpeed*.58),timeToGo=Math.min(4,range/(expectedInterceptorSpeed+i.target.velocity.length())),terminal=range<profile.terminalRange,trackId=missiles.indexOf(i.target)+1;i.commandPoint.addScaledVector(i.commandVelocity,dt);
  if(!terminal&&elapsed>=i.nextDatalink){const track=combatPicture.tracks.get(trackId);if(track&&track.age<2.2&&track.quality>.08){const delay=.2+(1-track.quality)*.85,solution=track.position.clone().addScaledVector(track.velocity,delay+timeToGo*.65);i.commandPoint.lerp(solution,.68);i.commandVelocity.lerp(track.velocity,.6);i.datalinkValid=true;i.nextDatalink=elapsed+.38+(1-track.quality)*1.05;}else{i.datalinkValid=false;i.nextDatalink=elapsed+.55;}}
  const terminalHoming=terminal&&(i.weapon==='RIM-67'||i.illuminated),aim=terminalHoming?i.target.mesh.position.clone().addScaledVector(i.target.velocity,timeToGo*.8):i.commandPoint.clone();
  if(i.age<profile.boost){const estimatedLaunchRange=Math.min(profile.maxRange,range+i.distanceTraveled),loftFactor=THREE.MathUtils.clamp((estimatedLaunchRange-profile.terminalRange)/(profile.maxRange-profile.terminalRange),0,1);aim.y=Math.max(aim.y,20+loftFactor*28);}else if(!terminal)aim.y+=Math.min(34,range*.16);
  const desired=aim.sub(i.mesh.position).normalize(),current=i.velocity.clone().normalize(),angle=current.angleTo(desired),turnLimit=profile.turnRate*dt*(terminal?2.2:i.age<profile.boost?.62:1),blend=angle>0?Math.min(1,turnLimit/angle):1,direction=current.lerp(desired,blend).normalize(),rangeFraction=Math.min(1,i.distanceTraveled/profile.maxRange),commandedSpeed=profile.maxSpeed*(1-rangeFraction*.1),nextSpeed=Math.min(commandedSpeed,speed+profile.acceleration*dt),previousPosition=i.mesh.position.clone();i.velocity.copy(direction.multiplyScalar(nextSpeed));i.mesh.position.addScaledVector(i.velocity,dt);i.distanceTraveled+=nextSpeed*dt;i.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),direction);const closestPoint=new THREE.Vector3();new THREE.Line3(previousPosition,i.mesh.position).closestPointToPoint(i.target.mesh.position,true,closestPoint);const postRange=i.mesh.position.distanceTo(i.target.mesh.position),interceptDistance=Math.min(range,postRange,closestPoint.distanceTo(i.target.mesh.position));
  if(i.history[i.history.length-1].distanceTo(i.mesh.position)>2.2){i.history.push(i.mesh.position.clone());if(i.history.length>140)i.history.shift();i.guidancePath.geometry.dispose();i.guidancePath.geometry=new THREE.BufferGeometry().setFromPoints(i.history);}
  const needsIllumination=i.weapon==='SM-2MR'&&terminal; phaseEl.textContent=i.age<profile.boost?'BOOST / LOFT CLIMB':needsIllumination?(i.illuminated?'TERMINAL / SPG-55 ILLUMINATION':'TERMINAL / COASTING WITHOUT ILLUMINATION'):terminal?'TERMINAL / ACTIVE SEEKER':i.datalinkValid?'MIDCOURSE / DATALINK UPDATE':'MIDCOURSE / INERTIAL COAST';
  if(interceptDistance<12){const id=missiles.indexOf(i.target)+1,trackQualityValue=combatPicture.tracks.get(id)?.quality??.1,guidanceQuality=i.weapon==='RIM-67'?Math.max(.62,trackQualityValue):i.illuminated?Math.max(.55,trackQualityValue):trackQualityValue,saturation=missiles.filter(m=>m.phase!=='destroyed'&&m.mesh.position.distanceTo(i.target.mesh.position)<35).length,illuminationPenalty=needsIllumination&&!i.illuminated?.34:0;const pk=Math.max(.08,Math.min(.88,.48+guidanceQuality*.42-saturation*.07+(i.weapon==='SM-2MR'?.06:0)-illuminationPenalty));const roll=Math.abs(Math.sin(id*97.13+(ammo+sm2Ammo)*17.7+i.age*3.17));i.mesh.visible=false;i.illuminationBeam.visible=false;if(roll<pk){i.target.phase='destroyed';i.target.mesh.visible=false;destroyMissileVisual(i.target,'intercept');phaseEl.textContent='TERMINAL INTERCEPT';log(`${i.weapon} INTERCEPT / PK ${(pk*100).toFixed(0)}%${needsIllumination?' / ILLUMINATED':''}`);}else{log(`${i.weapon} MISS / PK ${(pk*100).toFixed(0)}%${illuminationPenalty?' / NO ILLUMINATOR':''}`);}return;}
  if(terminal){const closestEver=Math.min(i.mesh.userData.closestApproach??Infinity,interceptDistance),previousRange=i.mesh.userData.previousTargetRange??Infinity;i.mesh.userData.closestApproach=closestEver;i.mesh.userData.previousTargetRange=postRange;if(postRange>previousRange+.35&&closestEver<36){i.mesh.visible=false;i.illuminationBeam.visible=false;log(`${i.weapon} MISS / CPA ${(closestEver/10).toFixed(1)} km`);return;}}
  if(i.distanceTraveled>profile.maxRange*1.5){i.mesh.visible=false;i.illuminationBeam.visible=false;log(`${i.weapon} MISS / KINEMATIC ${Math.round(i.distanceTraveled)}/${Math.round(range)} / ALT ${Math.round(i.mesh.position.y)}`);return;}
 });
 if(!missionEnded&&missiles.length>0&&missiles.every(m=>m.phase==='destroyed')&&hullIntegrity>0){interceptors.forEach(i=>{i.mesh.visible=false;i.illuminationBeam.visible=false;});updateShipStatus();finishMission(true);}
}
function updateIncomingMissile(m:Missile,dt:number){
 if(m.phase==='destroyed')return;if(elapsed<m.launchAt){m.mesh.visible=false;m.path.visible=false;return;}m.mesh.visible=true;m.path.visible=true;
 m.age+=dt;
 const range=m.mesh.position.distanceTo(defender.position),profile=incomingProfiles[m.kind],terminalFactor=THREE.MathUtils.clamp((profile.terminalAt-range)/(profile.terminalAt*.72),0,1);m.phase=range<profile.terminalAt?'terminal':range<profile.terminalAt*1.9?'midcourse':'inbound';
 const commandedAltitude=THREE.MathUtils.lerp(profile.cruiseAltitude,profile.terminalAltitude,terminalFactor);
 const aimPoint=defender.position.clone().add(m.aimOffset).add(new THREE.Vector3(0,commandedAltitude,0));
 const desired=aimPoint.sub(m.mesh.position).normalize();
 const current=m.velocity.clone().normalize();
 const angle=current.angleTo(desired),maxTurn=THREE.MathUtils.degToRad(profile.turnRate*(1+terminalFactor*.75))*dt;
 const blend=angle>0?Math.min(1,maxTurn/angle):1;
 const direction=current.lerp(desired,blend).normalize();
 const targetSpeed=THREE.MathUtils.lerp(profile.cruiseSpeed,profile.terminalSpeed,terminalFactor);
 const speed=THREE.MathUtils.lerp(m.velocity.length(),targetSpeed,Math.min(1,dt*.55));
 m.velocity.copy(direction.multiplyScalar(speed));
 m.mesh.position.addScaledVector(m.velocity,dt);
 m.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),m.velocity.clone().normalize());
 if(m.history.length===0||m.mesh.position.distanceTo(m.history[m.history.length-1])>3){m.history.push(m.mesh.position.clone());if(m.history.length>90)m.history.shift();m.path.geometry.dispose();m.path.geometry=new THREE.BufferGeometry().setFromPoints(m.history);}
 if(range<18){const nearestSam=interceptors.filter(i=>i.mesh.visible).reduce((best,i)=>Math.min(best,i.mesh.position.distanceTo(m.mesh.position)),Infinity);m.phase='destroyed';m.mesh.visible=false;leakers++;hullIntegrity=Math.max(0,hullIntegrity-profile.damage);destroyMissileVisual(m,'impact');log(`${m.kind} IMPACT / ${profile.damage}% DAMAGE / SAM ${Number.isFinite(nearestSam)?nearestSam.toFixed(0):'NONE'} / HULL ${hullIntegrity}%`);updateShipStatus();if(hullIntegrity<=0){phaseEl.textContent='USS LONG BEACH DISABLED';finishMission(false);}}
}
function updateTargetMarker(){const selected=missiles[selectedTargetId-1];if(!selected||selected.phase==='destroyed'||elapsed<selected.launchAt){targetMarker.style.display='none';return;}const projected=selected.mesh.position.clone().project(camera),behind=projected.z<-1||projected.z>1,rawX=(projected.x*.5+.5)*innerWidth,rawY=(-projected.y*.5+.5)*innerHeight,margin=innerWidth<560?28:46,safeTop=innerWidth<560?250:76,safeBottom=innerWidth<560?116:110,centerX=innerWidth*.5,centerY=innerHeight*.5,angle=Math.atan2(rawY-centerY,rawX-centerX),displayX=behind?centerX+Math.cos(angle+Math.PI)*innerWidth:centerX+Math.cos(angle)*innerWidth,displayY=behind?centerY+Math.sin(angle+Math.PI)*innerHeight:centerY+Math.sin(angle)*innerHeight,x=Math.max(margin,Math.min(innerWidth-margin,behind?displayX:rawX)),y=Math.max(safeTop,Math.min(innerHeight-safeBottom,behind?displayY:rawY)),offscreen=behind||rawX<margin||rawX>innerWidth-margin||rawY<safeTop||rawY>innerHeight-safeBottom,track=combatPicture.tracks.get(selectedTargetId),range=selected.mesh.position.distanceTo(defender.position),tti=Math.max(0,Math.round(range/Math.max(1,selected.velocity.length())));targetMarker.style.display='block';targetMarker.style.left=`${x}px`;targetMarker.style.top=`${y}px`;targetMarker.style.setProperty('--bearing',`${Math.atan2((behind?displayY:rawY)-centerY,(behind?displayX:rawX)-centerX)}rad`);targetMarker.classList.toggle('offscreen',offscreen);targetMarker.classList.toggle('right-edge',x>innerWidth-180);targetMarkerLabel.textContent=`T${String(selectedTargetId).padStart(2,'0')} ${track?.classification==='classified'?selected.kind:track?.classification.toUpperCase()??'UNCONF'} / ${tti}s / ${selected.phase.toUpperCase()}`;}
function tick(now:number){
 const realDt=Math.min((now-last)/1000,.1);last=now;
 if(running){simAccumulator+=realDt*timeScale;while(simAccumulator>=.05&&running){elapsed+=.05;updateCombat(.05);missiles.forEach(m=>updateIncomingMissile(m,.05));simAccumulator-=.05;}const activeMissiles=missiles.filter(m=>m.phase!=='destroyed'&&elapsed>=m.launchAt),live=activeMissiles.length,distances=activeMissiles.map(m=>m.mesh.position.distanceTo(defender.position));document.querySelector('#targetCount')!.textContent=`${live} ACTIVE / ${missiles.filter(m=>m.phase!=='destroyed').length-live} RESERVE / ${distances.length?(Math.max(...distances)/10).toFixed(1):'0.0'} km`;}
 for(let i=0;i<seaPositions.count;i++){const p=i*3,x=seaBase[p],y=seaBase[p+1];seaPositions.setZ(i,Math.sin(x*.026+elapsed*.72)*.48+Math.sin(y*.019-elapsed*.54)*.34+Math.sin((x+y)*.011+elapsed*.31)*.2);}seaPositions.needsUpdate=true;if(++waveFrame%8===0)seaGeometry.computeVertexNormals();
 missiles.forEach((m,index)=>{if(!m.mesh.visible)return;const pulse=.88+Math.sin(elapsed*19+index*1.7)*.12;(m.mesh.userData.exhaust as THREE.Mesh|undefined)?.scale.set(1,pulse,1);(m.mesh.userData.hotCore as THREE.Mesh|undefined)?.scale.setScalar(.9+pulse*.12);});
 clockEl.textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`;updateCamera();updateTargetMarker();renderer.render(scene,camera);requestAnimationFrame(tick);
}
requestAnimationFrame(tick);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
canvas.addEventListener('pointerdown',e=>{dragging=true;px=e.clientX;py=e.clientY}); addEventListener('pointerup',()=>dragging=false); addEventListener('pointermove',e=>{if(!dragging)return;az-=(e.clientX-px)*.006;el=Math.max(.15,Math.min(1.2,el+(e.clientY-py)*.005));px=e.clientX;py=e.clientY}); canvas.addEventListener('wheel',e=>{dist=Math.max(70,Math.min(360,dist+e.deltaY*.12))}); addEventListener('keydown',e=>{if(e.code==='Space')running=!running;if(e.key.toLowerCase()==='r')location.reload()});
addEventListener('keydown',e=>{if(e.key==='1'){cinematic=false;az=.8;el=.32;dist=125;}if(e.key==='2'){cinematic=false;az=.65;el=.48;dist=210;}if(e.key==='3'){cinematic=false;az=.15;el=.25;dist=150;}if(e.key.toLowerCase()==='c')cinematic=!cinematic;});
