import * as THREE from 'three';
import './style.css';
import { CombatPicture } from './sim';

type EnemyType='P-500'|'P-700'|'Kh-22';
type Missile={mesh:THREE.Group; velocity:THREE.Vector3; phase:'inbound'|'boost'|'midcourse'|'terminal'|'destroyed'; age:number; history:THREE.Vector3[]; path:THREE.Line; kind:EnemyType; speedFactor:number; rcs:number; launchAt:number; aimOffset:THREE.Vector3;bank:number;};
type Interceptor={mesh:THREE.Group; target:Missile; age:number; weapon:'RIM-67'|'SM-2MR'; velocity:THREE.Vector3; distanceTraveled:number; history:THREE.Vector3[]; guidancePath:THREE.Line; commandPoint:THREE.Vector3; commandVelocity:THREE.Vector3; nextDatalink:number; datalinkValid:boolean; illuminated:boolean; illuminationBeam:THREE.Line;};
type Explosion={core:THREE.Mesh; ring:THREE.Mesh; light:THREE.PointLight; age:number;};
type ShipDamageEffect={group:THREE.Group;fire:THREE.Mesh;smoke:THREE.Mesh[];light:THREE.PointLight;seed:number;};
type BoosterDebris={mesh:THREE.Group;velocity:THREE.Vector3;spin:THREE.Vector3;light:THREE.PointLight;age:number;};
const canvas=document.querySelector('#scene') as HTMLCanvasElement;
const scene=new THREE.Scene(); scene.fog=new THREE.Fog(0x06111b,180,900); scene.background=new THREE.Color(0x06111b);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,2000); camera.position.set(120,95,150); camera.lookAt(0,0,0);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
scene.add(new THREE.HemisphereLight(0x9cc7dd,0x10212b,1.55)); const sun=new THREE.DirectionalLight(0xffe3ad,2.5); sun.position.set(-120,200,100);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-250;sun.shadow.camera.right=250;sun.shadow.camera.top=250;sun.shadow.camera.bottom=-250;scene.add(sun);
const seaGeometry=new THREE.PlaneGeometry(1800,1800,64,64);const sea=new THREE.Mesh(seaGeometry,new THREE.MeshStandardMaterial({color:0x0a3340,roughness:.68,metalness:.18,flatShading:false})); sea.rotation.x=-Math.PI/2; scene.add(sea);const seaPositions=seaGeometry.attributes.position as THREE.BufferAttribute;const seaBase=Float32Array.from(seaPositions.array as ArrayLike<number>);
const grid=new THREE.GridHelper(1200,48,0x1d6570,0x123f4b); grid.position.y=.15; (grid.material as THREE.Material).opacity=.25; (grid.material as THREE.Material).transparent=true; scene.add(grid);
function createHullGeometry(){
 const sections=[[-29,3.15],[-27,3.9],[-22,4.35],[-14,4.55],[8,4.65],[17,4.2],[23,3.15],[27,1.65],[29.5,.18]] as const;
 const vertices:number[]=[],indices:number[]=[];
 for(const [x,w] of sections)vertices.push(x,6,-w,x,6,w,x,.4,-w*.58,x,.4,w*.58);
 for(let i=0;i<sections.length-1;i++){const a=i*4,b=(i+1)*4;indices.push(a,a+1,b+1,a,b+1,b,a+2,b+2,b+3,a+2,b+3,a+3,a,a+2,b+2,a,b+2,b,a+1,b+1,b+3,a+1,b+3,a+3);}
 indices.push(0,4,5,0,5,1,(sections.length-1)*4,(sections.length-1)*4+1,(sections.length-1)*4+3,(sections.length-1)*4,(sections.length-1)*4+3,(sections.length-1)*4+2);
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;
}
function createSlopedBoxGeometry(length:number,height:number,depth:number,slope:number){const geometry=new THREE.BoxGeometry(length,height,depth,1,1,1),position=geometry.attributes.position as THREE.BufferAttribute;for(let i=0;i<position.count;i++)if(position.getX(i)>0&&position.getY(i)>0)position.setX(i,position.getX(i)-slope);position.needsUpdate=true;geometry.computeVertexNormals();return geometry;}
function createHullNumberTexture(){const c=document.createElement('canvas');c.width=128;c.height=64;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,128,64);ctx.fillStyle='#e8ece5';ctx.font='bold 46px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('9',64,34);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
function ship(color:number,scale=1){
 const g=new THREE.Group(); g.scale.setScalar(scale);
 const hullMat=new THREE.MeshStandardMaterial({color,metalness:.72,roughness:.32});
 const deckMat=new THREE.MeshStandardMaterial({color:0x707d7c,metalness:.35,roughness:.6});
 const darkMat=new THREE.MeshStandardMaterial({color:0x263538,metalness:.5,roughness:.45});
 const hull=new THREE.Mesh(createHullGeometry(),hullMat);g.add(hull);
 const deckShape=new THREE.Shape(); deckShape.moveTo(-28,-3.15);deckShape.lineTo(-22,-4.25);deckShape.lineTo(16,-4.25);deckShape.lineTo(23,-3.15);deckShape.lineTo(29,0);deckShape.lineTo(23,3.15);deckShape.lineTo(16,4.25);deckShape.lineTo(-22,4.25);deckShape.lineTo(-28,3.15);deckShape.closePath(); const mainDeck=new THREE.Mesh(new THREE.ShapeGeometry(deckShape),deckMat); mainDeck.rotation.x=-Math.PI/2;mainDeck.position.y=6.05;g.add(mainDeck);
 const waterline=new THREE.Mesh(createHullGeometry(),new THREE.MeshStandardMaterial({color:0x151d20,roughness:.75}));waterline.scale.set(1.002,.28,1.002);waterline.position.y=-.1;g.add(waterline);
 const keel=new THREE.Mesh(new THREE.BoxGeometry(24,.7,2.8),darkMat); keel.position.set(-1,.15,0); g.add(keel);
 const aftDeck=new THREE.Mesh(new THREE.BoxGeometry(13,.7,8),deckMat); aftDeck.position.set(-10,6,0); g.add(aftDeck);
 const bridge=new THREE.Mesh(createSlopedBoxGeometry(11,5.5,6.5,1.35),deckMat); bridge.position.set(5,8,0); g.add(bridge);
 const bridgeRoof=new THREE.Mesh(new THREE.BoxGeometry(13,.8,7.2),darkMat); bridgeRoof.position.set(5,11,0); g.add(bridgeRoof);
 const mast=new THREE.Mesh(new THREE.CylinderGeometry(.45,.7,20,8),darkMat); mast.position.set(1,20,0); g.add(mast);
 const yard=new THREE.Mesh(new THREE.BoxGeometry(11,.35,.35),darkMat); yard.position.set(1,24,0); g.add(yard);
 const radar=new THREE.Group(); radar.position.set(1,24,0); const dish=new THREE.Mesh(new THREE.BoxGeometry(5.8,4.3,.45),new THREE.MeshStandardMaterial({color:0x9caaa6,metalness:.35,roughness:.52})); dish.rotation.z=.08; radar.add(dish); const backing=new THREE.Mesh(new THREE.BoxGeometry(3.8,3.1,1.1),darkMat);backing.position.z=-.65;radar.add(backing);for(let x=-2;x<=2;x++)for(let y=-1;y<=1;y++){const cell=new THREE.Mesh(new THREE.BoxGeometry(.65,.65,.12),new THREE.MeshStandardMaterial({color:0xc1cbc5,metalness:.3,roughness:.5}));cell.position.set(x,y*1.05,.3);radar.add(cell);} const feed=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,2.8,8),darkMat);feed.rotation.x=Math.PI/2;feed.position.z=1.6;radar.add(feed);g.add(radar);
 const fireControl=new THREE.Group(); fireControl.position.set(8,12,0); fireControl.add(new THREE.Mesh(new THREE.SphereGeometry(1.6,12,8),new THREE.MeshStandardMaterial({color:0x9ba9a6,metalness:.5,roughness:.45}))); g.add(fireControl);
 const launcher=new THREE.Group(); launcher.position.set(-21,7,0);launcher.rotation.y=Math.PI; launcher.userData.arms=[];launcher.add(new THREE.Mesh(new THREE.BoxGeometry(8,1.2,5.5),darkMat)); for(const z of [-2.1,2.1]){const rail=new THREE.Mesh(new THREE.BoxGeometry(7,.4,.28),deckMat); rail.position.set(0,1,z); launcher.add(rail);} g.add(launcher);
 const pivot=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.5,1.3,12),darkMat);pivot.position.y=1.1;launcher.add(pivot);for(const z of [-1.8,1.8]){const arm=new THREE.Group();arm.name='launcherArm';launcher.userData.arms.push(arm);const beam=new THREE.Mesh(new THREE.BoxGeometry(8,.35,.45),deckMat);beam.position.set(2.5,2,z);arm.add(beam);const readyRound=new THREE.Mesh(new THREE.CylinderGeometry(.22,.28,5.5,8),new THREE.MeshStandardMaterial({color:0xd0d4ca,metalness:.45,roughness:.35}));readyRound.rotation.z=Math.PI/2;readyRound.position.set(3,2.35,z);arm.add(readyRound);launcher.add(arm);}
 const windowMat=new THREE.MeshStandardMaterial({color:0x75d8d4,emissive:0x164b4a,emissiveIntensity:1.8}); const windows=new THREE.Group();for(let z=-2.3;z<=2.3;z+=1.15){const pane=new THREE.Mesh(new THREE.BoxGeometry(.18,.5,.72),windowMat);pane.position.set(10.58,9.6,z);windows.add(pane);}for(const side of [-1,1])for(let x=1.5;x<=8.5;x+=1.4){const pane=new THREE.Mesh(new THREE.BoxGeometry(.72,.5,.18),windowMat);pane.position.set(x,9.6,side*3.33);windows.add(pane);}g.add(windows);
 const upperBridge=new THREE.Mesh(createSlopedBoxGeometry(7,2.4,5.2,.8),deckMat); upperBridge.position.set(4,13,0); g.add(upperBridge);
 const aftHouse=new THREE.Mesh(createSlopedBoxGeometry(8,3.2,6,.45),deckMat); aftHouse.position.set(-7,8.2,0); g.add(aftHouse);
 const stack=new THREE.Mesh(new THREE.CylinderGeometry(1.1,1.35,5,10),darkMat); stack.position.set(-4,12.3,0); g.add(stack);
 const gunMount=new THREE.Group(); gunMount.position.set(15,7,0); const turret=new THREE.Mesh(new THREE.CylinderGeometry(2,2.4,1.5,10),deckMat); gunMount.add(turret); const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.22,.3,7,8),darkMat); barrel.rotation.z=Math.PI/2; barrel.position.set(3.5,1,0); gunMount.add(barrel); g.add(gunMount);
 const aftDirector=new THREE.Group(); aftDirector.position.set(-7,12,0); aftDirector.add(new THREE.Mesh(new THREE.SphereGeometry(1.3,12,8),new THREE.MeshStandardMaterial({color:0x9ba9a6,metalness:.5,roughness:.45}))); g.add(aftDirector);
 for(const side of [-1,1]){const rail=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,42,6),new THREE.MeshStandardMaterial({color:0xa5afaa,metalness:.5,roughness:.5}));rail.rotation.z=Math.PI/2;rail.position.set(-1,7,side*4.15);g.add(rail);for(let x=-19;x<=18;x+=4){const post=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,1.2,6),darkMat);post.position.set(x,6.5,side*4.15);g.add(post);}}
 for(const side of [-1,1])for(const x of [-5,-1]){const raft=new THREE.Mesh(new THREE.CylinderGeometry(.45,.45,2.2,10),new THREE.MeshStandardMaterial({color:0xe6ded0,roughness:.65}));raft.rotation.x=Math.PI/2;raft.position.set(x,8.1,side*3.8);g.add(raft);}
 for(const x of [-5,5]){const antenna=new THREE.Mesh(new THREE.CylinderGeometry(.04,.04,7,6),darkMat);antenna.position.set(x,17,0);antenna.rotation.z=x<0?-.18:.18;g.add(antenna);}
 const numberMat=new THREE.MeshBasicMaterial({map:createHullNumberTexture(),transparent:true,side:THREE.DoubleSide,depthWrite:false});for(const side of [-1,1]){const number=new THREE.Mesh(new THREE.PlaneGeometry(3.2,1.6),numberMat);number.position.set(17.5,3.7,side*4.02);number.rotation.y=side>0?0:Math.PI;g.add(number);const nav=new THREE.PointLight(side>0?0x36ff78:0xff3a32,3,18);nav.position.set(6,14,side*3.7);g.add(nav);}
 for(const side of [-1,1]){const anchor=new THREE.Mesh(new THREE.TorusGeometry(.45,.12,8,16),darkMat);anchor.position.set(21,3.2,side*3.1);anchor.rotation.x=Math.PI/2;g.add(anchor);}
 for(const x of [-15,-10,10]){const hatch=new THREE.Mesh(new THREE.BoxGeometry(2.2,.16,1.4),darkMat);hatch.position.set(x,6.3,0);g.add(hatch);}
 for(const x of [-14,-8,0,8,14]){const bollard=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,.8,8),darkMat); bollard.position.set(x,6.5,4); g.add(bollard);}
 const forwardLauncher=launcher.clone(true);forwardLauncher.position.set(21,7,0);forwardLauncher.rotation.y=0;forwardLauncher.scale.setScalar(.88);forwardLauncher.userData.arms=[];forwardLauncher.traverse(o=>{if(o.name==='launcherArm')forwardLauncher.userData.arms.push(o);});g.add(forwardLauncher);
 const aftMast=new THREE.Group();aftMast.position.set(-7,12,0);for(const side of [-1,1]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.14,.22,12,7),darkMat);leg.position.set(0,5,side*1.55);leg.rotation.x=side*.18;aftMast.add(leg);}for(let y=1;y<=10;y+=2){const brace=new THREE.Mesh(new THREE.BoxGeometry(.18,.18,3.2),darkMat);brace.position.y=y;aftMast.add(brace);}const sps49=new THREE.Group(),antennaMat=new THREE.MeshStandardMaterial({color:0xaab8b3,metalness:.62,roughness:.32});sps49.position.y=11;const antennaFrame=new THREE.Mesh(new THREE.BoxGeometry(9,.18,.18),antennaMat);sps49.add(antennaFrame);for(let x=-4;x<=4;x+=1){const vertical=new THREE.Mesh(new THREE.BoxGeometry(.06,3,.08),antennaMat);vertical.position.set(x,0,0);sps49.add(vertical);}for(const y of [-1.5,0,1.5]){const horizontal=new THREE.Mesh(new THREE.BoxGeometry(9,.06,.08),antennaMat);horizontal.position.y=y;sps49.add(horizontal);}const antennaFeed=new THREE.Mesh(new THREE.CylinderGeometry(.08,.08,2.6,6),darkMat);antennaFeed.rotation.x=Math.PI/2;antennaFeed.position.z=1.4;sps49.add(antennaFeed);aftMast.add(sps49);g.add(aftMast);
 const directors:THREE.Group[]=[];for(const [x,z,heading] of [[9,-3.4,-.38],[-8,3.4,2.72]] as const){const director=new THREE.Group();director.position.set(x,13,z);director.rotation.y=heading;const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(.75,1.05,1.4,12),darkMat);director.add(pedestal);const dish=new THREE.Mesh(new THREE.SphereGeometry(1.55,18,10,0,Math.PI*2,0,Math.PI*.48),new THREE.MeshStandardMaterial({color:0xaab7b2,metalness:.45,roughness:.38,side:THREE.DoubleSide}));dish.rotation.z=-Math.PI/2;dish.position.set(1.1,.7,0);director.add(dish);const horn=new THREE.Mesh(new THREE.CylinderGeometry(.08,.16,1.8,8),darkMat);horn.rotation.z=Math.PI/2;horn.position.set(2,.7,0);director.add(horn);directors.push(director);g.add(director);}
 const highDetail=new THREE.Group();for(const [x,z] of [[-1,-3.7],[-1,3.7],[6,-3.7],[6,3.7]] as const){const canister=new THREE.Mesh(new THREE.BoxGeometry(4.6,.85,1.05),new THREE.MeshStandardMaterial({color:0x6d7774,metalness:.52,roughness:.48}));canister.position.set(x,7.15,z);canister.rotation.y=z>0?.12:-.12;highDetail.add(canister);}for(const [x,z] of [[-10,-4.1],[-10,4.1]] as const){const boat=new THREE.Mesh(new THREE.CapsuleGeometry(.62,3.4,4,10),new THREE.MeshStandardMaterial({color:0xc4c1ac,roughness:.68}));boat.rotation.z=Math.PI/2;boat.position.set(x,9,z);highDetail.add(boat);}for(const [x,z] of [[-14,0],[13,0]] as const){const ciws=new THREE.Group();ciws.position.set(x,7.4,z);const base=new THREE.Mesh(new THREE.CylinderGeometry(.8,1.05,.8,12),deckMat);ciws.add(base);const turret=new THREE.Mesh(new THREE.BoxGeometry(1.15,1.2,1),new THREE.MeshStandardMaterial({color:0xd2d7cf,metalness:.35,roughness:.48}));turret.position.y=1;ciws.add(turret);for(let barrelIndex=-1;barrelIndex<=1;barrelIndex++){const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,2.4,6),darkMat);barrel.rotation.z=Math.PI/2;barrel.position.set(1.45,1.18,barrelIndex*.13);ciws.add(barrel);}highDetail.add(ciws);}for(const side of [-1,1])for(let x=-20;x<=22;x+=3){const stanchion=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.7,5),darkMat);stanchion.position.set(x,6.75,side*4.18);highDetail.add(stanchion);}const smokePuffs:THREE.Mesh[]=[];for(let i=0;i<9;i++){const puff=new THREE.Mesh(new THREE.SphereGeometry(.7,7,5),new THREE.MeshBasicMaterial({color:0x526064,transparent:true,opacity:.12,depthWrite:false}));smokePuffs.push(puff);highDetail.add(puff);}g.add(highDetail);
 g.userData={radar,sps49,fireControl,launcher,forwardLauncher,directors,highDetail,smokePuffs,hullMat,detail:[radar,sps49,fireControl,launcher,forwardLauncher,windows,aftMast]};
 return g;
}
const defender=ship(0x4b5a59); defender.position.set(0,0,40);defender.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});scene.add(defender);
const wake=new THREE.Group(),wakeLineMat=new THREE.LineBasicMaterial({color:0xc5eff0,transparent:true,opacity:.3,depthWrite:false,blending:THREE.AdditiveBlending});for(const side of [-1,1])for(const offset of [0,1.2]){const points=[new THREE.Vector3(0,0,side*(2.8+offset*.25)),new THREE.Vector3(-14,0,side*(4.4+offset)),new THREE.Vector3(-34,0,side*(8+offset*1.6)),new THREE.Vector3(-58,0,side*(14+offset*2))];wake.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),wakeLineMat));}wake.position.set(-28,.22,40);scene.add(wake);
const missiles:Missile[]=[]; const interceptors:Interceptor[]=[]; const combatPicture=new CombatPicture(); const radarCanvas=document.querySelector('#radar') as HTMLCanvasElement; const radarCtx=radarCanvas?.getContext('2d');let launcherCycle=0;
const lastTrackClasses=new Map<number,string>();
const explosions:Explosion[]=[];
const explodedTargets=new Set<Missile>();
const shipDamageEffects:ShipDamageEffect[]=[];
const boosterDebris:BoosterDebris[]=[];
const WORLD_UNITS_PER_KM=10,RADAR_PIXELS_PER_WORLD_UNIT=.14;
const weaponProfiles={
 'RIM-67':{minRange:20,maxRange:750,maxSpeed:12.5,boost:5.2,acceleration:3.1,turnRate:THREE.MathUtils.degToRad(18),terminalRange:180},
 'SM-2MR':{minRange:15,maxRange:450,maxSpeed:13.5,boost:4.4,acceleration:3.6,turnRate:THREE.MathUtils.degToRad(22),terminalRange:100}
} as const;
const incomingProfiles={
 'P-500':{cruiseAltitude:1.2,terminalAltitude:.3,terminalAt:180,cruiseSpeed:8.8,terminalSpeed:9.6,turnRate:8,damage:28,defaultRange:600},
 'P-700':{cruiseAltitude:2.6,terminalAltitude:.4,terminalAt:220,cruiseSpeed:9.8,terminalSpeed:10.8,turnRate:6.5,damage:38,defaultRange:750},
 'Kh-22':{cruiseAltitude:360,terminalAltitude:2.2,terminalAt:450,cruiseSpeed:13.2,terminalSpeed:15.2,turnRate:4.5,damage:46,defaultRange:1000}
} as const;
function defensiveShotRequirement(missile:Missile,quality:number){return missile.kind==='Kh-22'||missile.phase==='terminal'||quality<.42?2:1;}
function missileThreatScore(missile:Missile,quality:number){const range=missile.mesh.position.distanceTo(defender.position),tti=range/Math.max(1,missile.velocity.length());return Math.max(0,120-tti)*2+(missile.phase==='terminal'?90:missile.phase==='midcourse'?35:0)+(missile.kind==='Kh-22'?45:missile.kind==='P-700'?18:0)+quality*12;}
function createEnemyMissile(kind:EnemyType){
 const g=new THREE.Group(),isGranite=kind==='P-700',isKh22=kind==='Kh-22',length=isKh22?11:isGranite?9.6:8.8,radius=isGranite?1.05:isKh22?.72:.86;
 const skin=new THREE.MeshStandardMaterial({color:isKh22?0xb7b9ad:isGranite?0xa9553d:0xb96245,metalness:.58,roughness:.4});
 const dark=new THREE.MeshStandardMaterial({color:0x242b2c,metalness:.55,roughness:.5});
 const body=new THREE.Mesh(new THREE.CylinderGeometry(radius*.9,radius,length,14),skin);body.rotation.x=Math.PI/2;g.add(body);
 const forwardBand=new THREE.Mesh(new THREE.CylinderGeometry(radius*.94,radius*.94,.42,14),new THREE.MeshStandardMaterial({color:isKh22?0xd8d9cf:0x373f40,metalness:.65,roughness:.35}));forwardBand.rotation.x=Math.PI/2;forwardBand.position.z=-length*.28;g.add(forwardBand);
 const nose=new THREE.Mesh(new THREE.ConeGeometry(radius*.9,isKh22?2.8:2.1,14),skin);nose.rotation.x=-Math.PI/2;nose.position.z=-length*.5-1;g.add(nose);
 const tail=new THREE.Mesh(new THREE.CylinderGeometry(radius*.72,radius,1.6,14),dark);tail.rotation.x=Math.PI/2;tail.position.z=length*.5+.6;g.add(tail);
 const wingSpan=isKh22?4.8:isGranite?5.6:5.1,wingChord=isKh22?3.4:2.8;
 const wingShape=new THREE.Shape();wingShape.moveTo(0,0);wingShape.lineTo(wingSpan,wingChord*.7);wingShape.lineTo(wingSpan*.78,-wingChord*.45);wingShape.lineTo(0,-wingChord*.7);wingShape.closePath();
 for(const side of [-1,1]){const wing=new THREE.Mesh(new THREE.ShapeGeometry(wingShape),skin);wing.rotation.x=Math.PI/2;wing.rotation.z=side<0?Math.PI:0;wing.position.set(side*radius*.45,0,isKh22?.5:1);g.add(wing);}
 for(const side of [-1,1]){const fin=new THREE.Mesh(new THREE.BoxGeometry(isKh22?.13:.18,isKh22?2.2:1.7,2.5),dark);fin.position.set(side*(radius+.35),0,length*.35);fin.rotation.z=side*.18;g.add(fin);}
 if(isGranite){const intake=new THREE.Mesh(new THREE.CylinderGeometry(.42,.58,3,10),dark);intake.rotation.x=Math.PI/2;intake.position.set(0,-radius*.85,1);g.add(intake);}
 if(kind==='P-500'){for(const side of [-1,1]){const intakeLip=new THREE.Mesh(new THREE.BoxGeometry(1.2,.55,2.6),dark);intakeLip.position.set(side*.78,-.68,.9);intakeLip.rotation.z=side*.16;g.add(intakeLip);}}
 if(isKh22){const dorsal=new THREE.Mesh(new THREE.BoxGeometry(.16,2.8,4.5),skin);dorsal.position.set(0,1.15,1.5);dorsal.rotation.x=.08;g.add(dorsal);const belly=new THREE.Mesh(new THREE.BoxGeometry(1.1,.35,3.8),dark);belly.position.set(0,-.78,1.1);g.add(belly);}
 const exhaust=new THREE.Mesh(new THREE.ConeGeometry(radius*.5,isKh22?6:5,12,1,true),new THREE.MeshBasicMaterial({color:isKh22?0xffd37a:0xff7138,transparent:true,opacity:.72,blending:THREE.AdditiveBlending,depthWrite:false}));exhaust.rotation.x=-Math.PI/2;exhaust.position.z=length*.5+3.4;g.add(exhaust);
 const hotCore=new THREE.Mesh(new THREE.ConeGeometry(radius*.18,3.2,10,1,true),new THREE.MeshBasicMaterial({color:0xfff2c0,transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false}));hotCore.rotation.x=-Math.PI/2;hotCore.position.z=length*.5+2.4;g.add(hotCore);
 const glow=new THREE.PointLight(0xff642d,isKh22?7:5,isKh22?35:28);glow.position.z=length*.5+2;g.add(glow);const seaMist=new THREE.Mesh(new THREE.ConeGeometry(isGranite?1.8:1.45,isGranite?11:9,12,1,true),new THREE.MeshBasicMaterial({color:0xbce8ec,transparent:true,opacity:.16,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}));seaMist.rotation.x=-Math.PI/2;seaMist.position.z=length*.5+7;seaMist.visible=false;g.add(seaMist);const shockCone=new THREE.Mesh(new THREE.ConeGeometry(2.1,7,18,1,true),new THREE.MeshBasicMaterial({color:0xe7f4f2,transparent:true,opacity:.12,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}));shockCone.rotation.x=-Math.PI/2;shockCone.position.z=-length*.16;shockCone.visible=false;g.add(shockCone);g.userData.exhaust=exhaust;g.userData.hotCore=hotCore;g.userData.seaMist=seaMist;g.userData.shockCone=shockCone;return g;
}
function addMissile(pos:THREE.Vector3,kind:EnemyType='P-500',launchAt=0){const visual=kind==='P-700'?{rcs:.7,scale:1.05}:{rcs:kind==='Kh-22'?1.1:.42,scale:kind==='Kh-22'?.92:.96},profile=incomingProfiles[kind],ordinal=missiles.length,aimOffset=new THREE.Vector3(Math.sin((ordinal+1)*2.399)*2.8,0,Math.cos((ordinal+1)*1.73)*1.2);const g=createEnemyMissile(kind);g.position.copy(pos);g.scale.setScalar(visual.scale);g.visible=launchAt<=0;const selection=new THREE.Mesh(new THREE.TorusGeometry(kind==='P-700'?4.8:4.2,.12,8,32),new THREE.MeshBasicMaterial({color:0xffd45a,transparent:true,opacity:.9}));selection.rotation.x=Math.PI/2;selection.visible=false;g.add(selection);g.userData.selection=selection;const history=[pos.clone()];const path=new THREE.Line(new THREE.BufferGeometry().setFromPoints(history),new THREE.LineBasicMaterial({color:kind==='Kh-22'?0xffb05a:0xe25a43,transparent:true,opacity:.34,blending:THREE.AdditiveBlending}));path.visible=g.visible;scene.add(g,path);const initialDirection=defender.position.clone().sub(pos).setY(0).normalize();missiles.push({mesh:g,velocity:initialDirection.multiplyScalar(profile.cruiseSpeed),phase:'inbound',age:0,history,path,kind,speedFactor:profile.cruiseSpeed,rcs:visual.rcs,launchAt,aimOffset,bank:0});}
function launchInterceptor(target:Missile){
 const g=new THREE.Group(),sm2=selectedWeapon==='SM-2MR',missileMat=new THREE.MeshStandardMaterial({color:sm2?0xf0eee4:0xd9d7c7,metalness:.7,roughness:.3});
 const body=new THREE.Mesh(new THREE.CylinderGeometry(sm2?.42:.55,sm2?.48:.62,sm2?5.6:6.4,12),missileMat);body.rotation.x=Math.PI/2;g.add(body);
 const nose=new THREE.Mesh(new THREE.ConeGeometry(sm2?.42:.55,sm2?1.7:2.1,12),missileMat);nose.rotation.x=-Math.PI/2;nose.position.z=-(sm2?3.65:4.25);g.add(nose);
 const booster=new THREE.Group(),boosterBody=new THREE.Mesh(new THREE.CylinderGeometry(sm2?.48:.62,sm2?.55:.7,sm2?2.2:2.8,12),new THREE.MeshStandardMaterial({color:0xb9bcb4,metalness:.55,roughness:.42}));boosterBody.rotation.x=Math.PI/2;boosterBody.position.z=sm2?3.7:4.5;booster.add(boosterBody);for(const side of [-1,1])for(const axis of ['x','y'] as const){const fin=new THREE.Mesh(new THREE.BoxGeometry(axis==='x'?1.8:.12,axis==='y'?1.8:.12,1.25),missileMat);fin.position[axis]=side*(sm2?.82:1.05);fin.position.z=sm2?4.1:4.9;booster.add(fin);}g.add(booster);g.userData.booster=booster;
 const flame=new THREE.PointLight(sm2?0x8fdfff:0x6cdcff,7,28);flame.position.z=sm2?5.1:6;g.add(flame);const trail=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-14)]),new THREE.LineBasicMaterial({color:0x8fe9ff,transparent:true,opacity:.8}));g.add(trail);
 const seeker=new THREE.Mesh(new THREE.ConeGeometry(sm2?5:7,sm2?22:30,20,1,true),new THREE.MeshBasicMaterial({color:0x65e4ff,transparent:true,opacity:.08,depthWrite:false,side:THREE.DoubleSide}));seeker.rotation.x=-Math.PI/2;seeker.position.z=-15;seeker.visible=false;g.add(seeker);g.userData.seeker=seeker;
 const stationName=launcherCycle%2===0?'AFT':'FORWARD',launchStation=stationName==='AFT'?defender.userData.launcher:defender.userData.forwardLauncher,railSide=Math.floor(launcherCycle/2)%2===0?-1.8:1.8;launchStation.userData.lastLaunch=performance.now();launcherCycle++;g.position.copy(launchStation.localToWorld(new THREE.Vector3(3,2.35,railSide)));
 const illuminationBeam=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineBasicMaterial({color:0xffd66b,transparent:true,opacity:.42,blending:THREE.AdditiveBlending,depthWrite:false}));illuminationBeam.visible=false;
 const history=[g.position.clone()],guidancePath=new THREE.Line(new THREE.BufferGeometry().setFromPoints(history),new THREE.LineBasicMaterial({color:sm2?0x9deaff:0x71d6ff,transparent:true,opacity:.5,blending:THREE.AdditiveBlending})),track=combatPicture.tracks.get(missiles.indexOf(target)+1),salvoLeader=interceptors.find(i=>i.mesh.visible&&i.target===target),commandPoint=(salvoLeader?.commandPoint??track?.position??target.mesh.position).clone(),commandVelocity=(salvoLeader?.commandVelocity??track?.velocity??target.velocity).clone(),nextDatalink=salvoLeader?.nextDatalink??elapsed+.35;scene.add(g,illuminationBeam,guidancePath);const initialDirection=commandPoint.clone().sub(g.position);initialDirection.y=Math.max(34,initialDirection.y);initialDirection.normalize();interceptors.push({mesh:g,target,age:0,weapon:selectedWeapon,velocity:initialDirection.multiplyScalar(9),distanceTraveled:0,history,guidancePath,commandPoint,commandVelocity,nextDatalink,datalinkValid:salvoLeader?.datalinkValid??!!track,illuminated:false,illuminationBeam});const launchRange=target.mesh.position.distanceTo(defender.position)/WORLD_UNITS_PER_KM;log(`${selectedWeapon} ${stationName} LAUNCH / ${launchRange.toFixed(1)} km / TRACK ${Math.round((track?.quality??0)*100)}%`);
}
function separateBooster(interceptor:Interceptor){const booster=interceptor.mesh.userData.booster as THREE.Group|undefined;if(!booster||interceptor.mesh.userData.boosterSeparated)return;interceptor.mesh.userData.boosterSeparated=true;scene.attach(booster);const light=new THREE.PointLight(0xffb45b,5,18);light.position.copy(booster.position);scene.add(light);boosterDebris.push({mesh:booster,velocity:interceptor.velocity.clone().multiplyScalar(.62).add(new THREE.Vector3(0,-1.4,0)),spin:new THREE.Vector3(.8,.35,.55),light,age:0});log(`${interceptor.weapon} BOOSTER SEPARATION`);}
function updateBoosterDebris(dt:number){for(let index=boosterDebris.length-1;index>=0;index--){const debris=boosterDebris[index];debris.age+=dt;debris.velocity.y-=1.8*dt;debris.mesh.position.addScaledVector(debris.velocity,dt);debris.mesh.rotation.x+=debris.spin.x*dt;debris.mesh.rotation.y+=debris.spin.y*dt;debris.mesh.rotation.z+=debris.spin.z*dt;debris.light.position.copy(debris.mesh.position);debris.light.intensity=Math.max(0,5-debris.age*4);if(debris.age>5||debris.mesh.position.y<-.5){scene.remove(debris.mesh,debris.light);boosterDebris.splice(index,1);}}}
function createExplosion(position:THREE.Vector3){const core=new THREE.Mesh(new THREE.IcosahedronGeometry(2.2,2),new THREE.MeshBasicMaterial({color:0xffc45e,transparent:true,opacity:.92,depthWrite:false,blending:THREE.AdditiveBlending}));core.position.copy(position);const ring=new THREE.Mesh(new THREE.TorusGeometry(3.2,.22,10,48),new THREE.MeshBasicMaterial({color:0xff7138,transparent:true,opacity:.78,depthWrite:false,blending:THREE.AdditiveBlending}));ring.position.copy(position);ring.quaternion.copy(camera.quaternion);const light=new THREE.PointLight(0xff6a22,18,95);light.position.copy(position);scene.add(core,ring,light);explosions.push({core,ring,light,age:0});}
function createShipDamage(worldPosition:THREE.Vector3,severity:number){const local=defender.worldToLocal(worldPosition.clone()),side=local.z>=0?1:-1,group=new THREE.Group();local.x=THREE.MathUtils.clamp(local.x,-24,24);local.y=6.3;local.z=side*3.75;group.position.copy(local);group.rotation.y=side<0?Math.PI:0;const scorch=new THREE.Mesh(new THREE.CircleGeometry(2.2,18),new THREE.MeshBasicMaterial({color:0x120d0b,transparent:true,opacity:.9,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2}));group.add(scorch);const fire=new THREE.Mesh(new THREE.IcosahedronGeometry(1.15,1),new THREE.MeshBasicMaterial({color:0xff6b24,transparent:true,opacity:.92,depthWrite:false,blending:THREE.AdditiveBlending}));fire.position.set(0,1,.2);group.add(fire);const smoke:THREE.Mesh[]=[];for(let i=0;i<6;i++){const puff=new THREE.Mesh(new THREE.SphereGeometry(.85,7,5),new THREE.MeshBasicMaterial({color:0x667174,transparent:true,opacity:.32,depthWrite:false}));smoke.push(puff);group.add(puff);}const light=new THREE.PointLight(0xff5a24,5+severity*.1,28);light.position.set(0,1.2,.6);group.add(light);defender.add(group);shipDamageEffects.push({group,fire,smoke,light,seed:shipDamageEffects.length*2.37+.4});(defender.userData.hullMat as THREE.MeshStandardMaterial).color.lerp(new THREE.Color(0x2a2423),Math.min(.45,severity/100));}
function flashCombat(kind:'intercept'|'impact'){combatFlash.className='combat-flash';void combatFlash.offsetWidth;combatFlash.classList.add(kind);}
function destroyMissileVisual(missile:Missile,effect:'intercept'|'impact'){if(!explodedTargets.has(missile)){explodedTargets.add(missile);createExplosion(missile.mesh.position.clone());}flashCombat(effect);}
function ciwsTracer(target:THREE.Vector3){const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([defender.position.clone().add(new THREE.Vector3(15,9,0)),target.clone()]),new THREE.LineBasicMaterial({color:0xffef9a,transparent:true,opacity:.9}));scene.add(line);setTimeout(()=>{scene.remove(line);line.geometry.dispose();(line.material as THREE.Material).dispose();},110);}
addMissile(new THREE.Vector3(-85,18,-210)); addMissile(new THREE.Vector3(0,28,-240)); addMissile(new THREE.Vector3(80,14,-220));
let running=true,elapsed=0,simAccumulator=0,last=performance.now(),ammo=6,sm2Ammo=12,selectedWeapon:'RIM-67'|'SM-2MR'='RIM-67',autoFire=true,radarEnabled=true,timeScale=1,selectedTargetId=1,hullIntegrity=100,ciwsEnabled=true,ciwsRounds=1200,lastCiwsShot=-10,nextSamLaunch=0,leakers=0,missionEnded=false,maxSamChannels=3,maxIlluminators=2; let dragging=false,px=0,py=0,az=0.65,el=0.48,dist=210,cinematic=false,waveFrame=0,viewMode:1|2|3=2;
const phaseEl=document.querySelector('#phase')!, clockEl=document.querySelector('#clock')!, targetState=document.querySelector('#targetState')!, feed=document.querySelector('#feed')!, ammoEl=document.querySelector('#ammo')!, weaponEnvelope=document.querySelector('#weaponEnvelope')!, threatName=document.querySelector('#threatName')!, threatRange=document.querySelector('#threatRange')!, threatAltitude=document.querySelector('#threatAltitude')!, trackQuality=document.querySelector('#trackQuality')!, threatTti=document.querySelector('#threatTti')!, qualityFill=document.querySelector('#qualityFill') as HTMLElement;
const targetMarker=document.querySelector('#targetMarker') as HTMLElement,targetMarkerLabel=document.querySelector('#targetMarkerLabel') as HTMLElement,combatFlash=document.querySelector('#combatFlash') as HTMLElement;
const controls=document.createElement('div');controls.className='combat-controls';controls.style.cssText='position:fixed;left:34px;bottom:150px;display:flex;gap:8px;z-index:8';document.body.appendChild(controls);
const resultPanel=document.createElement('div');resultPanel.className='result-panel';resultPanel.style.cssText='display:none;position:fixed;inset:0;margin:auto;width:360px;height:210px;background:#071923ee;border:1px solid #4ac0b8;color:#d5edf0;z-index:20;padding:28px;text-align:center;font:12px Arial;letter-spacing:1px';document.body.appendChild(resultPanel);
let placementMode:false|'enemy'|'ship'=false;
const sandbox=document.createElement('div');sandbox.style.cssText='position:fixed;inset:0;margin:auto;width:470px;height:430px;background:#071923f5;border:1px solid #4ac0b8;color:#d5edf0;z-index:30;padding:28px;font:12px Arial;letter-spacing:1px';sandbox.innerHTML=`<div style="font-size:20px;letter-spacing:3px;margin-bottom:22px">SANDBOX SCENARIO</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px"><label>MISSILE TYPE<select id="sbType"><option>P-500</option><option>P-700</option><option>Kh-22</option></select></label><label>MISSILE COUNT<input id="sbCount" type="number" min="1" max="24" value="6"></label><label>LAUNCH INTERVAL (s)<input id="sbInterval" type="number" min="0" max="20" step="0.5" value="1"></label><label>ALTITUDE (50 m/unit)<input id="sbAltitude" type="number" min="0.2" max="500" step="0.1" value="1.2"></label><label>CENTER X<input id="sbX" type="number" min="-800" max="800" value="0"></label><label>CENTER Z<input id="sbZ" type="number" min="-1200" max="-80" value="-600"></label><label>FORMATION SPREAD<input id="sbSpread" type="number" min="0" max="500" value="150"></label><label>START WEAPON<select id="sbWeapon"><option>RIM-67</option><option>SM-2MR</option></select></label></div><button id="sbStart" style="margin-top:28px;width:100%;border:1px solid #4ac0b8;background:#0b2830;color:#bce7e5;padding:11px;cursor:pointer">START EXERCISE</button>`;sandbox.querySelectorAll('input,select').forEach((e:any)=>e.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px');document.body.appendChild(sandbox);running=false;missiles.forEach(m=>{m.mesh.visible=false;m.path.visible=false;});
sandbox.className='sandbox-panel';
function numberInput(id:string){return Number((sandbox.querySelector(id) as HTMLInputElement).value);}
const pickPlacement=document.createElement('button');pickPlacement.textContent='PICK FORMATION CENTER ON RADAR';pickPlacement.style.cssText='margin-top:12px;width:100%;border:1px solid #547d82;background:#0a2229;color:#9fd3d1;padding:8px;cursor:pointer';sandbox.insertBefore(pickPlacement,sandbox.querySelector('#sbStart'));pickPlacement.onclick=()=>{placementMode='enemy';pickPlacement.textContent='CLICK TACTICAL RADAR...';};
const pickShip=document.createElement('button');pickShip.textContent='PICK USS LONG BEACH ON RADAR';pickShip.style.cssText=pickPlacement.style.cssText;sandbox.insertBefore(pickShip,sandbox.querySelector('#sbStart'));pickShip.onclick=()=>{placementMode='ship';pickShip.textContent='CLICK TACTICAL RADAR...';};
const patternWrap=document.createElement('label');patternWrap.innerHTML='LAUNCH PATTERN<select id="sbPattern"><option value="RIPPLE">RIPPLE / ONE BY ONE</option><option value="SALVO">SALVO / SIMULTANEOUS</option><option value="WAVES">WAVES / GROUPS OF FOUR</option></select>';patternWrap.style.cssText='display:block;margin-top:12px';sandbox.insertBefore(patternWrap,pickPlacement);const patternSelect=patternWrap.querySelector('select') as HTMLSelectElement;patternSelect.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';
patternSelect.remove(2);patternSelect.onchange=()=>{if(patternSelect.value==='SALVO')(sandbox.querySelector('#sbInterval') as HTMLInputElement).value='0';};
sandbox.style.height='570px';
const sandboxGrid=sandbox.querySelector('div[style*="grid"]')!;for(const [label,id,value] of [['SHIP X','sbShipX','0'],['SHIP Z','sbShipZ','40']]){const field=document.createElement('label');field.textContent=label;const input=document.createElement('input');input.id=id;input.type='number';input.value=value;input.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';field.appendChild(input);sandboxGrid.appendChild(field);}sandbox.style.height='640px';
for(const [label,id,value,max] of [['RIM-67 MAGAZINE','sbRim','6','48'],['SM-2MR MAGAZINE','sbSm2','12','96'],['CIWS ROUNDS','sbCiws','1200','6000']]){const field=document.createElement('label');field.textContent=label;const input=document.createElement('input');input.id=id;input.type='number';input.min='0';input.max=max;input.value=value;input.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';field.appendChild(input);sandboxGrid.appendChild(field);}sandbox.style.height='760px';
const channelField=document.createElement('label');channelField.textContent='SAM FIRE CHANNELS';const channelInput=document.createElement('input');channelInput.id='sbChannels';channelInput.type='number';channelInput.min='1';channelInput.max='8';channelInput.value='3';channelInput.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';channelField.appendChild(channelInput);sandboxGrid.appendChild(channelField);
const illuminatorField=document.createElement('label');illuminatorField.textContent='TERMINAL ILLUMINATORS';const illuminatorInput=channelInput.cloneNode() as HTMLInputElement;illuminatorInput.id='sbIlluminators';illuminatorInput.max='4';illuminatorInput.value='2';illuminatorField.appendChild(illuminatorInput);sandboxGrid.appendChild(illuminatorField);
const wave2Type=document.createElement('label');wave2Type.innerHTML='SECOND WAVE TYPE<select id="sbType2"><option value="NONE">NONE</option><option>P-500</option><option>P-700</option><option>Kh-22</option></select>';const wave2Select=wave2Type.querySelector('select') as HTMLSelectElement;wave2Select.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';sandboxGrid.appendChild(wave2Type);for(const [label,id,value,max] of [['SECOND WAVE COUNT','sbCount2','4','12'],['SECOND WAVE DELAY','sbDelay2','10','60']]){const field=document.createElement('label');field.textContent=label;const input=document.createElement('input');input.id=id;input.type='number';input.min='0';input.max=max;input.value=value;input.style.cssText='display:block;width:100%;margin-top:6px;background:#0a252d;border:1px solid #315f63;color:#d5edf0;padding:7px';field.appendChild(input);sandboxGrid.appendChild(field);}sandbox.style.height='850px';
const presets=document.createElement('div');presets.style.cssText='display:flex;gap:7px;margin-top:12px';sandbox.insertBefore(presets,patternWrap);function presetButton(text:string,kind:EnemyType,count:number,interval:number,altitude:number,spread:number,range:number){const b=document.createElement('button');b.textContent=text;b.style.cssText='flex:1;border:1px solid #3d6f73;background:#09232a;color:#9fd3d1;padding:7px;font-size:9px;cursor:pointer';b.onclick=()=>{(sandbox.querySelector('#sbType') as HTMLSelectElement).value=kind;(sandbox.querySelector('#sbCount') as HTMLInputElement).value=String(count);(sandbox.querySelector('#sbInterval') as HTMLInputElement).value=String(interval);(sandbox.querySelector('#sbAltitude') as HTMLInputElement).value=String(altitude);(sandbox.querySelector('#sbSpread') as HTMLInputElement).value=String(spread);(sandbox.querySelector('#sbZ') as HTMLInputElement).value=String(-range);};presets.appendChild(b);}presetButton('SEA SKIMMER','P-500',6,1.5,1.2,140,600);presetButton('SATURATION','P-700',16,0,2.6,260,750);presetButton('HIGH SPEED','Kh-22',8,2,360,190,1000);
radarCanvas.addEventListener('pointerdown',e=>{if(!placementMode)return;e.stopPropagation();const rect=radarCanvas.getBoundingClientRect(),px=(e.clientX-rect.left)/rect.width*radarCanvas.width,py=(e.clientY-rect.top)/rect.height*radarCanvas.height,x=Math.round((px-radarCanvas.width/2)/RADAR_PIXELS_PER_WORLD_UNIT),z=Math.round((py-radarCanvas.height/2)/RADAR_PIXELS_PER_WORLD_UNIT);if(placementMode==='ship'){(sandbox.querySelector('#sbShipX') as HTMLInputElement).value=String(x);(sandbox.querySelector('#sbShipZ') as HTMLInputElement).value=String(z);pickShip.textContent=`SHIP SET / X ${x} / Z ${z}`;}else{(sandbox.querySelector('#sbX') as HTMLInputElement).value=String(x);(sandbox.querySelector('#sbZ') as HTMLInputElement).value=String(z);pickPlacement.textContent=`CENTER SET / X ${x} / Z ${z}`;}placementMode=false;});
(sandbox.querySelector('#sbStart') as HTMLButtonElement).onclick=()=>{missiles.forEach(m=>{scene.remove(m.mesh,m.path);m.path.geometry.dispose();});missiles.length=0;interceptors.forEach(i=>scene.remove(i.mesh));interceptors.length=0;combatPicture.tracks.clear();explodedTargets.clear();explosions.forEach(e=>scene.remove(e.core,e.ring,e.light));explosions.length=0;shipDamageEffects.forEach(effect=>defender.remove(effect.group));shipDamageEffects.length=0;boosterDebris.forEach(debris=>scene.remove(debris.mesh,debris.light));boosterDebris.length=0;(defender.userData.hullMat as THREE.MeshStandardMaterial).color.set(0x4b5a59);elapsed=0;last=performance.now();ammo=6;sm2Ammo=12;hullIntegrity=100;ciwsRounds=1200;missionEnded=false;selectedWeapon=(sandbox.querySelector('#sbWeapon') as HTMLSelectElement).value as 'RIM-67'|'SM-2MR';const kind=(sandbox.querySelector('#sbType') as HTMLSelectElement).value as EnemyType,count=Math.max(1,Math.min(24,numberInput('#sbCount'))),interval=Math.max(0,numberInput('#sbInterval')),altitude=numberInput('#sbAltitude'),cx=numberInput('#sbX'),cz=numberInput('#sbZ'),spread=numberInput('#sbSpread');for(let i=0;i<count;i++){const offset=count===1?0:(i/(count-1)-.5)*spread;addMissile(new THREE.Vector3(cx+offset,altitude+Math.sin(i)*5,cz-Math.abs(offset)*.12),kind,i*interval);}selectedTargetId=1;missiles[0].mesh.userData.selection.visible=true;weaponButton.textContent=`WEAPON: ${selectedWeapon}`;ammoEl.textContent=`RIM ${ammo} / SM2 ${sm2Ammo}`;sandbox.style.display='none';running=true;log(`SANDBOX START / ${count} x ${kind} / ${interval}s INTERVAL`);};
(sandbox.querySelector('#sbStart') as HTMLButtonElement).addEventListener('pointerdown',()=>{interceptors.forEach(i=>{i.illuminationBeam.visible=false;scene.remove(i.illuminationBeam,i.guidancePath);i.guidancePath.geometry.dispose();});explosions.forEach(e=>scene.remove(e.core,e.ring,e.light));simAccumulator=0;nextSamLaunch=0;leakers=0;launcherCycle=0;const x=numberInput('#sbShipX'),z=numberInput('#sbShipZ');defender.position.set(x,0,z);wake.position.set(x-28,.22,z);},true);
(sandbox.querySelector('#sbStart') as HTMLButtonElement).addEventListener('click',()=>setTimeout(()=>{ammo=Math.max(0,Math.min(48,numberInput('#sbRim')));sm2Ammo=Math.max(0,Math.min(96,numberInput('#sbSm2')));ciwsRounds=Math.max(0,Math.min(6000,numberInput('#sbCiws')));maxSamChannels=Math.max(1,Math.min(8,numberInput('#sbChannels')));maxIlluminators=Math.max(1,Math.min(4,numberInput('#sbIlluminators')));ammoEl.textContent=`RIM ${ammo} / SM2 ${sm2Ammo}`;},0));
(sandbox.querySelector('#sbStart') as HTMLButtonElement).addEventListener('click',()=>setTimeout(()=>{const kind2=wave2Select.value as EnemyType|'NONE';if(kind2==='NONE')return;const count=Math.max(0,Math.min(12,numberInput('#sbCount2'))),delay=Math.max(0,numberInput('#sbDelay2')),cx=numberInput('#sbX'),cz=numberInput('#sbZ'),altitude=numberInput('#sbAltitude'),spread=numberInput('#sbSpread');for(let i=0;i<count;i++){const offset=count===1?0:(i/(count-1)-.5)*spread*.75;addMissile(new THREE.Vector3(cx+offset,kind2==='Kh-22'?Math.max(45,altitude):altitude,cz-50),kind2,delay+i*.6);}log(`SECOND WAVE / ${count} x ${kind2} / T+${delay}s`);},0));
function finishMission(victory:boolean){if(missionEnded)return;missionEnded=true;running=false;const score=Math.max(0,Math.round(hullIntegrity*10+ammo*150+sm2Ammo*100+ciwsRounds/10-Math.max(0,elapsed-20)*5)),outcome=victory?(leakers===0?'AIRSPACE SECURED':`RAID SURVIVED / ${leakers} LEAKER${leakers===1?'':'S'}`):'USS LONG BEACH DISABLED';resultPanel.innerHTML=`<div style="font-size:20px;letter-spacing:3px;margin-bottom:18px">${outcome}</div><div>MISSION SCORE ${score}</div><div style="margin-top:10px;color:#78c9c4">HULL ${hullIntegrity}% / RIM ${ammo} / SM2 ${sm2Ammo} / CIWS ${ciwsRounds}</div><button id="restartMission" style="margin-top:25px;border:1px solid #4ac0b8;background:#0b2830;color:#bce7e5;padding:9px 18px;cursor:pointer">RESTART EXERCISE</button>`;resultPanel.style.display='block';resultPanel.querySelector('button')!.addEventListener('click',()=>location.reload());}
function controlButton(label:string,action:()=>void){const b=document.createElement('button');b.textContent=label;b.style.cssText='border:1px solid #438e91;background:#071923dd;color:#a8dddd;padding:8px 11px;font:10px Arial;letter-spacing:1px;cursor:pointer';b.onclick=action;controls.appendChild(b);return b;}
const autoButton=controlButton('AUTO FIRE: ON',()=>{autoFire=!autoFire;autoButton.textContent=`AUTO FIRE: ${autoFire?'ON':'OFF'}`;});
const radarButton=controlButton('RADAR: ACTIVE',()=>{radarEnabled=!radarEnabled;radarButton.textContent=`RADAR: ${radarEnabled?'ACTIVE':'SILENT'}`;log(radarEnabled?'RADAR EMISSION RESTORED':'EMCON / RADAR SILENT');});
const ciwsButton=controlButton('CIWS: AUTO',()=>{ciwsEnabled=!ciwsEnabled;ciwsButton.textContent=`CIWS: ${ciwsEnabled?'AUTO':'HOLD'}`;});
const weaponButton=controlButton('WEAPON: RIM-67',()=>{selectedWeapon=selectedWeapon==='RIM-67'?'SM-2MR':'RIM-67';weaponButton.textContent=`WEAPON: ${selectedWeapon}`;ammoEl.textContent=`RIM ${ammo} / SM2 ${sm2Ammo}`;});
const targetButton=controlButton('TARGET: 1',()=>{const live=missiles.map((m,i)=>({m,id:i+1})).filter(x=>x.m.phase!=='destroyed');if(!live.length)return;const current=live.findIndex(x=>x.id===selectedTargetId);selectedTargetId=live[(current+1)%live.length].id;targetButton.textContent=`TARGET: ${selectedTargetId}`;missiles.forEach((m,i)=>m.mesh.userData.selection.visible=i+1===selectedTargetId&&m.phase!=='destroyed');});
const fireButton=controlButton('LAUNCH SAM',()=>{
 const active=interceptors.filter(i=>i.mesh.visible).length,track=combatPicture.tracks.get(selectedTargetId),target=missiles[selectedTargetId-1],available=selectedWeapon==='RIM-67'?ammo:sm2Ammo,profile=weaponProfiles[selectedWeapon];
 if(!running){log('LAUNCH INHIBIT / SIMULATION PAUSED');return;}if(elapsed<nextSamLaunch){log('LAUNCH INHIBIT / MK 10 LAUNCHER CYCLING');return;}if(active>=maxSamChannels){log(`LAUNCH INHIBIT / CHANNELS ${active}/${maxSamChannels}`);return;}if(available<=0){log('LAUNCH INHIBIT / MAGAZINE EMPTY');return;}if(!target||target.phase==='destroyed'){log('LAUNCH INHIBIT / TARGET INVALID');return;}if(!track){log(`LAUNCH INHIBIT / TRACK ${selectedTargetId} LOST`);return;}if(track.quality<.32||track.age>2.2){log(`LAUNCH INHIBIT / TRACK QUALITY ${Math.round(track.quality*100)}%`);return;}const assigned=interceptors.filter(i=>i.mesh.visible&&i.target===target).length,required=defensiveShotRequirement(target,track.quality);if(assigned>=required){log(`LAUNCH INHIBIT / SALVO COMPLETE ${assigned}/${required}`);return;}
 const range=target.mesh.position.distanceTo(defender.position);if(range<profile.minRange||range>profile.maxRange){log(`LAUNCH INHIBIT / ${selectedWeapon} ENVELOPE ${(profile.minRange/10).toFixed(1)}-${(profile.maxRange/10).toFixed(1)} km`);return;}
 launchInterceptor(target);nextSamLaunch=elapsed+.12;if(selectedWeapon==='RIM-67')ammo--;else sm2Ammo--;ammoEl.textContent=`RIM ${ammo} / SM2 ${sm2Ammo}`;
});
const speedButton=controlButton('TIME: 1X',()=>{timeScale=timeScale===1?2:timeScale===2?4:1;speedButton.textContent=`TIME: ${timeScale}X`;});
controlButton('SCENARIO SETUP',()=>{running=false;sandbox.style.display='block';});
missiles[0].mesh.userData.selection.visible=true;
function log(s:string){const d=document.createElement('div'); d.textContent=s; feed.prepend(d); while(feed.children.length>5)feed.lastChild?.remove();}
function updateShipStatus(){const active=interceptors.filter(i=>i.mesh.visible).length,illuminated=interceptors.filter(i=>i.mesh.visible&&i.illuminated).length;document.querySelector('#shipState')!.textContent=`HULL ${hullIntegrity}% / CH ${active}/${maxSamChannels} / ILL ${illuminated}/${maxIlluminators}`;}
log('16:42:08  NTU combat system initialized'); log('16:42:11  SURFACE SEARCH RADAR — CONTACTS ACQUIRED');
function updateCamera(){if(cinematic)az+=.0018;let focus:THREE.Vector3;if(viewMode===1)focus=defender.position.clone().add(new THREE.Vector3(0,9,0));else if(viewMode===3){const track=combatPicture.tracks.get(selectedTargetId);focus=track?defender.position.clone().lerp(track.position,.52):defender.position.clone().add(new THREE.Vector3(0,8,-80));}else focus=new THREE.Vector3(defender.position.x,8,defender.position.z-80);const x=Math.cos(el)*Math.sin(az)*dist,z=Math.cos(el)*Math.cos(az)*dist;camera.position.set(focus.x+x,focus.y+Math.sin(el)*dist,focus.z+z);camera.lookAt(focus);}
setInterval(()=>{if(defender.userData.radar){const now=performance.now(),t=now*.001;defender.userData.radar.rotation.y+=.04;defender.userData.sps49.rotation.y-=.025;defender.userData.fireControl.rotation.y=Math.sin(t)*.3;defender.userData.launcher.rotation.y=Math.PI+Math.sin(t*.75)*.12;defender.userData.forwardLauncher.rotation.y=-Math.sin(t*.68)*.12;for(const station of [defender.userData.launcher,defender.userData.forwardLauncher]){const sinceLaunch=now-(station.userData.lastLaunch??-10000),kick=sinceLaunch<900?Math.sin(Math.min(1,sinceLaunch/900)*Math.PI)*.32:0;station.userData.arms?.forEach((arm:THREE.Group,index:number)=>arm.rotation.z=.12+Math.sin(t*.9+index*.4)*.05+kick);}defender.userData.directors?.forEach((director:THREE.Group,index:number)=>director.rotation.y+=(index?-.003:.003));}},50);
function updateCiws(){if(!ciwsEnabled||ciwsRounds<=0||elapsed-lastCiwsShot<.55)return;const candidates=missiles.filter(m=>m.phase!=='destroyed'&&m.mesh.position.distanceTo(defender.position)<15).sort((a,b)=>a.mesh.position.distanceTo(defender.position)-b.mesh.position.distanceTo(defender.position));const target=candidates[0];if(!target)return;lastCiwsShot=elapsed;ciwsRounds=Math.max(0,ciwsRounds-60);ciwsTracer(target.mesh.position);const saturation=Math.max(1,candidates.length),basePk=Math.max(.08,.46/saturation)-(target.kind==='P-500'?.1:target.kind==='P-700'?.16:.3),pk=target.kind==='Kh-22'?Math.min(.14,basePk):Math.max(.08,basePk),roll=Math.abs(Math.sin(elapsed*31.7+ciwsRounds*.013));if(roll<pk){target.phase='destroyed';target.mesh.visible=false;destroyMissileVisual(target,'intercept');log(`CIWS KILL / PK ${Math.round(pk*100)}% / ${ciwsRounds} ROUNDS`);}else log(`CIWS MISS / PK ${Math.round(pk*100)}% / ${ciwsRounds} ROUNDS`);}
setInterval(()=>interceptors.forEach(i=>{if(i.mesh.userData.seeker)i.mesh.userData.seeker.visible=i.weapon==='RIM-67'&&i.mesh.visible&&i.target.phase!=='destroyed'&&i.mesh.position.distanceTo(i.target.mesh.position)<weaponProfiles[i.weapon].terminalRange;}),50);
setInterval(()=>{const live=missiles.filter(m=>m.phase!=='destroyed').length,engagedTargets=new Set(interceptors.filter(i=>i.mesh.visible).map(i=>i.target)).size;targetState.textContent=live>0?`${live} THREATS / ${engagedTargets} ENGAGED`:'AIRSPACE CLEAR';},120);
setInterval(()=>{if(missiles[selectedTargetId-1]?.phase==='destroyed'){const next=missiles.findIndex(m=>m.phase!=='destroyed');if(next>=0){selectedTargetId=next+1;targetButton.textContent=`TARGET: ${selectedTargetId}`;}}missiles.forEach((m,i)=>m.mesh.userData.selection.visible=i+1===selectedTargetId&&m.phase!=='destroyed'&&combatPicture.tracks.has(i+1));},120);
setInterval(()=>{explosions.forEach(e=>{e.age+=.05;e.core.scale.setScalar(1+e.age*3.4);e.ring.scale.setScalar(1+e.age*5.8);e.ring.quaternion.copy(camera.quaternion);(e.core.material as THREE.MeshBasicMaterial).opacity=Math.max(0,.92-e.age/1.45);(e.ring.material as THREE.MeshBasicMaterial).opacity=Math.max(0,.78-e.age/1.15);e.light.intensity=Math.max(0,18-e.age*14);if(e.age>1.5){e.core.visible=false;e.ring.visible=false;e.light.visible=false;}});},50);
setInterval(()=>{if(!radarCtx)return; const w=radarCanvas.width,h=radarCanvas.height,cx=w/2,cy=h/2; radarCtx.clearRect(0,0,w,h); radarCtx.fillStyle='#061923'; radarCtx.fillRect(0,0,w,h); radarCtx.strokeStyle='#2d7f83'; radarCtx.globalAlpha=.65; for(const r of [35,70,105]){radarCtx.beginPath();radarCtx.arc(cx,cy,r,0,Math.PI*2);radarCtx.stroke();} radarCtx.setLineDash([4,4]);for(const [weapon,color] of [['SM-2MR','#d7aa55'],['RIM-67','#65cfd0']] as const){radarCtx.strokeStyle=color;radarCtx.globalAlpha=weapon===selectedWeapon?.72:.32;radarCtx.beginPath();radarCtx.arc(cx,cy,weaponProfiles[weapon].maxRange*RADAR_PIXELS_PER_WORLD_UNIT,0,Math.PI*2);radarCtx.stroke();}radarCtx.setLineDash([]);radarCtx.beginPath();radarCtx.moveTo(cx,cy);radarCtx.lineTo(cx+Math.cos(elapsed*.8)*110,cy+Math.sin(elapsed*.8)*110);radarCtx.strokeStyle='#78e1c8';radarCtx.globalAlpha=.65;radarCtx.stroke();radarCtx.globalAlpha=1;radarCtx.fillStyle='#78e1c8';radarCtx.fillRect(cx-3,cy-3,6,6);for(const track of combatPicture.tracks.values()){const missile=missiles[track.id-1];if(!missile||missile.phase==='destroyed')continue;const x=cx+(track.position.x-defender.position.x)*RADAR_PIXELS_PER_WORLD_UNIT,y=cy+(track.position.z-defender.position.z)*RADAR_PIXELS_PER_WORLD_UNIT,color=track.quality>.7?'#ff5148':track.quality>.25?'#ffb347':'#bd78ff',uncertainty=Math.max(2,track.uncertainty/100*RADAR_PIXELS_PER_WORLD_UNIT);radarCtx.strokeStyle=color;radarCtx.globalAlpha=.28;radarCtx.beginPath();radarCtx.arc(x,y,uncertainty,0,Math.PI*2);radarCtx.stroke();radarCtx.globalAlpha=.95;radarCtx.beginPath();radarCtx.moveTo(x-5,y);radarCtx.lineTo(x+5,y);radarCtx.moveTo(x,y-5);radarCtx.lineTo(x,y+5);radarCtx.stroke();if(lastTrackClasses.get(track.id)!==track.classification){lastTrackClasses.set(track.id,track.classification);log(`TRACK ${track.id} ${track.classification.toUpperCase()} · UNCERTAINTY ${(track.uncertainty/1000).toFixed(1)} km`);}}radarCtx.globalAlpha=1;interceptors.forEach(i=>{if(!i.mesh.visible)return; const x=cx+(i.mesh.position.x-defender.position.x)*RADAR_PIXELS_PER_WORLD_UNIT,y=cy+(i.mesh.position.z-defender.position.z)*RADAR_PIXELS_PER_WORLD_UNIT; radarCtx.fillStyle='#a4ecff';radarCtx.beginPath();radarCtx.arc(x,y,3,0,Math.PI*2);radarCtx.fill();});},100);
function updateCombat(dt:number){
 updateCiws();
 updateBoosterDebris(dt);
 combatPicture.update(elapsed,dt,radarEnabled?missiles.map((m,i)=>({m,i})).filter(x=>elapsed>=x.m.launchAt&&x.m.phase!=='destroyed').map(x=>({id:x.i+1,position:x.m.mesh.position,velocity:x.m.velocity,altitude:x.m.mesh.position.y*50,rcs:x.m.rcs})):[],1,defender.position);
 const activeInterceptors=interceptors.filter(i=>i.mesh.visible),active=activeInterceptors.length,assignments=new Map<Missile,number>();activeInterceptors.forEach(i=>assignments.set(i.target,(assignments.get(i.target)??0)+1));const best=[...combatPicture.tracks.values()].filter(t=>{const missile=missiles[t.id-1];return missile&&missile.phase!=='destroyed'&&t.quality>=.24&&t.age<2.2&&(assignments.get(missile)??0)<defensiveShotRequirement(missile,t.quality);}).sort((a,b)=>missileThreatScore(missiles[b.id-1],b.quality)-missileThreatScore(missiles[a.id-1],a.quality))[0];
 const terminalSm2=activeInterceptors.filter(i=>i.weapon==='SM-2MR'&&i.target.phase!=='destroyed'&&i.mesh.position.distanceTo(i.target.mesh.position)<weaponProfiles[i.weapon].terminalRange).sort((a,b)=>a.mesh.position.distanceTo(a.target.mesh.position)-b.mesh.position.distanceTo(b.target.mesh.position));
 const illuminated=new Set(terminalSm2.slice(0,maxIlluminators));
 activeInterceptors.forEach(i=>{i.illuminated=illuminated.has(i);i.illuminationBeam.visible=i.illuminated;if(i.illuminated){i.illuminationBeam.geometry.dispose();i.illuminationBeam.geometry=new THREE.BufferGeometry().setFromPoints([defender.position.clone().add(new THREE.Vector3(8,13,0)),i.target.mesh.position.clone()]);}});
 interceptors.filter(i=>!i.mesh.visible).forEach(i=>i.illuminationBeam.visible=false);
 updateShipStatus();
 const selected=missiles[selectedTargetId-1],selectedTrack=combatPicture.tracks.get(selectedTargetId);if(selected&&selected.phase!=='destroyed'){const range=selected.mesh.position.distanceTo(defender.position),profile=weaponProfiles[selectedWeapon],inRange=range>=profile.minRange&&range<=profile.maxRange;threatName.textContent=`TRACK ${String(selectedTargetId).padStart(2,'0')} / ${selectedTrack?.classification==='classified'?selected.kind:selectedTrack?.classification.toUpperCase()??'PENDING ID'}`;threatRange.textContent=`${(range/10).toFixed(1)} km`;threatAltitude.textContent=`${Math.round(selected.mesh.position.y*50)} m`;trackQuality.textContent=selectedTrack?`${Math.round(selectedTrack.quality*100)}% ${selectedTrack.classification.toUpperCase()}`:'NO DATA';threatTti.textContent=`${Math.max(0,Math.round(range/Math.max(1,selected.velocity.length())))} s`;qualityFill.style.width=`${Math.round((selectedTrack?.quality??0)*100)}%`;weaponEnvelope.textContent=`${selectedWeapon} / ${inRange?'IN RANGE':'OUT OF ENVELOPE'}`;weaponEnvelope.className=inRange?'in-range':'out-range';}
 if(running&&autoFire&&elapsed>2&&elapsed>=nextSamLaunch&&(ammo>0||sm2Ammo>0)&&active<maxSamChannels&&best){const target=missiles[best.id-1],range=target.mesh.position.distanceTo(defender.position),rim=weaponProfiles['RIM-67'],sm2=weaponProfiles['SM-2MR'],rimOk=ammo>0&&range>=rim.minRange&&range<=rim.maxRange,sm2Ok=sm2Ammo>0&&range>=sm2.minRange&&range<=sm2.maxRange;if(rimOk||sm2Ok){selectedWeapon=sm2Ok&&range<sm2.maxRange*.8?'SM-2MR':'RIM-67';launchInterceptor(target);nextSamLaunch=elapsed+.12;if(selectedWeapon==='RIM-67')ammo--;else sm2Ammo--;weaponButton.textContent=`WEAPON: ${selectedWeapon}`;ammoEl.textContent=`RIM ${ammo} / SM2 ${sm2Ammo}`;}}
 interceptors.forEach(i=>{
  if(!i.mesh.visible)return;if(i.target.phase==='destroyed'){i.mesh.visible=false;i.illuminationBeam.visible=false;return;}
  const profile=weaponProfiles[i.weapon];i.age+=dt;if(i.age>=profile.boost)separateBooster(i);const range=i.mesh.position.distanceTo(i.target.mesh.position),speed=Math.max(1,i.velocity.length()),expectedInterceptorSpeed=Math.max(speed,profile.maxSpeed*.58),timeToGo=Math.min(4,range/(expectedInterceptorSpeed+i.target.velocity.length())),terminal=range<profile.terminalRange,trackId=missiles.indexOf(i.target)+1;i.commandPoint.addScaledVector(i.commandVelocity,dt);
  if(!terminal&&elapsed>=i.nextDatalink){const track=combatPicture.tracks.get(trackId);if(track&&track.age<2.2&&track.quality>.08){const delay=.2+(1-track.quality)*.85,solution=track.position.clone().addScaledVector(track.velocity,delay+timeToGo*.65);i.commandPoint.lerp(solution,.68);i.commandVelocity.lerp(track.velocity,.6);i.datalinkValid=true;i.nextDatalink=elapsed+.38+(1-track.quality)*1.05;}else{i.datalinkValid=false;i.nextDatalink=elapsed+.55;}}
  const terminalHoming=terminal&&(i.weapon==='RIM-67'||i.illuminated),aim=terminalHoming?i.target.mesh.position.clone().addScaledVector(i.target.velocity,timeToGo*.8):i.commandPoint.clone();
  if(i.age<profile.boost){const estimatedLaunchRange=Math.min(profile.maxRange,range+i.distanceTraveled),loftFactor=THREE.MathUtils.clamp((estimatedLaunchRange-profile.terminalRange)/(profile.maxRange-profile.terminalRange),0,1);aim.y=Math.max(aim.y,20+loftFactor*28);}else if(!terminal)aim.y+=Math.min(34,range*.16);
  const desired=aim.sub(i.mesh.position).normalize(),current=i.velocity.clone().normalize(),angle=current.angleTo(desired),turnLimit=profile.turnRate*dt*(terminal?2.2:i.age<profile.boost?.62:1),blend=angle>0?Math.min(1,turnLimit/angle):1,direction=current.lerp(desired,blend).normalize(),rangeFraction=Math.min(1,i.distanceTraveled/profile.maxRange),commandedSpeed=profile.maxSpeed*(1-rangeFraction*.1),nextSpeed=Math.min(commandedSpeed,speed+profile.acceleration*dt),previousPosition=i.mesh.position.clone();i.velocity.copy(direction.multiplyScalar(nextSpeed));i.mesh.position.addScaledVector(i.velocity,dt);i.distanceTraveled+=nextSpeed*dt;i.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),direction);const closestPoint=new THREE.Vector3();new THREE.Line3(previousPosition,i.mesh.position).closestPointToPoint(i.target.mesh.position,true,closestPoint);const postRange=i.mesh.position.distanceTo(i.target.mesh.position),interceptDistance=Math.min(range,postRange,closestPoint.distanceTo(i.target.mesh.position));
  if(i.history[i.history.length-1].distanceTo(i.mesh.position)>2.2){i.history.push(i.mesh.position.clone());if(i.history.length>140)i.history.shift();i.guidancePath.geometry.dispose();i.guidancePath.geometry=new THREE.BufferGeometry().setFromPoints(i.history);}
  const needsIllumination=i.weapon==='SM-2MR'&&terminal; phaseEl.textContent=i.age<profile.boost?'BOOST / LOFT CLIMB':needsIllumination?(i.illuminated?'TERMINAL / SPG-55 ILLUMINATION':'TERMINAL / COASTING WITHOUT ILLUMINATION'):terminal?'TERMINAL / ACTIVE SEEKER':i.datalinkValid?'MIDCOURSE / DATALINK UPDATE':'MIDCOURSE / INERTIAL COAST';
  if(interceptDistance<2.5){const id=missiles.indexOf(i.target)+1,trackQualityValue=combatPicture.tracks.get(id)?.quality??.1,guidanceQuality=i.weapon==='RIM-67'?Math.max(.62,trackQualityValue):i.illuminated?Math.max(.55,trackQualityValue):trackQualityValue,saturation=missiles.filter(m=>m.phase!=='destroyed'&&m.mesh.position.distanceTo(i.target.mesh.position)<35).length,illuminationPenalty=needsIllumination&&!i.illuminated?.34:0;const pk=Math.max(.08,Math.min(.88,.48+guidanceQuality*.42-saturation*.07+(i.weapon==='SM-2MR'?.06:0)-illuminationPenalty));const roll=Math.abs(Math.sin(id*97.13+(ammo+sm2Ammo)*17.7+i.age*3.17));i.mesh.visible=false;i.illuminationBeam.visible=false;if(roll<pk){i.target.phase='destroyed';i.target.mesh.visible=false;destroyMissileVisual(i.target,'intercept');phaseEl.textContent='TERMINAL INTERCEPT';log(`${i.weapon} INTERCEPT / ${(i.distanceTraveled/WORLD_UNITS_PER_KM).toFixed(1)} km / PK ${(pk*100).toFixed(0)}%${needsIllumination?' / ILLUMINATED':''}`);}else{log(`${i.weapon} MISS / PK ${(pk*100).toFixed(0)}%${illuminationPenalty?' / NO ILLUMINATOR':''}`);}return;}
  if(terminal){const closestEver=Math.min(i.mesh.userData.closestApproach??Infinity,interceptDistance),previousRange=i.mesh.userData.previousTargetRange??Infinity;i.mesh.userData.closestApproach=closestEver;i.mesh.userData.previousTargetRange=postRange;if(postRange>previousRange+.15&&closestEver<8){i.mesh.visible=false;i.illuminationBeam.visible=false;log(`${i.weapon} MISS / CPA ${(closestEver/WORLD_UNITS_PER_KM).toFixed(2)} km`);return;}}
  if(i.distanceTraveled>profile.maxRange){i.mesh.visible=false;i.illuminationBeam.visible=false;log(`${i.weapon} MISS / RANGE EXHAUSTED ${(i.distanceTraveled/WORLD_UNITS_PER_KM).toFixed(1)} km`);return;}
 });
 if(!missionEnded&&missiles.length>0&&missiles.every(m=>m.phase==='destroyed')&&hullIntegrity>0){interceptors.forEach(i=>{i.mesh.visible=false;i.illuminationBeam.visible=false;});updateShipStatus();finishMission(true);}
}
function updateIncomingMissile(m:Missile,dt:number){
 if(m.phase==='destroyed')return;if(elapsed<m.launchAt){m.mesh.visible=false;m.path.visible=false;return;}m.mesh.visible=true;m.path.visible=true;
 m.age+=dt;
 const range=m.mesh.position.distanceTo(defender.position),profile=incomingProfiles[m.kind],terminalFactor=THREE.MathUtils.clamp((profile.terminalAt-range)/(profile.terminalAt*.72),0,1);m.phase=range<profile.terminalAt?'terminal':range<profile.terminalAt*1.9?'midcourse':'inbound';
 const commandedAltitude=THREE.MathUtils.lerp(profile.cruiseAltitude,profile.terminalAltitude,terminalFactor);
 const aimPoint=defender.position.clone().add(m.aimOffset).add(new THREE.Vector3(0,commandedAltitude,0));
 const desired=aimPoint.sub(m.mesh.position).normalize();
 const current=m.velocity.clone().normalize();
 const turnSign=current.clone().cross(desired).y;
 const angle=current.angleTo(desired),maxTurn=THREE.MathUtils.degToRad(profile.turnRate*(1+terminalFactor*.75))*dt;
 const blend=angle>0?Math.min(1,maxTurn/angle):1;
 const direction=current.lerp(desired,blend).normalize();
 const targetSpeed=THREE.MathUtils.lerp(profile.cruiseSpeed,profile.terminalSpeed,terminalFactor);
 const speed=THREE.MathUtils.lerp(m.velocity.length(),targetSpeed,Math.min(1,dt*.55));
 m.velocity.copy(direction.multiplyScalar(speed));
 m.mesh.position.addScaledVector(m.velocity,dt);
 m.bank=THREE.MathUtils.lerp(m.bank,THREE.MathUtils.clamp(turnSign*8,-.62,.62),Math.min(1,dt*2.4));
 m.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),m.velocity.clone().normalize());
 m.mesh.rotateZ(m.bank);
 if(m.mesh.userData.seaMist)m.mesh.userData.seaMist.visible=m.kind!=='Kh-22'&&m.phase==='terminal'&&m.mesh.position.y<1.25;
 if(m.mesh.userData.shockCone)m.mesh.userData.shockCone.visible=m.kind==='Kh-22'&&m.phase==='terminal';
 if(m.history.length===0||m.mesh.position.distanceTo(m.history[m.history.length-1])>3){m.history.push(m.mesh.position.clone());if(m.history.length>90)m.history.shift();m.path.geometry.dispose();m.path.geometry=new THREE.BufferGeometry().setFromPoints(m.history);}
 if(range<6){const nearestSam=interceptors.filter(i=>i.mesh.visible).reduce((best,i)=>Math.min(best,i.mesh.position.distanceTo(m.mesh.position)),Infinity);m.phase='destroyed';m.mesh.visible=false;leakers++;hullIntegrity=Math.max(0,hullIntegrity-profile.damage);createShipDamage(m.mesh.position,profile.damage);destroyMissileVisual(m,'impact');log(`${m.kind} IMPACT / ${profile.damage}% DAMAGE / SAM ${Number.isFinite(nearestSam)?(nearestSam/WORLD_UNITS_PER_KM).toFixed(1)+' km':'NONE'} / HULL ${hullIntegrity}%`);updateShipStatus();if(hullIntegrity<=0){phaseEl.textContent='USS LONG BEACH DISABLED';finishMission(false);}}
}
function updateTargetMarker(){const selected=missiles[selectedTargetId-1],track=combatPicture.tracks.get(selectedTargetId);if(!selected||selected.phase==='destroyed'||elapsed<selected.launchAt||!track){targetMarker.style.display='none';return;}const projected=track.position.clone().project(camera),behind=projected.z<-1||projected.z>1,rawX=(projected.x*.5+.5)*innerWidth,rawY=(-projected.y*.5+.5)*innerHeight,margin=innerWidth<560?28:46,safeTop=innerWidth<560?250:76,safeBottom=innerWidth<560?220:110,centerX=innerWidth*.5,centerY=innerHeight*.5,angle=Math.atan2(rawY-centerY,rawX-centerX),displayX=behind?centerX+Math.cos(angle+Math.PI)*innerWidth:centerX+Math.cos(angle)*innerWidth,displayY=behind?centerY+Math.sin(angle+Math.PI)*innerHeight:centerY+Math.sin(angle)*innerHeight,x=Math.max(margin,Math.min(innerWidth-margin,behind?displayX:rawX)),y=Math.max(safeTop,Math.min(innerHeight-safeBottom,behind?displayY:rawY)),offscreen=behind||rawX<margin||rawX>innerWidth-margin||rawY<safeTop||rawY>innerHeight-safeBottom,range=track.position.distanceTo(defender.position),tti=Math.max(0,Math.round(range/Math.max(1,track.velocity.length())));targetMarker.style.display='block';targetMarker.style.left=`${x}px`;targetMarker.style.top=`${y}px`;targetMarker.style.setProperty('--bearing',`${Math.atan2((behind?displayY:rawY)-centerY,(behind?displayX:rawX)-centerX)}rad`);targetMarker.classList.toggle('offscreen',offscreen);targetMarker.classList.toggle('right-edge',x>innerWidth-180);targetMarkerLabel.textContent=`T${String(selectedTargetId).padStart(2,'0')} ${track.classification==='classified'?selected.kind:track.classification.toUpperCase()} / ${tti}s / ±${(track.uncertainty/1000).toFixed(1)}km`;}
function tick(now:number){
 const realDt=Math.min((now-last)/1000,.1);last=now;
 if(running){simAccumulator+=realDt*timeScale;while(simAccumulator>=.05&&running){elapsed+=.05;updateCombat(.05);missiles.forEach(m=>updateIncomingMissile(m,.05));simAccumulator-=.05;}const activeMissiles=missiles.filter(m=>m.phase!=='destroyed'&&elapsed>=m.launchAt),live=activeMissiles.length,distances=activeMissiles.map(m=>m.mesh.position.distanceTo(defender.position));document.querySelector('#targetCount')!.textContent=`${live} ACTIVE / ${missiles.filter(m=>m.phase!=='destroyed').length-live} RESERVE / ${distances.length?(Math.max(...distances)/10).toFixed(1):'0.0'} km`;}
 for(let i=0;i<seaPositions.count;i++){const p=i*3,x=seaBase[p],y=seaBase[p+1];seaPositions.setZ(i,Math.sin(x*.026+elapsed*.72)*.48+Math.sin(y*.019-elapsed*.54)*.34+Math.sin((x+y)*.011+elapsed*.31)*.2);}seaPositions.needsUpdate=true;if(++waveFrame%8===0)seaGeometry.computeVertexNormals();
 missiles.forEach((m,index)=>{if(!m.mesh.visible)return;const pulse=.88+Math.sin(elapsed*19+index*1.7)*.12;(m.mesh.userData.exhaust as THREE.Mesh|undefined)?.scale.set(1,pulse,1);(m.mesh.userData.hotCore as THREE.Mesh|undefined)?.scale.setScalar(.9+pulse*.12);(m.mesh.userData.seaMist as THREE.Mesh|undefined)?.scale.set(1+pulse*.12,1+pulse*.28,1+pulse*.12);const shock=m.mesh.userData.shockCone as THREE.Mesh|undefined;if(shock)(shock.material as THREE.MeshBasicMaterial).opacity=.09+pulse*.035;});
 clockEl.textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`;updateCamera();if(defender.userData.highDetail)defender.userData.highDetail.visible=camera.position.distanceTo(defender.position)<270;defender.userData.smokePuffs?.forEach((puff:THREE.Mesh,index:number)=>{const life=(elapsed*.22+index/9)%1;puff.position.set(-4-life*7,15+life*11,Math.sin(index*2.1+life*4)*.8);puff.scale.setScalar(.55+life*2.1);(puff.material as THREE.MeshBasicMaterial).opacity=.13*(1-life);});shipDamageEffects.forEach(effect=>{effect.fire.scale.setScalar(.8+Math.sin(elapsed*13+effect.seed)*.22);effect.light.intensity=3.5+Math.sin(elapsed*17+effect.seed)*1.5;effect.smoke.forEach((puff,index)=>{const life=(elapsed*.28+index/effect.smoke.length+effect.seed)%1;puff.position.set(-life*2,1+life*9,Math.sin(effect.seed+index*1.7)*.7);puff.scale.setScalar(.5+life*2.4);(puff.material as THREE.MeshBasicMaterial).opacity=.32*(1-life);});});updateTargetMarker();renderer.render(scene,camera);requestAnimationFrame(tick);
}
requestAnimationFrame(tick);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
canvas.addEventListener('pointerdown',e=>{dragging=true;px=e.clientX;py=e.clientY}); addEventListener('pointerup',()=>dragging=false); addEventListener('pointermove',e=>{if(!dragging)return;az-=(e.clientX-px)*.006;el=Math.max(.15,Math.min(1.2,el+(e.clientY-py)*.005));px=e.clientX;py=e.clientY}); canvas.addEventListener('wheel',e=>{dist=Math.max(70,Math.min(360,dist+e.deltaY*.12))}); addEventListener('keydown',e=>{if(e.code==='Space')running=!running;if(e.key.toLowerCase()==='r')location.reload()});
addEventListener('keydown',e=>{if(e.key==='1'){cinematic=false;viewMode=1;az=.8;el=.32;dist=125;}if(e.key==='2'){cinematic=false;viewMode=2;az=.65;el=.48;dist=210;}if(e.key==='3'){cinematic=false;viewMode=3;az=.15;el=.25;dist=260;}if(e.key.toLowerCase()==='c')cinematic=!cinematic;});
