import * as THREE from 'three';
import type { SensorDefinition } from './sim';
import type { FixedSensorFaceConfig } from './sensor-faces';

export type ShipClass=string;
export type LauncherKind='mk10'|'mk41';
export type ShipWeapon='RIM-67'|'SM-2MR'|'SM-2ER';
export type SubsystemId='sps48'|'sps49'|'spg55'|'mk10Aft'|'mk10Forward'|'ciws'|'ecm'|'srboc'|'propulsion';

export type LauncherConfig=
 | {kind:'mk10';displayName:string;compatibleWeapons:ShipWeapon[];azimuthRateDeg:number;elevationRateDeg:number;reloadSeconds:number}
 | {kind:'mk41';displayName:string;compatibleWeapons:ShipWeapon[];columns:number;sequenceInterval:number;exhaustClearance:number;isolationStartsAt:number;maximumIsolationFraction:number;loadingPermutation:number;gridSize:number};

export interface ShipDefinition {
 id:ShipClass;
 name:string;
 hullNumber:string;
 era:string;
 role:string;
 launcher:LauncherConfig;
 readonly launcherKind:LauncherKind;
 sensors:SensorDefinition[];
 fixedSensorFaces?:FixedSensorFaceConfig;
 subsystemLabels:Record<SubsystemId,string>;
 subsystemPositions:Record<SubsystemId,THREE.Vector3>;
 ammo:{rim67:number;sm2mr:number;sm2er:number;ciws:number;channels:number;illuminators:number};
 hullColor:number;
 build:()=>THREE.Group;
}

function slopedBox(length:number,height:number,depth:number,foreSlope:number,aftSlope=0){const geometry=new THREE.BoxGeometry(length,height,depth),position=geometry.attributes.position as THREE.BufferAttribute;for(let i=0;i<position.count;i++){const x=position.getX(i),y=position.getY(i);if(y>0&&x>0)position.setX(i,x-foreSlope);if(y>0&&x<0)position.setX(i,x+aftSlope);}position.needsUpdate=true;geometry.computeVertexNormals();return geometry;}
function strut(group:THREE.Group,a:THREE.Vector3,b:THREE.Vector3,radius:number,material:THREE.Material){const delta=b.clone().sub(a),mesh=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,delta.length(),6),material);mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());group.add(mesh);return mesh;}
function hullGeometry(){const sections=[[-34,2.05],[-32,3.05],[-25,3.55],[-8,3.75],[13,3.72],[24,3.35],[29,2.55],[32.5,1.2],[34,.1]] as const,vertices:number[]=[],indices:number[]=[];for(const [x,w] of sections)vertices.push(x,5.8,-w,x,5.8,w,x,.25,-w*.58,x,.25,w*.58);for(let i=0;i<sections.length-1;i++){const a=i*4,b=a+4;indices.push(a,a+1,b+1,a,b+1,b,a+2,b+2,b+3,a+2,b+3,a+3,a,a+2,b+2,a,b+2,b,a+1,b+1,b+3,a+1,b+3,a+3);}indices.push(0,4,5,0,5,1,(sections.length-1)*4,(sections.length-1)*4+1,(sections.length-1)*4+3,(sections.length-1)*4,(sections.length-1)*4+3,(sections.length-1)*4+2);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;}
function hullNumberTexture(){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=96;const context=canvas.getContext('2d')!;context.fillStyle='#f3f4ee';context.font='700 58px Arial';context.textAlign='center';context.textBaseline='middle';context.fillText('57',128,51);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
function flagTexture(){const canvas=document.createElement('canvas');canvas.width=247;canvas.height=130;const context=canvas.getContext('2d')!;for(let row=0;row<13;row++){context.fillStyle=row%2?'#f4f3ed':'#b22234';context.fillRect(0,row*10,247,10);}context.fillStyle='#3c3b6e';context.fillRect(0,0,99,70);context.fillStyle='#fff';for(let y=0;y<5;y++)for(let x=0;x<6;x++){context.beginPath();context.arc(9+x*16+(y%2)*8,8+y*14,1.8,0,Math.PI*2);context.fill();}const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
function gun(material:THREE.Material,dark:THREE.Material){const group=new THREE.Group(),base=new THREE.Mesh(new THREE.CylinderGeometry(1.45,1.75,.65,12),dark),turret=new THREE.Mesh(slopedBox(2.9,1.6,2.5,.65,.25),material),barrel=new THREE.Mesh(new THREE.CylinderGeometry(.13,.2,5.2,8),dark);base.position.y=.3;turret.position.set(.15,1.15,0);barrel.rotation.z=Math.PI/2;barrel.position.set(3.1,1.55,0);group.add(base,turret,barrel);return group;}
function ciws(material:THREE.Material,dark:THREE.Material,name:string){const group=new THREE.Group();group.name=name;const base=new THREE.Mesh(new THREE.CylinderGeometry(.7,.95,.7,12),dark),turret=new THREE.Mesh(new THREE.BoxGeometry(1,1.05,.9),material),pivot=new THREE.Group(),radome=new THREE.Mesh(new THREE.SphereGeometry(.38,10,7),material);turret.position.y=.88;pivot.position.set(0,1.08,0);for(let n=-1;n<=1;n++){const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,2.2,6),dark);barrel.rotation.z=Math.PI/2;barrel.position.set(1.3,0,n*.11);pivot.add(barrel);}radome.position.set(-.25,1.55,0);group.add(base,turret,pivot,radome);group.userData.elevationPivot=pivot;return group;}
function director(material:THREE.Material,dark:THREE.Material,x:number,z:number,heading:number){const group=new THREE.Group();group.position.set(x,13.5,z);group.rotation.y=heading;group.userData.stowHeading=heading;const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(.58,.82,1.05,12),dark),pivot=new THREE.Group(),dish=new THREE.Mesh(new THREE.SphereGeometry(1.05,16,8,0,Math.PI*2,0,Math.PI*.46),material),back=new THREE.Mesh(new THREE.CylinderGeometry(.88,.72,.28,14),dark),feed=new THREE.Mesh(new THREE.CylinderGeometry(.055,.11,1.45,7),dark),tip=new THREE.Object3D();pivot.position.y=.65;dish.rotation.z=-Math.PI/2;dish.position.x=.74;back.rotation.z=Math.PI/2;back.position.x=.55;feed.rotation.z=Math.PI/2;feed.position.x=1.35;tip.position.x=2.1;pivot.add(back,dish,feed,tip);group.add(pedestal,pivot);group.userData.elevationPivot=pivot;group.userData.feedTip=tip;return group;}
function vlsBank(rows:number,columns:number,spacing:number,material:THREE.Material,dark:THREE.Material,omitted:number[]=[]){const group=new THREE.Group(),cells:{lid:THREE.Group;origin:THREE.Object3D;index:number}[]=[],width=(rows-1)*spacing+1.05,depth=(columns-1)*spacing+1.05,plinth=new THREE.Mesh(new THREE.BoxGeometry(width+.55,.28,depth+.55),dark);plinth.position.y=.05;group.add(plinth);for(let row=0;row<rows;row++)for(let column=0;column<columns;column++){const physicalIndex=row*columns+column,x=(row-(rows-1)/2)*spacing,z=(column-(columns-1)/2)*spacing;if(omitted.includes(physicalIndex)){const cranePlate=new THREE.Mesh(new THREE.BoxGeometry(.68,.1,.68),dark);cranePlate.position.set(x,.25,z);group.add(cranePlate);continue;}const frame=new THREE.Mesh(new THREE.BoxGeometry(.67,.1,.67),material),well=new THREE.Mesh(new THREE.BoxGeometry(.51,.04,.51),new THREE.MeshBasicMaterial({color:0x182326})),lid=new THREE.Group(),panel=new THREE.Mesh(new THREE.BoxGeometry(.53,.055,.53),material),hinge=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.5,6),dark),origin=new THREE.Object3D();frame.position.set(x,.22,z);well.position.set(x,.29,z);lid.position.set(x-.265,.34,z);panel.position.x=.265;hinge.rotation.x=Math.PI/2;hinge.position.z=-.265;origin.position.set(x,.42,z);lid.add(panel,hinge);group.add(frame,well,lid,origin);cells.push({lid,origin,index:physicalIndex});}group.userData.cells=cells;return group;}
function fixedArray(material:THREE.Material,dark:THREE.Material,position:THREE.Vector3,rotation:THREE.Euler){const group=new THREE.Group();group.position.copy(position);group.rotation.copy(rotation);const border=new THREE.Mesh(new THREE.CylinderGeometry(2.45,2.45,.14,8),dark),panelMaterial=material.clone(),panel=new THREE.Mesh(new THREE.CylinderGeometry(2.18,2.18,.18,8),panelMaterial);border.rotation.x=Math.PI/2;panel.rotation.x=Math.PI/2;panel.position.z=.09;group.add(border,panel);for(let x=-1.2;x<=1.2;x+=.6)for(let y=-1.2;y<=1.2;y+=.6){if(Math.hypot(x,y)>1.65)continue;const module=new THREE.Mesh(new THREE.CircleGeometry(.055,8),new THREE.MeshBasicMaterial({color:0xdfe3d9}));module.position.set(x,y,.2);group.add(module);}group.userData.panel=panel;return group;}

export function buildTiconderoga(){
 const ship=new THREE.Group(),hullMat=new THREE.MeshStandardMaterial({color:0x687678,metalness:.58,roughness:.42}),deckMat=new THREE.MeshStandardMaterial({color:0x5d6867,metalness:.32,roughness:.66}),superMat=new THREE.MeshStandardMaterial({color:0x8d9998,metalness:.38,roughness:.52}),dark=new THREE.MeshStandardMaterial({color:0x263235,metalness:.52,roughness:.46}),arrayMat=new THREE.MeshStandardMaterial({color:0xcbd0c8,metalness:.24,roughness:.58}),windowMat=new THREE.MeshStandardMaterial({color:0x4ca8ad,emissive:0x123f43,emissiveIntensity:1.5}),highDetail=new THREE.Group(),mediumDetail=new THREE.Group(),lowDetail=new THREE.Group();
 const hull=new THREE.Mesh(hullGeometry(),hullMat),waterline=new THREE.Mesh(hullGeometry(),new THREE.MeshStandardMaterial({color:0x151d20,roughness:.8}));waterline.scale.set(1.002,.27,1.002);waterline.position.y=-.05;ship.add(hull,waterline);
 const deckShape=new THREE.Shape();deckShape.moveTo(-33,-2);deckShape.lineTo(-30,-3.15);deckShape.lineTo(18,-3.68);deckShape.lineTo(27,-2.9);deckShape.lineTo(34,0);deckShape.lineTo(27,2.9);deckShape.lineTo(18,3.68);deckShape.lineTo(-30,3.15);deckShape.closePath();const deck=new THREE.Mesh(new THREE.ShapeGeometry(deckShape),deckMat);deck.rotation.x=-Math.PI/2;deck.position.y=5.85;ship.add(deck);
 const forwardHouse=new THREE.Mesh(slopedBox(15.5,7.8,6.35,2.8,.65),superMat);forwardHouse.position.set(5.5,9.6,0);ship.add(forwardHouse);const bridge=new THREE.Mesh(slopedBox(8.8,3.1,5.85,1.8,.45),superMat);bridge.position.set(9.4,14.85,0);ship.add(bridge);const bridgeRoof=new THREE.Mesh(slopedBox(6.4,.55,5.2,.7,.25),dark);bridgeRoof.position.set(8.4,16.65,0);ship.add(bridgeRoof);for(const side of [-1,1])for(let x=6.7;x<=11.7;x+=.82){const window=new THREE.Mesh(new THREE.BoxGeometry(.55,.42,.1),windowMat);window.position.set(x,15.25,side*2.98);ship.add(window);}for(let z=-2.15;z<=2.15;z+=.72){const window=new THREE.Mesh(new THREE.BoxGeometry(.1,.42,.48),windowMat);window.position.set(13.25,15.25,z);ship.add(window);}
 const aftHouse=new THREE.Mesh(slopedBox(14,6.8,6.35,.75,1.9),superMat);aftHouse.position.set(-7.8,9.1,0);ship.add(aftHouse);const hangar=new THREE.Mesh(slopedBox(8.2,4.2,6.25,.25,1.15),superMat);hangar.position.set(-14.3,8,0);ship.add(hangar);for(const side of [-1,1]){const door=new THREE.Mesh(new THREE.BoxGeometry(3.5,2.45,.12),dark);door.position.set(-15.2,7.8,side*3.18);ship.add(door);const catwalk=new THREE.Mesh(new THREE.BoxGeometry(12,.18,.85),dark);catwalk.position.set(-8.5,10.9,side*3.55);ship.add(catwalk);}
 const arrays:THREE.Group[]=[];arrays.push(fixedArray(arrayMat,dark,new THREE.Vector3(12.95,12.25,0),new THREE.Euler(0,Math.PI/2,0)));arrays.push(fixedArray(arrayMat,dark,new THREE.Vector3(5.8,12.25,-3.22),new THREE.Euler(0,0,0)));arrays.push(fixedArray(arrayMat,dark,new THREE.Vector3(-14.9,11.65,0),new THREE.Euler(0,-Math.PI/2,0)));arrays.push(fixedArray(arrayMat,dark,new THREE.Vector3(-8.6,11.65,3.22),new THREE.Euler(0,Math.PI,0)));ship.add(...arrays);
 for(const x of [1.2,-8.5]){const trunk=new THREE.Mesh(slopedBox(3.1,3.2,3.5,.45,.45),superMat);trunk.position.set(x,14.4,0);ship.add(trunk);for(const z of [-.72,.72]){const stack=new THREE.Mesh(new THREE.CylinderGeometry(.68,.82,2.45,10),dark);stack.position.set(x,17,z);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.74,.74,.25,10),new THREE.MeshBasicMaterial({color:0x111719}));cap.position.set(x,18.3,z);ship.add(stack,cap);}}
 const foreMast=new THREE.Group();foreMast.position.set(4.2,15,0);for(const side of [-1,1])strut(foreMast,new THREE.Vector3(-1,0,side*1.7),new THREE.Vector3(0,10,side*.45),.13,dark);strut(foreMast,new THREE.Vector3(1.2,0,0),new THREE.Vector3(0,10,0),.13,dark);for(let y=2;y<9;y+=2){const bar=new THREE.Mesh(new THREE.BoxGeometry(.14,.14,3-y*.18),dark);bar.position.y=y;foreMast.add(bar);}const platform=new THREE.Mesh(new THREE.CylinderGeometry(1.8,2.1,.25,10),dark);platform.position.y=8.5;foreMast.add(platform);const mastPole=new THREE.Mesh(new THREE.CylinderGeometry(.12,.22,8,7),dark);mastPole.position.y=13;foreMast.add(mastPole);const sps49=new THREE.Group();sps49.position.y=10.2;const radarBar=new THREE.Mesh(new THREE.BoxGeometry(7,.12,.12),arrayMat);sps49.add(radarBar);for(let x=-3;x<=3;x+=.75){const tine=new THREE.Mesh(new THREE.BoxGeometry(.04,2.1,.06),arrayMat);tine.position.x=x;sps49.add(tine);}foreMast.add(sps49);ship.add(foreMast);
 const aftMast=new THREE.Group();aftMast.position.set(-11.5,14,0);for(const side of [-1,1])strut(aftMast,new THREE.Vector3(-1,0,side*1.5),new THREE.Vector3(0,8,side*.4),.12,dark);strut(aftMast,new THREE.Vector3(1,0,0),new THREE.Vector3(0,8,0),.12,dark);const aftPole=new THREE.Mesh(new THREE.CylinderGeometry(.1,.2,6.5,7),dark);aftPole.position.y=10.5;aftMast.add(aftPole);ship.add(aftMast);
 const forwardVls=vlsBank(8,8,.72,superMat,dark,[0,1,8]);forwardVls.position.set(21.5,5.9,0);const aftVls=vlsBank(8,8,.72,superMat,dark,[55,62,63]);aftVls.position.set(-25.2,5.9,0);ship.add(forwardVls,aftVls);const vlsCells=[...(forwardVls.userData.cells as any[]).map(cell=>({...cell,bank:'FWD'})),...(aftVls.userData.cells as any[]).map(cell=>({...cell,bank:'AFT'}))];
 const foreGun=gun(superMat,dark);foreGun.position.set(29.2,6.15,0);const aftGun=gun(superMat,dark);aftGun.position.set(-31,6.15,0);aftGun.rotation.y=Math.PI;ship.add(foreGun,aftGun);
 const directors=[director(arrayMat,dark,10,-3.7,-.25),director(arrayMat,dark,10,3.7,.25),director(arrayMat,dark,-10.8,-3.7,Math.PI+.3),director(arrayMat,dark,-10.8,3.7,Math.PI-.3)];ship.add(...directors);const foreCiws=ciws(superMat,dark,'ciwsFore');foreCiws.position.set(13.5,9.3,0);const aftCiws=ciws(superMat,dark,'ciwsAft');aftCiws.position.set(-15.5,10.2,-3.55);aftCiws.rotation.y=Math.PI;ship.add(foreCiws,aftCiws);
 const flightDeck=new THREE.Mesh(new THREE.BoxGeometry(7.8,.14,6.35),deckMat);flightDeck.position.set(-19.2,6.05,0);ship.add(flightDeck);const marking=new THREE.Mesh(new THREE.RingGeometry(2.05,2.18,48),new THREE.MeshBasicMaterial({color:0xe8e4cb,side:THREE.DoubleSide}));marking.rotation.x=-Math.PI/2;marking.position.set(-19.2,6.14,0);highDetail.add(marking);for(const side of [-1,1]){const line=new THREE.Mesh(new THREE.BoxGeometry(7.2,.025,.08),new THREE.MeshBasicMaterial({color:0xe8e4cb}));line.position.set(-19.2,6.15,side*2.75);highDetail.add(line);}
 for(const side of [-1,1])for(let x=-28;x<=28;x+=2.5){const post=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,.65,5),dark);post.position.set(x,6.45,side*(x>20?3.2:x<-25?3.2:4.18));highDetail.add(post);}for(const side of [-1,1])for(const x of [-2,-6,-10]){const boat=new THREE.Mesh(new THREE.CapsuleGeometry(.42,2.5,4,9),new THREE.MeshStandardMaterial({color:0xe1d9c8,roughness:.66}));boat.rotation.z=Math.PI/2;boat.position.set(x,9.1,side*4.05);highDetail.add(boat);}
 for(const side of [-1,1])for(const x of [-15,-4,7,15]){const canister=new THREE.Mesh(new THREE.BoxGeometry(2.8,.7,.72),dark);canister.position.set(x,8.2,side*4);highDetail.add(canister);}const smokePuffs:THREE.Mesh[]=[],smokeOrigins=[new THREE.Vector3(1.2,18.3,-.72),new THREE.Vector3(1.2,18.3,.72),new THREE.Vector3(-8.5,18.3,-.72),new THREE.Vector3(-8.5,18.3,.72)];for(let n=0;n<12;n++){const anchor=new THREE.Group(),origin=smokeOrigins[n%smokeOrigins.length],puff=new THREE.Mesh(new THREE.SphereGeometry(.65,7,5),new THREE.MeshBasicMaterial({color:0x526064,transparent:true,opacity:.12,depthWrite:false}));anchor.position.copy(origin).sub(new THREE.Vector3(-4,15,0));anchor.add(puff);smokePuffs.push(puff);highDetail.add(anchor);}const flagGeometry=new THREE.PlaneGeometry(3,1.6,10,3);flagGeometry.translate(-1.5,0,0);const flag=new THREE.Mesh(flagGeometry,new THREE.MeshStandardMaterial({map:flagTexture(),side:THREE.DoubleSide}));flag.position.set(-11.5,25,0);highDetail.add(flag);ship.add(highDetail);
 for(const side of [-1,1]){const rail=new THREE.Mesh(new THREE.BoxGeometry(48,.07,.07),new THREE.MeshBasicMaterial({color:0x82908d}));rail.position.set(-1,6.65,side*4.15);mediumDetail.add(rail);}ship.add(mediumDetail);const lowHull=new THREE.Mesh(new THREE.BoxGeometry(28,5,7),superMat);lowHull.position.set(-1,9,0);const lowMast=new THREE.Mesh(new THREE.CylinderGeometry(.18,.35,15,6),dark);lowMast.position.set(2,19,0);lowDetail.add(lowHull,lowMast);lowDetail.visible=false;ship.add(lowDetail);
 const numberMaterial=new THREE.MeshBasicMaterial({map:hullNumberTexture(),transparent:true,side:THREE.DoubleSide});for(const side of [-1,1]){const number=new THREE.Mesh(new THREE.PlaneGeometry(3.4,1.35),numberMaterial);number.position.set(23,3.6,side*3.78);number.rotation.y=side>0?0:Math.PI;ship.add(number);}
 const navigationLights:THREE.PointLight[]=[],lightBulbs:THREE.Mesh[]=[];for(const side of [-1,1]){const color=side>0?0x42ff74:0xff493e,light=new THREE.PointLight(color,3,18),bulb=new THREE.Mesh(new THREE.SphereGeometry(.14,8,6),new THREE.MeshBasicMaterial({color}));light.position.set(10.5,17,side*3.7);bulb.position.copy(light.position);navigationLights.push(light);lightBulbs.push(bulb);ship.add(light,bulb);}const mastLight=new THREE.PointLight(0xf5fff0,2.5,24),mastBulb=new THREE.Mesh(new THREE.SphereGeometry(.14,8,6),new THREE.MeshBasicMaterial({color:0xf5fff0}));mastLight.position.set(4.2,31,0);mastBulb.position.copy(mastLight.position);navigationLights.push(mastLight);lightBulbs.push(mastBulb);ship.add(mastLight,mastBulb);
 const radar=new THREE.Group();radar.userData.static=true;const searchBeam=new THREE.Mesh(new THREE.RingGeometry(25,105,64,1,0,Math.PI*.13),new THREE.MeshBasicMaterial({color:0x5ee9df,transparent:true,opacity:.025,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}));searchBeam.rotation.x=-Math.PI/2;searchBeam.position.set(4,18,0);radar.add(searchBeam);radar.userData.searchBeam=searchBeam;ship.add(radar);const fireControl=new THREE.Group();fireControl.userData.static=true;ship.add(fireControl);
 const ewPulse=new THREE.Group();for(let n=0;n<3;n++){const ring=new THREE.Mesh(new THREE.TorusGeometry(12+n*8,.08,6,72),new THREE.MeshBasicMaterial({color:0x66e5dc,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}));ring.rotation.x=Math.PI/2;ring.position.y=18;ewPulse.add(ring);}ewPulse.visible=false;ship.add(ewPulse);
 ship.userData={shipClass:'ticonderoga',launcherKind:'mk41',vlsCells,radar,sps49,fireControl,directors,sensorFaceModels:arrays,fixedSensorFaceHealth:[1,1,1,1],highDetail,mediumDetail,lowDetail,smokePuffs,flag,hullMat,ewPulse,navigationLights,lightBulbs,detail:[forwardHouse,bridge,aftHouse,hangar,foreMast,aftMast,forwardVls,aftVls,foreGun,aftGun,foreCiws,aftCiws,...directors,...arrays]};
 return ship;
}

export const TICONDEROGA_METADATA:Omit<ShipDefinition,'build'>={
 id:'ticonderoga',name:'USS LAKE CHAMPLAIN',hullNumber:'CG-57',era:'1990s AEGIS',role:'AEGIS AIR DEFENSE CRUISER',launcherKind:'mk41',hullColor:0x687678,
 launcher:{kind:'mk41',displayName:'MK 41 VLS',compatibleWeapons:['SM-2MR','SM-2ER'],columns:8,sequenceInterval:.5,exhaustClearance:1.6,isolationStartsAt:.75,maximumIsolationFraction:.48,loadingPermutation:17,gridSize:64},
 fixedSensorFaces:{sensorName:'AN/SPY-1B',subsystemId:'sps48',labels:['BOW','STARBOARD','STERN','PORT'],headings:[0,Math.PI/2,Math.PI,-Math.PI/2],damageMultiplier:1.45,healthyColor:0xcbd0c8,damagedColor:0x4a302c,criticalEmissive:0x45120c},
 sensors:[{name:'AN/SPY-1B',threeDimensional:true,baseInterval:.42,maxRange:820,radarHeight:32,precision:1.12,scanMode:'phased-array'},{name:'AN/SPS-49',threeDimensional:false,baseInterval:1.05,maxRange:1100,radarHeight:38,precision:.75,scanMode:'mechanical'}],
 subsystemLabels:{sps48:'AN/SPY-1B',sps49:'AN/SPS-49',spg55:'AN/SPG-62',mk10Aft:'MK 41 AFT',mk10Forward:'MK 41 FWD',ciws:'PHALANX CIWS',ecm:'AN/SLQ-32',srboc:'MK 36 SRBOC',propulsion:'PROPULSION'},
 subsystemPositions:{sps48:new THREE.Vector3(7,13,0),sps49:new THREE.Vector3(4,25,0),spg55:new THREE.Vector3(10,14,0),mk10Aft:new THREE.Vector3(-25,6,0),mk10Forward:new THREE.Vector3(22,6,0),ciws:new THREE.Vector3(13,10,0),ecm:new THREE.Vector3(-2,15,4),srboc:new THREE.Vector3(-5,8,4),propulsion:new THREE.Vector3(-7,5,0)},
 ammo:{rim67:0,sm2mr:48,sm2er:32,ciws:1800,channels:6,illuminators:4}
};
